### ISSUE TITLE
HIV Management - Medications

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1093]
![image](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/7b9a3d5b-e65f-4728-b179-89a064be6406)
![Selection_353](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/6bcbebd0-87fe-4362-b2f1-813c834d065e)

**Comment by anvmn** [comment]
@adamhstewart 

Option 1 and Option 3 for medications is identical. How do we fix it?

![Selection_364](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/7c1754f5-5a26-4134-95fc-71861bf1e291)

**Comment by Diama1** [comment]
@anvmn Based on the HIV doc, here is the third option 
![Screenshot from 2024-04-03 10-53-20](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/4362f044-d838-43f6-984d-1f01978b239a)

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions:

1. Instead of adverse effect and effects, adverse events is displayed.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/dcb6806d-6d09-412f-b7f5-f1902cded50c)

### Checked and approved:

1. Prescribed medication screen looks and works per design
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/79afbae9-554b-468a-a4d7-c3bd9dc86c0b)

2. Treatment review screen looks and works per design except the difference in adverse effect pointed out in issues point 1. 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/489de9f5-9fa6-413a-9b16-86047e1977a5)

**Comment by adamhstewart** [comment]
@anvm changes for medications:

There are three categories of medication to be added, they should be labeled with the list headers on the screen exactly as they appear below

Most Common Anti-Retroviral Medications: 
- Dolutegravir + Lamivudine + Tenofovir (DTG-3TC-TDF) 
- Atazanavir + Ritonavir (ATZ/r) 
- Dolutegravir (DTG) 
- Abacavir + Lamivudine (ABC-3TC) called Kivexa in Burundi 
- Lamivudine + Tenofovir (3TC-TDF)
- Zidovudine (liquid) (AZT) 

Less Common Anti-Retroviral Medications:
- Lamivudine + Zidovudine + Nevirapine (3TC-AZT-NVP)
- Efavirenz + Lamivudine + Tenofovir (EFV-3TC-TDF)
- Lamivudine + Zidovudine (3TC-AZT)
- Lopinavir + Ritonavir (LPV/r)
- Darunavir + Ritonavir (DRV/r)
- Darunavir + Cobicistat (DRV/c)
- Raltegravir (RAL)
- Efavirenz (EFV)
- Nevirapine (tablet or liquid) (NVP)
- Etravirine (ETR)
- Tenofovir (TDF)
- Lamivudine (3TC)
- Abacavir (ABC)

Prophylaxis Medications
- Bactrim
- Dapsone
- Isoniazid
- Fluconazole
- Azithromycin

### Validation Logic
In order to submit the form, the user must pick at least one option from the first two groups. Multiple selections can be made in any group without limit.

### Other notes
- These medications are for all country settings (not just Rwanda or Burundi)

Bump +5h

**Comment by anvmn** [comment]
@LudmilaGoichman 

Please test https://github.com/TIP-Global-Health/eheza-app/issues/1093#issuecomment-2067783161 on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition
- Android tablet

### Questions:
1. In the fourth medication, "called Kivexa in Burundi" was omitted. Is it okay?

> Abacavir + Lamivudine (ABC-3TC) called Kivexa in Burundi

<img width="336" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b7fead40-d885-462b-8bb3-ed6aabc97d54">

2. I think, like all medication lists, the dose should be indicated and how many times to take it.

<img width="602" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/96653799-0eda-4b08-9a32-29b677e1bb43">|<img width="346" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1c534fe9-7140-4d64-af97-6d8bc1cbbca2">
---|---

### Checked and Approved:
1. If the CHW doesn't select medication from the first two groups, the "Save" button is disabled:

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/707c999a-d1ce-4478-834c-cc62cbd34933">

4. If the CHW selects medication from the first two groups, the "Save" button is enabled:

<img width="286" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d3613eec-206a-41c4-aaa9-df52341ba0c2">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7aca5798-d1ea-4580-a216-8b4d18fee81f">
---|---

5. The list of medications matches the comment (except the fourth medication) - https://github.com/TIP-Global-Health/eheza-app/issues/1093#issuecomment-2067783161

<img width="540" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7f108890-2541-487a-a549-e4622cb5bb4a">

**Comment by anvmn** [comment]
@LudmilaGoichman @adamhstewart 


> 1. In the fourth medication, "called Kivexa in Burundi" was omitted. Is it okay?
> Abacavir + Lamivudine (ABC-3TC) called Kivexa in Burundi

Looks like a comment to me, which may be implemented when applying translations.
In any case, it would make no sense to have this on Rwanda site, hence omited.

> 2. I think, like all medication lists, the dose should be indicated and how many times to take it.

We go by requirements. Right now, doses presentations were not requested.

**Comment by adamhstewart** [comment]
@anvmn update to meds

Under Prophylaxis Medication

Add:
- Trimethoprim and Sulfamethoxazole tablets (Adults)
- Dispersible Co-trimoxazole tablets  (Pediatrics)
- Co-trimoxazole Oral Suspension (Pediatrics)

Remove: 
- Dapsone
- Isoniazid
- Fluconazole
- Azithromycin
