### ISSUE TITLE
Group Education - Progress report

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1097]
## Issue

On the individual report we need to show the record of attended group education topics and the dates of the education.
This part will come through patient record.
| Patient record page | Group education page |
| ----------------------------- | --------------------------------- |
| ![Screenshot from 2024-04-02 15-39-44](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/3447ff96-8e28-41ae-a9cf-4d98c9c915ca) | ![Screenshot from 2024-04-01 10-11-54](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/e9115df5-b888-4c9b-8c69-f95d48b49efc) |

## Todo
- Create the screen per designs
- Implement the logic

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/#patient-record/

## QA Review

### Found issues and questions:

1. Not sure if it's important, but the table header says Date instead of education date. I think it's meaning is obvious and the shorter version is preferable.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/01226bda-b314-447c-9d0c-df1f190634a8)

### Checked and approved:

1. On the progress report the Health education tab lists the topics and dates.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7cea1693-eebf-4369-b4d3-b5793ff60901)
