### ISSUE TITLE
ANC Progress Report - Lab Section Change [3h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#118]
## Issue 

After feedback from the team, we are altering the lab section of the ANC progress report. The lab section will have a button that will take the user to a separate "pop out" screen that shows the lab results overview (how we have it currently just in a new screen alone). From there, the user can click on the blue arrow button to access the history of a particular lab (as it works now). 

[Here ](https://www.loom.com/share/df98c27d461647d7bbae8d92bac7e523) is a quick video overview. 

Figma files are [here](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746). 

Main Progress Report Section | Lab Results Overview | Particular Lab Overview 
--|--|-- 
![Anetnatal Progress Report](https://user-images.githubusercontent.com/77505464/151422097-2fc786ae-d06e-4895-8b9a-a3a9bc3d6f9a.jpg)|![Lab Result Pop Out-1](https://user-images.githubusercontent.com/77505464/151422112-bbceeb24-b923-430b-8ef9-634175844f88.jpg)|![Lab Result Pop Out](https://user-images.githubusercontent.com/77505464/151422143-2d477bd4-cf6b-420b-aa04-2cb77aa68982.jpg)

## To Do: 
- Style per design

**Comment by jeanette-pelizzon** [comment]
// @adamhstewart FYI

**Comment by anvmn** [comment]
@LudmilaGoichman 

All points fixed. Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon 

- Nutrition env
- tablet

### Questions/Found Issues:
1.  Photos still appear in the middle of the report instead of at the bottom as they do in the image in the issue description. It is correct?

| in the app (nurse)| in the app (CHW) | in the design |
---|---|---
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152188008-bc7dd97a-699b-43e9-ab5b-82a099896108.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152193722-70fec55c-f46a-40b1-9108-8c6b17f3e482.png">|![151422097-2fc786ae-d06e-4895-8b9a-a3a9bc3d6f9a_jpg__800×3785_](https://user-images.githubusercontent.com/35059802/152188159-ab30462d-7a18-43ca-a6c1-ae403cf6499a.png)

2. The CHW Activity section is not displayed in the report as it 's displayed in the design. Should this be fixed in the current issue?

CHW report (all activities completed and synced) | Nurse report in the first encounter after CHW encounter | Design |
---|--- |---
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152193406-3e440154-cc99-4bef-8d90-e6bdb3b84b38.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152194147-b2c15159-6885-4be6-b34a-b3363956e65b.png">|![151422097-2fc786ae-d06e-4895-8b9a-a3a9bc3d6f9a_jpg__800×3785_](https://user-images.githubusercontent.com/35059802/152194275-8005c344-f2c9-49dc-93e6-a13e7ac00ab6.png)

### Checked and Approved:
1. The lab section has the "See Lab Results" button that takes the user to a separate "pop out" screen that shows the lab results overview 
 
Nurse | CHW |
---|---
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152188503-769d92c9-16ce-4679-a542-a16081629d98.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152193526-27a89a19-e7c5-4092-be29-e5d67be4c850.png">

2. The separate "pop out" screen that shows the lab results overview after clicking the "See Lab Results" button:

Nurse:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152188901-df76d0ef-bfd5-4b31-bbd7-613711166dc0.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152188952-6e54970c-536e-4ceb-9a19-621d5f7a1076.png">
---|---

CHW:
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152193910-52add6c7-f08b-4951-b970-bd022336ad24.png">


3. In this, separate "pop out" screen, the user can click on the blue arrow button to access the history of a particular lab:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152189248-7128b8df-af04-4ef0-999e-fa343d2ccf61.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152189317-e1a57f3f-64a8-4f01-9716-00570f4324f4.png">
---|---

4. the Back arrow on the Lab Results and Lab History screens works as expected - returns to the previous screen

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152190138-0d88efe5-198c-4124-8b59-5d73978098d3.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152190178-e315bb18-40c2-4cc8-bf18-5dfdc52dbcf1.png">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Photos still appear in the middle of the report instead of at the bottom as they do in the image in the issue description. It is correct?

This is part of #91, and not deployed yet.

> The CHW Activity section is not displayed in the report as it 's displayed in the design. Should this be fixed in the current issue?

@Diama1 is working on it, and it's still in progress.
