### ISSUE TITLE
ANC Logic - Diagnosis + Next Steps: HIV [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#124]
## Issue 

First, read #165 regarding the updates to the HIV lab flow and the questions that were added to make these diagnoses. 

If an HIV test is run, there will be next steps required.  

Here is an [explainer video](https://www.loom.com/share/d6919a5512b04fd7b4aba912570b6d43). 

All next steps have the same health education step after the diagnosis and before any medication distribution. 

![Positive PMTCT 2](https://user-images.githubusercontent.com/77505464/154877243-af66e987-f7b2-459a-9070-8e693f9b61c7.png) 

If a patient is **POSITIVE** for HIV and the health center **has HIV services**, the patient will have the following next steps: 
Diagnosis | Referral
--|-- 
![Positive PMTCT 1](https://user-images.githubusercontent.com/77505464/154876156-a35f1af9-ea06-4207-8961-7b9a8b41fe8a.png) | ![Positive PMTCT 3](https://user-images.githubusercontent.com/77505464/154876160-50ba645c-6791-4dc4-a562-53facb750c41.png)

If a patient is **POSITIVE** for HIV and the health center **does NOT have HIV services**, the patient will have the following next steps: 
Diagnosis | Referral
--|--
![Positive No Program 1](https://user-images.githubusercontent.com/77505464/154876188-fc28f0b1-b31c-4f9e-8c5d-0d3cdcdf1941.png) | ![Positive No Program 3](https://user-images.githubusercontent.com/77505464/154876192-f26eca1d-76cc-49f7-9c5d-ab89858e1119.png)

If the patient is **NEGATIVE** for HIV with a **POSITIVE PARTNER** who is **NOT ON ARVs** the patient will have the following next steps: 
Diagnosis | Referral
--|--
![Neg, PartPos,Arvs No 1](https://user-images.githubusercontent.com/77505464/154876305-4b2c0237-2451-443b-aeb7-42c6ec50a975.png)| ![Neg, PartPos,Arvs No 2](https://user-images.githubusercontent.com/77505464/154876306-a85018be-3ad4-46c9-a568-75622dd4f2af.png)

If the patient is **NEGATIVE** with a **POSITIVE PARTNER** who **IS ON ARVs** but does **NOT HAVE A SUPPRESSED VIRAL LOAD**
Diagnosis | Referral
--|--
![Neg, PartPos,Arvs Yes 1](https://user-images.githubusercontent.com/77505464/154876473-73c26fe4-459a-4a6c-92d4-ffe27fe72b5e.png)| ![Neg, PartPos,Arvs Yes 2](https://user-images.githubusercontent.com/77505464/154876475-88c6a215-a45f-4c71-9ac2-6121c78b7f04.png)

If the patient is **NEGATIVE** with a **POSITIVE PARTNER** who **IS ON ARVs** with a **SUPPRESSED VIRAL LOAD** 
OR

If the patient is **NEGATIVE** with a **NEGATIVE PARTNER**,then these are the next steps

![Negative](https://user-images.githubusercontent.com/77505464/154876553-3fde6ace-91d0-4391-9712-92df58e2b3f0.png)

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021)

## Note: 
- The next steps should appear after the initial encounter with the patient, not after they return for lab results. 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Style next step screens per design 
- Adjust logic per document

**Comment by anvmn** [comment]
@jeanette-pelizzon 
How do we know that patients partner is positive?

**Comment by jeanette-pelizzon** [comment]
Ignore all ANC logic issues for now.  However, there is a question that is asked during the encounter about the partner.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Ignore all ANC logic issues for now. However, there is a question that is asked during the encounter about the partner.

Well, I did find that we ask patient if partner was tested for HIV during preganancy:

![Selection_488](https://user-images.githubusercontent.com/17882245/153294361-9cd8a5c8-6930-483e-bf10-26a34b1e3d64.png)

If the answer is Yes, no matter the result, we do not ask at subsequent encounters.

He're some thoughts about this:

1. If partener took the test and got negative result, we consider him to be negative throughout the pregnancy. This is a little problematic, since partner can turn positive at latter time during pregnancy, but this is a clinical decision.
2. If the answer is No, we do not know what partner state is. In this case, we will assume that the partner is negative.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Another question - how do we know if HC got HIV services or not?

**Comment by jeanette-pelizzon** [comment]
@anvmn updated this issue so it is good to be worked on now. All your previous questions should be addressed now. Be sure to check out #165 first. Then this issue. I made videos for each one to explain them a bit more. Let me know if you have any questions.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Question about warning popup: should we navigate to next steps when one diagnoses is made? 
Or, similar to point 3 from https://github.com/TIP-Global-Health/eheza-app/issues/136#issuecomment-1054616309, popuop should appear when we enter Next Steps activity?

**Comment by jeanette-pelizzon** [comment]
It should appear when we enter the next steps. Would it be helpful for me to go through all the different diagnoses and say which ones specifically interrupt the flow or come in the next steps section? @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Yes, it will help alot. Thanks,.

**Comment by jeanette-pelizzon** [comment]
@anvmn 
<img width="697" alt="Screen Shot 2022-03-02 at 3 58 29 PM" src="https://user-images.githubusercontent.com/77505464/156448599-92fe64c2-5b6e-4ca6-89b7-1e63415cbd9d.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Thanks. We better add it to https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- Positive HIV, no PMTCT, shows health education, meds, and referral as expected
- Negative, HIV Discordant partner (either on ARVs or without reduced viral load) hows health education, meds, and referral as expected
- proper health education questions show for each scenario

### Needs followup
- Positive HIV + PMTCT services available - medications are removed as expected, but the question "Will you accompany the patient..." is missing
- Med distribution has the disbursement question under each action rather than each all together as the design above shows... maybe this was for consistency elsewhere?

![image](https://user-images.githubusercontent.com/688507/160716958-f38a150a-42e4-489d-8367-a7a1a92f6fcd.png)

- Before "Actions to take" under medication distribution, there is supposed to be a sentence that describes the condition (e.g. "This patient is part of a discordant partnership." - but it does not appear in the app:

![image](https://user-images.githubusercontent.com/688507/160717330-e19f1c7d-ac7a-4238-8b16-ad50a9bb4547.png)

- It seems we changed "Diagnosis + Medicine" to just "Medication Distribution." If a patient has both HIV and Malaria, they get both sub activities, which seems wrong to me. Referring to @jeanette-pelizzon for review:

![image](https://user-images.githubusercontent.com/688507/160717537-d595cc16-f935-4635-bf9c-b1d936c2ab74.png)

**Comment by jeanette-pelizzon** [comment]
HIV+ with No Program the screen is correct. It is three separate pills (at least that was my understanding). The others get a combo pill I believe? 

This is the screen I have for that in the design: 
![Positive No Program 3](https://user-images.githubusercontent.com/77505464/160924085-82d6530a-0a71-414e-aaad-3cca5e6c9e70.png)

// @adamhstewart should I double check with Wendy?

**Comment by jeanette-pelizzon** [comment]
> It seems we changed "Diagnosis + Medicine" to just "Medication Distribution." If a patient has both HIV and Malaria, they get both sub activities, which seems wrong to me. Referring to @jeanette-pelizzon for review

Yes the diagnosis is just the pop up and then it should be medication distribution. If they have medications for two things then they can be stacked.

**Comment by jeanette-pelizzon** [comment]
@anvmn we have had to update the medication for HIV positive patients in this flow. I assumed I would need to create a new issue, which can be found #210 

Let me know if I need to just update this issue instead. 

// @adamhstewart

**Comment by anvmn** [comment]
@adamhstewart 

> Positive HIV + PMTCT services available - medications are removed as expected, but the question "Will you accompany the patient..." is missing

Maybe you're expecting to find the question on another location?
The question appears on the Refeeral activity:

![Peek 2022-04-07 10-41](https://user-images.githubusercontent.com/17882245/162147054-870b5f1c-951d-4429-9f3a-1fbcb9e295d5.gif)
