### ISSUE TITLE
ANC Labs - Wait Subactivity [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#186]
## Issue 

There is a new subactivity called "Wait" which will be in three scenarios:

-  if lab results require a patient to wait 
- if a patient needs to come back to have their vitals rechecked 
- if a patient need to wait for both labs and vitals 

Labs Wait | Vitals Wait | Both Wait 
--|--|--
<img width="280" alt="Screen Shot 2022-03-16 at 12 28 13 PM" src="https://user-images.githubusercontent.com/77505464/158639381-0eba079d-80d1-4494-840d-208ecdf7d976.png"> | <img width="282" alt="Screen Shot 2022-03-16 at 12 28 09 PM" src="https://user-images.githubusercontent.com/77505464/158639345-b4284741-30ce-4ebd-9ee6-f7e08595e28f.png"> | <img width="281" alt="Screen Shot 2022-03-16 at 12 28 19 PM" src="https://user-images.githubusercontent.com/77505464/158639420-6e84c0ae-7701-4ba8-8311-4345755282a2.png">

To Do: 

- Create new sub activity 
- Logic behind which version should appear when

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Can't find that Wait icon under Design Assets on Figma. Please add. 

Thanks.

**Comment by jeanette-pelizzon** [comment]
I need to show you the new Figma layout today. You can find the icon [here](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A16) on the subactivity icon frame. It's in the bottom right corner.

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- Sub activity and icon appear as designed
- new page and logic of messages appear and work as designed

### Needs followup
- The progress report still appears automatically after Diagnosis and medicine - it should only appear after "wait"\
- Not exactly part of this issue, but the progress report should have an "end encounter" button as per the design so that the nurse does not need to back out to the tray to end the encounter.

**Comment by adamhstewart** [comment]
@anvmn moving this over in favor of #203 - please do remember that progress report needs to be removed both after diagnosis and medication AND wait.
