### ISSUE TITLE
Build foundation for subsequent Acute Illness encounters at Health Centers [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#199]
## Issue 
Currently, Nurses at the Health Center are blocked from accessing subsequent visits at the HC that were created at the HC. While it is not a common occurrence, a nurse should be able to see a patient more than once for the same illness.

## Tasks
- Create the foundations to allow for an illness to be accessed at the health center after it was already seen there.
- Allow access from the front end "entry" screen to an existing acute illness (currently grayed out):

![image](https://user-images.githubusercontent.com/688507/160501212-af6ee241-745b-4193-b5b9-879457306865.png)

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

QA Review

### Found issues and questions:

1. The first time I selected the existing acute illness option, both the New acute illness and the Existing acute illness options were available. I have ended this existing acute illness as cured, and then came back and created a new acute illness. Afterwards, only the Existing acute illness option was displayed as enabled, and on the next screen the First acute illness encounter was also disabled. Is this by design?
![4-disabled](https://user-images.githubusercontent.com/3536805/169533521-17ce10bf-5d6f-4e26-a8e6-3e3e9308a480.png)
![5-disabled](https://user-images.githubusercontent.com/3536805/169533539-c5c28d59-5c42-46cc-ae55-21875a4e2f83.png)


### Checked and approved:

1. The Select existing acute illness option is available.
![1-existing-acute-illness](https://user-images.githubusercontent.com/3536805/169527218-d350892a-851e-4205-a9cc-5866e0daf306.png)

2. After selecting the above option, some information is available from the existing acute illness.
![2-existing-info](https://user-images.githubusercontent.com/3536805/169527433-8dd64ae3-2e1f-4039-a1af-0b5b88eea24c.png)
