### ISSUE TITLE
Designate point of referral for an Acute Illness [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#200]
## Issue
At the Health Center, before beginning an encounter, the nurse should be aware if the referral (i.e. the patient was last seen at) the Health center or the CHW.

This notification should be made on the entry screen for the encounter:

![image](https://user-images.githubusercontent.com/688507/160501842-01a33168-ee84-4b0d-9f56-860f6a390a16.png)

The text options are:
- CHW Referral
- Health Center Referral

## Task
- Create the logic that identifies the most immediate previous encounter for the illness as a CHW or HC encounter.
- Render the text notification on the screen.

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The first two rows have 25px line height, the 3rd row has 21px line height.
![2-line-height-padding](https://user-images.githubusercontent.com/3536805/169534863-465486f8-7d85-4879-9e92-06cbcee3be77.png)


2. The padding between the first two lines and the 2nd and 3rd lines is different. See image above. -Is this grouping of text intentional?

### Checked and approved:

1. The requested text is displayed on the option.
![1-text-added](https://user-images.githubusercontent.com/3536805/169534962-b578b9a2-6f03-4550-83a1-a7ff65b1e849.png)
