### ISSUE TITLE
Review progress report step should come only after Labs are entered + other workflow adjustments [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#203]
## Issue

Right now the progress report comes up at the end of the first part of the encounter before the labs are entered, but it should only be reviewed after the labs/vitals recheck are entered.

In addition, since this is not the end of the encounter, the language on the button to close out of the activities should be different,

Also, After the user views the progress report after "next steps" (in the second "part" of the encounter), if the user uses the back arrow, you return to an activity tray for the first party of the activity. See video:

https://www.loom.com/share/1279578766c84665b66d97c84150b8bd

## Tasks
- Remove logic that displays progress report in the case there are any labs to enter or vitals to recheck (if there are no additional tasks, the progress report can be displayed.
- On the first part of the encounter change the button text from "End Encounter" to "Pause Encounter"
- Add text on the "Wait" screen: "To proceed with more encounters while you wait for test results or a vitals recheck, touch "Pause Encounter" below to leave this encounter. You can return to it from the case management screen."
- Add "Close Encounter" at the bottom of the progress report
- Add the usual dialog that warns that closing (or pausing) the encounter means that no more data can be entered (in both parts of the encounter).
- ensure that "backing out" of the progress report returns to the proper "part" of the encounter"

Note: @jeanette-pelizzon I think we'll need some new design here and some adjustment to the workflow in Figma

**Comment by jeanette-pelizzon** [comment]
here are the new wait screens:


Wait Vitals | Wait Labs | Wait Both 
--|--|--
![Next Steps Template-1](https://user-images.githubusercontent.com/77505464/160918589-eb8b1a79-6b02-4446-8d23-b37533b42a03.jpg) | ![Next Steps Template-2](https://user-images.githubusercontent.com/77505464/160918612-57a97ef9-c2a3-4c8b-a1a9-5390104257eb.jpg) | ![Next Steps Template](https://user-images.githubusercontent.com/77505464/160918631-75f03a12-f4eb-4e07-91ec-a684496e6a64.jpg)

**Comment by jeanette-pelizzon** [comment]
With the progress report, it's meant to show at the beginning of the *first encounter* only if the patient has seen a CHW previously. They was the nurse can see the CHW activities that took place. If the patient has not previously seen a CHW before the first encounter, then no progress report should (or would be able to) be shown.  The progress report should appear at the actual end of every encounter (not during the "wait" period) 

With any subsequent encounters, the progress report should be shown at the beginning and the end of the encounter.

I think the issue is that we are technically ending the encounter during the wait period so that may be why it is being triggered there as well. 

// @anvmn

**Comment by adamhstewart** [comment]
@anvmn note, I edited the initial issue with one more aspect - to ensure that "backing out" of the progress report brings you to the right context.

**Comment by anvmn** [comment]
@adamhstewart 

> Add text on the "Wait" screen: "To proceed with more encounters while you wait for test results or a vitals recheck, touch "Pause Encounter" below to leave this encounter. You can return to it from the case management screen."

This text is a little missleading, because there's no such button bellow.
Real form will show:

![Selection_634](https://user-images.githubusercontent.com/17882245/161973067-1c1f19d8-9835-4a00-b970-1bc669b02219.png)

As any actvity, Wait should be saved to record the action.
Also, other sub activities at next steps may be not completed yet, and therefore,
we can not guarantee that saving Wait completes this phase of encounter.

//cc @jeanette-pelizzon

**Comment by jeanette-pelizzon** [comment]
Let's say a patient has multiple diagnoses. When they are in next steps do we have it currently popping up Diagnosis one then going through all the next steps pertaining to that diagnosis. Then it pops up the 2nd diagnosis and runs through those next steps? 

OR  is it popping up all the diagnosis at the beginning and stacking the next steps? 

// @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

One popup with all diagnoses

**Comment by jeanette-pelizzon** [comment]
Alright, so then each stage should be stacked as well - all the diagnosis pop up together, all the health education in one screen, all the medication distro in one screen, referral (can just be the one referral since they are all the same). So the wait activity should be at the end of each next steps flow. Because of that then the button at the bottom can be changed from saved to pause encounter (on the back end it can do the same thing it's just confusing language). 

// @anvmn @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

> So the wait activity should be at the end of each next steps flow. 

As we discussed, Wait will appear only when all other next steps tasks are completed, and
will have 'Pause encounter' button.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Progress report displays only after filling out labs section.

2. Button text is Pause encounter.
![5-pause-encounter](https://user-images.githubusercontent.com/3536805/178230551-77977714-d2cc-428b-9d81-3dd33da604c8.png)

3. Wait screen text is changed as requested:
![5-wait-text](https://user-images.githubusercontent.com/3536805/178230753-85c1e2ba-5b8c-4640-985c-8ec6df5d6671.png)

4. On the bottom of the progress report the button text is End encounter.
![3-end-encounter](https://user-images.githubusercontent.com/3536805/178231700-db3b9ea9-31b2-4f2f-ab2e-4bc83c9d5eed.png)

5. Ending the encounter displays the warning that entering or editing more data is not possible.
![7-end-encounter-warning](https://user-images.githubusercontent.com/3536805/178232157-4c15d964-a04e-4050-bb2c-66c33366235e.png)

6. Backing out of the Progress report in second part of the workflow returns to the second part.
![4-after-back-from-report](https://user-images.githubusercontent.com/3536805/178231511-70dd74ee-950f-425a-939a-6384afbec39c.png)
