### ISSUE TITLE
Feature: ANC Subsequent Visit 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#226]
## Feature Description 

This feature updates aspects of the ANC subsequent visit at the Health Center, as well as diagnosis and next steps logic. This logic incorporates health protocols and allows for consistency of care.

## Logic Document 
The logic for ANC subsequent visit can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) under the ANC - Nurse tab. You'll see a blue line that shows where the logic for the subsequent visit begins. 

## Design Assets
The design elements can be found in the components file[ here](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=0%3A1). You can view the flow in figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) 
## Tracked Issues

**Symptom Review**
- #227 
- #228
- #229
- #230
- #231
- #232
- #233 
- #234
- #235 
- #236
- #237
- #238 
- #239 
- #240
- #241 
- #242
- #243
- #244
- #245
- #246 

**Treatment Review**
- #247 
- #248 
- #249 
- #250 
- #251
- #252
- #253 
- #279 
- #256 
- #263 
- #265
- #266
- #284 

**History** 
- #257 

**Labs**  
- #258
- #260
- #270
- #264 

**Immunizations**
- #261
- #269

**Progress Report**
- #267
- #268

**Other**
- #271 
- #259 
- #273

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Currently we have:

![Selection_711](https://user-images.githubusercontent.com/17882245/166161262-654c79b1-9c69-4745-b28d-0471aa47b263.png)

At design we have:

![Selection_710](https://user-images.githubusercontent.com/17882245/166161247-02ff0464-da4f-4b14-803c-c5eca164c3a5.png)

- History and Examination have switched places. Is this intentional?
- Don't see Malaria prevention activity anymore. Why is that?

**Comment by jeanette-pelizzon** [comment]
I do not see the malaria prevention activity in the nutrition environment. This is what I see: 
<img width="715" alt="Screen Shot 2022-05-02 at 10 46 49 AM" src="https://user-images.githubusercontent.com/77505464/166260228-e9df40d4-7349-48ea-9698-0ddc41662123.png">

History and Examination were switched in design by accident. This screen shot shows all the activities for subs visit as I have them now: 
<img width="322" alt="Screen Shot 2022-05-02 at 11 40 03 AM" src="https://user-images.githubusercontent.com/77505464/166263324-36d96d95-691e-4746-a600-000cae89cfc8.png">

**Comment by jeanette-pelizzon** [comment]
updated to include the malaria activity (it only appears if not done previously) 

<img width="307" alt="Screen Shot 2022-05-03 at 3 57 25 PM" src="https://user-images.githubusercontent.com/77505464/166555889-d07f39f8-7bfd-4f32-926c-5daa567bc4d0.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Question:

1. We have Immunization in the above images and on the design. Is this not implemented yet, or does it have some special requirements for it to display? @anvmn 

### Checked and approved:

1. Order of icons in a subsequent encounter are the same as on the design. (Malaria prevention is missing because it was already answered with yes).
![1-icons](https://user-images.githubusercontent.com/3536805/177155569-0aaf2bd1-2a8e-4395-9f98-7ecc25173f41.png)

**Comment by jeanette-pelizzon** [comment]
@balagan73 immunization only appears if they have not met the requirement for tetanus already. I am unsure if this has been deployed to the testing environment yet. @anvm?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Immunization development was deployed 7 days ago.
@balagan73 tested this already - https://github.com/TIP-Global-Health/eheza-app/issues/261#issuecomment-1178592184.
