### ISSUE TITLE
ANC Subs Visit - Next Steps - Possible Pyelonephritis [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#243]
## Issue 

When a patient identifies that they have the following, we refer them to the hospital. 
(1) Symptom Review: Burning with Urination + flank pain 

Pop-Up | Referral
--|-- 
<img width="336" alt="Screen Shot 2022-04-26 at 5 32 32 PM" src="https://user-images.githubusercontent.com/77505464/165396073-30435352-4a04-4f85-a20f-543c52f7d015.png"> | <img width="335" alt="Screen Shot 2022-04-26 at 5 32 39 PM" src="https://user-images.githubusercontent.com/77505464/165396074-58a82442-b525-40bb-ba76-d6b4b308d52a.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. When conditions are fulfilled, no next steps display. I have tried all 3 options for flank pain.

Condition1|Condition2|No next steps
-|-|-
![1-burning](https://user-images.githubusercontent.com/3536805/176444342-5d696b7c-8084-44e2-9256-e8e613f49839.png)|![4-flank-pain](https://user-images.githubusercontent.com/3536805/176444547-48052e7b-8547-4918-b1a7-720b585000e2.png)|![3-no-next-steps](https://user-images.githubusercontent.com/3536805/176444589-f783f90a-9a05-4fca-98d1-2b9a97ab005b.png)
 
 UPDATE: https://github.com/TIP-Global-Health/eheza-app/issues/242 with new patient had no problem with diagnoses, so there was something with the history of this specific patient. As @anvmn told me there was an issue if Danger signs was not filled. That issue is fixed, but not yet deployed. Going to came back in a minute to test this issue with new patient.

2. Warning text is really concise. See image below. Is that a problem?

### Checked and approved:

1. With new patient when Symptom Review is Burning with Urination + flank pain, the diagnosis is pyelonephritis.

Symptom|Warning|Next steps
-|-|-
![4-flank-pain](https://user-images.githubusercontent.com/3536805/176452131-3576527b-68bf-4008-a583-8df44293eefd.png)|![5-warning](https://user-images.githubusercontent.com/3536805/176452188-cd1b9077-a399-4958-92ac-e737cbcd3c13.png)|![6-hospital-referral](https://user-images.githubusercontent.com/3536805/176452205-0dc27994-2f97-4f6c-bcdb-10b6d9f7f6fd.png)
