### ISSUE TITLE
ANC Subs Visit - Next Steps - Candidiasis (Yeast Infection) [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#244]
## Issue 

When a patient identifies that they have the following symptoms, we provide health education and medication: 
(1) Symptom Review: Burning with Urination + vaginal itching or discharge

Pop-Up | Health Education | Medication
--|--|-- 
<img width="316" alt="Screen Shot 2022-04-26 at 5 35 24 PM" src="https://user-images.githubusercontent.com/77505464/165396449-994f80ae-8613-46d8-ad47-93673ecf06d7.png"> | <img width="320" alt="Screen Shot 2022-04-26 at 5 35 30 PM" src="https://user-images.githubusercontent.com/77505464/165396451-8d896e4c-d4db-43fb-a0a6-13fd307cac08.png"> | <img width="320" alt="Screen Shot 2022-04-26 at 5 35 37 PM" src="https://user-images.githubusercontent.com/77505464/165396452-7807ab86-0050-4f2e-b431-fe11f5aec638.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity. If they are being referred to the hospital for multiple things, there is only one referral screen. 

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated health education screen to include question: 

<img width="326" alt="Screen Shot 2022-05-03 at 1 04 52 PM" src="https://user-images.githubusercontent.com/77505464/166503531-193f4341-30d0-4923-b0d3-02af162a55f2.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Looking at Figma, seems to me that this diagnosis is also made for `Abnormal Vaginal Discharge +  itching`:

![Selection_731](https://user-images.githubusercontent.com/17882245/167791791-df32808a-cd5f-4939-8230-60a905f1bbc9.png)

However, I don't see it mentioned in Logic file, and there's no issue for that.
Please advice.

**Comment by jeanette-pelizzon** [comment]
@anvmn had to go back into notes to clarify but there are three ways to diagnose candidiasis. I have updated them on the logic document [here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Thanks. Please update issue description as well, for consistency.
It will help preventing confusion and may save time when this gets to QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Popup text is different: 
![2-candidiasis](https://user-images.githubusercontent.com/3536805/175544865-64cb1c6a-9c4b-499c-a314-5fb41dda0a71.png)

2. Council should be Counsel.
![4-grammar](https://user-images.githubusercontent.com/3536805/175545123-cb779786-de60-4565-bc34-d7a9c128a1d1.png)

3. Health education screen has text 'Burning with urination' instead of 'Burning on urination'. Is that a problem?
![3-health-education](https://user-images.githubusercontent.com/3536805/175545648-f54b5e1e-d831-41c7-b299-94aaae9cbfe3.png)

4. Question about vaginal discharge is duplicated. It exists on the symptom review page, and also in the follow up questions.
Selecting the first one will trigger trichomonas, while selecting the latter combined with burning while urinating triggers candidiasis diagnosis. This is ambiguous, and if nurses are not trained to make difference, it can lead to misdiagnoses, where prescribing Metronidazole just helps in the development on candidiasis.

Symptom review|Follow up
-|-
![5-discharge](https://user-images.githubusercontent.com/3536805/175551818-ff537155-374a-49db-ab8c-e3ca7bef2f52.png)|![4-discharge](https://user-images.githubusercontent.com/3536805/175551220-de768191-5b99-4698-a82d-6a9d9ea2e31a.png)

5. When symptoms are Burning with urination + Vaginal itching, or Burning with urination + vaginal discharge, No Next steps displayed.
UPDATE: This is probably caused by some other issue (Danger signs not filled), because with new patient I could not reproduce it.

Preconditions|No Next steps
-|-
![1-burning](https://user-images.githubusercontent.com/3536805/176443324-7c3e38a3-2dab-4576-9be2-af95e3e54c54.png)![2-itching+vd](https://user-images.githubusercontent.com/3536805/176443341-ea64a9b8-c238-4b43-a29c-8496568b49f2.png)|![3-no-next-steps](https://user-images.githubusercontent.com/3536805/176443346-a0d95a26-a51b-4f9c-9e42-ba1acaeba527.png)


### Checked and approved:

1. Health education screen includes follow up question.
![3-health-education](https://user-images.githubusercontent.com/3536805/175546013-9347bbb5-15df-4132-abae-c04f6d606a4d.png)

2. Medication screen includes correct medications.
![5-meds](https://user-images.githubusercontent.com/3536805/175546099-ce5acdde-b454-46ab-82dd-3d53e0896f20.png)

**Comment by adamhstewart** [comment]
@Diama1 please fix the two issues found on the QA report.

**Comment by Diama1** [comment]
> @Diama1 please fix the two issues found on the QA report.

@adamhstewart I am seeing only one issue on the **Counsel**

**Comment by adamhstewart** [comment]
@Diama1 

1. > Popup text is different:
2. > Council should be Counsel.

**Comment by balagan73** [comment]
@adamhstewart I have updated my above report with issue number 5, whereas no next steps display after conditions are fulfilled.

**Comment by Diama1** [comment]
> https://nutrition-ihangane.pantheonsite.io/
> 
> ### QA Review
> ### Found issues and questions:
> 1. Popup text is different:
>    ![2-candidiasis](https://user-images.githubusercontent.com/3536805/175544865-64cb1c6a-9c4b-499c-a314-5fb41dda0a71.png)

@jeanette-pelizzon Could you please share the correct text that was supposed to go on this popup?

**Comment by jeanette-pelizzon** [comment]
@Diama1 
<img width="297" alt="Screen Shot 2022-06-29 at 2 29 06 PM" src="https://user-images.githubusercontent.com/77505464/176509813-a4d52999-d239-4a78-b2c5-95702361fe5d.png">

**Comment by Diama1** [comment]
@jeanette-pelizzon thank you

**Comment by anvmn** [comment]
@balagan73 

Please verify that typos and popup text are fixed.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Popup text is fixed.
![image](https://user-images.githubusercontent.com/3536805/183281313-e4b81a2d-dc7e-47e4-b5c5-9a70b18455b6.png)

2. Typo is fixed:
![image](https://user-images.githubusercontent.com/3536805/183281398-0d209180-5155-4a51-9109-f3f11e245933.png)
