### ISSUE TITLE
ANC Subs Visit - Treatment History - HIV Medication [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#249]
## Issue 

Under the "Treatment Review" activity, an HIV medication sub-activity will populate if the patient was diagnosed with HIV in a previous encounter. This is necessary for the healthcare worker to follow up with the patient and ensure they are correctly taking their medications and that their symptoms are improving. This activity will only populate for patients who were diagnosed with HIV previously in this pregnancy OR were given TDF + 3TC because they were part of a discordant partnership.

There are two different flows for HIV medication depending on if the patient was referred to a PMTCT program in the first encounter. 

**PMTCT Patient**
Screen One | Answer = NO | Answer = Yes 
--|--|--
<img width="285" alt="Screen Shot 2022-04-27 at 1 48 17 PM" src="https://user-images.githubusercontent.com/77505464/165588332-0dad67b4-5e41-47fe-9ba0-693b186e12af.png"> | <img width="244" alt="Screen Shot 2022-04-27 at 1 48 29 PM" src="https://user-images.githubusercontent.com/77505464/165588333-68296d20-7594-41fd-a427-dd9e151168ce.png"> | <img width="242" alt="Screen Shot 2022-04-27 at 1 48 39 PM" src="https://user-images.githubusercontent.com/77505464/165588334-e500992a-1da4-4451-92e2-38026a11c5d5.png">

The green notes at the bottom tell you where this screen will lead as in one case they will need to redo the HIV flow from the 1st encounter to prescribe the correct medicine. 

**NOT PMTCT** 
<img width="251" alt="Screen Shot 2022-05-17 at 12 42 02 PM" src="https://user-images.githubusercontent.com/77505464/168864359-74c485cc-bd90-4c1d-9471-85216cb6486b.png">

**Discordant Partnership** 
<img width="264" alt="Screen Shot 2022-04-27 at 2 18 36 PM" src="https://user-images.githubusercontent.com/77505464/165593239-79f5aa75-6c59-45b7-85df-9abe27af171a.png">

## Design Files:
You can see the Figma file [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=424%3A24920)

You can access the medication icon[ here.](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A28) 

Here is the icon that should be used: 
![Medication](https://user-images.githubusercontent.com/77505464/165603581-f3ccec29-c281-48d3-be18-c41b8aa4c484.jpg)

## Related Issues: 
- #279 
- #264

## To Do: 
- Create HIV medication sub-activity 
- Create logic for the two different pathways 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. To be crystal clear here, this issue is only about questions at Treatment review.
The comments we have in green are not related to this specific issue:

![Selection_742](https://user-images.githubusercontent.com/17882245/168486696-35e9e46c-7459-4765-b96a-a04c7050e5bd.png)

Please confirm.

2. Patient that is HIV positive, and not referred to HIV program is given ARVs and Dolutegravir(50 mg). Why don't we mention Dolutegravir(50 mg)?

![Selection_743](https://user-images.githubusercontent.com/17882245/168488040-056b8b79-a480-4c27-9b2e-06b570ac159e.png)

Also, it's may not be previous visit, because previous visit could be second, third, fourth .. nurse encounter.

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> 1. To be crystal clear here, this issue is only about questions at Treatment review.
>    The comments we have in green are not related to this specific issue -- **Yes you don't need the green comments for this issue**

2. this was just an example - if they are prescribed different meds then those should populate there and have the related follow up questions

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Do we have clarification for this?
Do we track here only the HIV diagnosis, or the Discordant Partnership diagnosis as well?

**Comment by jeanette-pelizzon** [comment]
@anvmn updated the main issue. 

1. there are now screenshots for PMTCT, Not PMTCT and discordant partnership (we will be tracking discordant couples now)

2. the green notes in the PMTCT screen shots should be taken into account because in some cases they will have to redo the HIV flow from the 1st encounter to get the right meds.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> 1.there are now screenshots for PMTCT, Not PMTCT and discordant partnership (we will be tracking discordant couples now)

+2h please

> 2. the green notes in the PMTCT screen shots should be taken into account because in some cases they will have to redo the HIV flow from the 1st encounter to get the right meds.

Please open separate issue with detailed requirements.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Question:

1. When flow restarts because patient did not receive medication from PMTCT, the wording of the first question is different from design. Is this a problem?
![5-pmtct-no-meds-redo](https://user-images.githubusercontent.com/3536805/175058662-48287f6d-47da-4d59-bac6-08bd7aaae8ba.png)


### Checked and approved:

1. 

PMTCT patient|No medication|Medication
-|-|-
![1-pmtct-medication](https://user-images.githubusercontent.com/3536805/175058145-f8917868-ffe6-44ff-9287-c8f7cb65c2e4.png)|![2-no-meds](https://user-images.githubusercontent.com/3536805/175058266-9572315a-7dea-45ae-b133-4ae0a9a8df22.png)|![3-yes-meds](https://user-images.githubusercontent.com/3536805/175058272-42494075-f82c-4c78-be6c-5e323c162663.png)

2. When patient received no meds after being referred to PMTCT, flow restarts:
![4-pmtct-no-meds-redo](https://user-images.githubusercontent.com/3536805/175058470-ae744d17-970e-44ef-bfe6-179dead33bbd.png)

3. 

Not surpressed viral load|Surpressed viral load
-|-
![6-discordant-partner-not-surpressed](https://user-images.githubusercontent.com/3536805/175229311-df43654d-c3b3-4fda-aaa5-357c7e5d4771.png)|![9-surpressed](https://user-images.githubusercontent.com/3536805/175229346-9381a8bd-b1b9-4871-8f68-405eb472ac88.png)
![7-warning](https://user-images.githubusercontent.com/3536805/175229377-0e4defec-f8f9-4de6-b9ab-6d44397ad877.png)|
![8-tdf-3tc](https://user-images.githubusercontent.com/3536805/175229432-25efeaf1-a951-45fc-b8f2-e928e1a39dab.png)|

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. 
PMTCT - no medicine|PMTCT - medicine
-|-
![2-no-meds](https://user-images.githubusercontent.com/3536805/175227074-05cde6b7-0e57-40fb-9fb5-5426cd9741ca.png)|![3-yes-meds](https://user-images.githubusercontent.com/3536805/175227095-39db3679-9934-40dc-b40f-c3e3ebaa8574.png)


2. When at previous HIV positive patient is prescribed medication, the wording is different than what we have here in issue description.
![5-pmtct-no-meds-redo](https://user-images.githubusercontent.com/3536805/175228454-f291d4a0-d97f-4383-aff2-804fcde8a13d.png)

3. Discordant partner

Not surpressed viral load|Surpressed viral load
-|-
![6-discordant-partner-not-surpressed](https://user-images.githubusercontent.com/3536805/175229311-df43654d-c3b3-4fda-aaa5-357c7e5d4771.png)|![9-surpressed](https://user-images.githubusercontent.com/3536805/175229346-9381a8bd-b1b9-4871-8f68-405eb472ac88.png)
![7-warning](https://user-images.githubusercontent.com/3536805/175229377-0e4defec-f8f9-4de6-b9ab-6d44397ad877.png)|
![8-tdf-3tc](https://user-images.githubusercontent.com/3536805/175229432-25efeaf1-a951-45fc-b8f2-e928e1a39dab.png)|

**Comment by jeanette-pelizzon** [comment]
@Diama1 the issue that Zolt found should be fixed. It should read "Are you still taking ARV's" as this was what was requested by the medical team. I have taken a screenshot of the design for reference. 
<img width="227" alt="Screen Shot 2022-07-11 at 8 14 00 PM" src="https://user-images.githubusercontent.com/77505464/178386841-0acc6106-af99-4652-b5e6-9e23f16a9bb3.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Please note that display this for any HIV medication.
For example, we have here Doltegraviv:

![Selection_908](https://user-images.githubusercontent.com/17882245/178451264-099dac91-dadd-4b12-85bc-06e710dd3ac3.png)

I don't think that ARVs are sutabe here, so I made the message more general (same one we use for other diagnoses).

**Comment by jeanette-pelizzon** [comment]
@anvmn Wendy gave me the ARV text specifically so I would say we should keep it as ARV's. All those medicines in the HIV flow are types of ARV's.

**Comment by anvmn** [comment]
@jeanette-pelizzon Fine with me

@Diama1 please proceed with this change

**Comment by Diama1** [comment]
@jeanette-pelizzon on this task, I would like to ask for more clarification. On which condition will the ARV question be displayed?

**Comment by jeanette-pelizzon** [comment]
In treatment history for HIV patients. So if a patient was previously diagnosed with HIV in this pregnancy then this activity will appear during their next encounter. For the HIV Medication subactivity, the screen should look like what i posted [here](https://github.com/TIP-Global-Health/eheza-app/issues/249#issuecomment-1181205006). 

Let me know if this helps!

**Comment by anvmn** [comment]
@Diama1 what's the status please?
