### ISSUE TITLE
ANC Subs Visit - Labs - History Subactivity [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#258]
## Issue 

When we previously discussed labs, we created a way for the nurses to input results into E-Heza via case management. We are going to keep this. However, due to the fact that the labs affect the diagnosis, it's imperative that we have the results in E-Heza. When a patient comes back for a subsequent encounter, their healthcare worker will now be prompted to input any missing lab results into E-Heza before continuing on with the lab activity. This will help ensure that all the data for the patient is the most up-to-date. 

![Selection_874](https://user-images.githubusercontent.com/17882245/175919119-4fa36421-4bda-4a53-9864-81dd1d0ec756.png)

[Here](https://www.loom.com/share/34308f898c034492a336427a5162b780) is a quick video explaining how this flow will work. 

## Design Files: 

You can find the designs in Figma [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=560%3A31799).

Rough prototype [here](https://www.figma.com/proto/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=498%3A29651&scaling=scale-down&page-id=127%3A13021&starting-point-node-id=560%3A31799&show-proto-sidebar=1). 

## To Do: 
- Create history subactivity 
- Create logic to pull in missing test results 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> due to the fact that the labs affect the diagnosis, it's imperative that we have the results in E-Heza

Not only that lab results affect the diagnosis, they also determine next steps, like prescribing medication and referring to hospital.
Note that diagnosis determioation, and next steps are performed only when enering results from case management.

None of this will happen when update is performed from this activity (because we operate in context of current encounter, while lab result is from previous encounter).

//cc @adamhstewart

**Comment by jeanette-pelizzon** [comment]
@adamhstewart will have to help us problem solve this

**Comment by adamhstewart** [comment]
> because we operate in context of current encounter, while lab result is from previous encounter

This makes sense technically, but unfortunately not clinically. Even if a result is from a previous encounter, it should be able to influence a subsequent encounter. The most stark example would be HIV: If someone tested positive for HIV in an earlier encounter, that would always need to be considered in subsequent encounters.

I think what we need here is some mechanism to determine how to handle "old" lab results, I assume something like this:
- In some (possibly most) cases, we use the most recent result to determine next steps.
- In some cases, we don't consider the results because they are considered to old to be relevant. (we would nee dto check this clinically to know if there are such results).

**Comment by adamhstewart** [comment]
@anvmn There are two scenarios when filling in historic tests (for non rapid result tests):

1. The test has implications in the current encounter so we need to account for it in the NEXT STEPS of the FIRST PART of the current encounter (not case management) if the test result is non-normal:
 - Syphilis - record result, add positive diagnosis and refer to Hospital in next steps
 - Hep B - record result, and refer to hospital in next steps
 - Blood group - negative rhesus - record result, and refer to hospital in next steps
 - Random blood sugar - record result, add hypoglycemia diagnosis and refer to Hospital in next steps

2. The test result needs to be recorded but does not impact the first part of the current encounter
 - Hemoglobin - record results (this test is run every visit, so the NEW labs will determine next steps)
 - Urine dipstick - record results (this test is run every visit, so NEW labs will determine next steps)
 - HIV PCR - record results (this test is run every visit for an HIV positive patient, so NEW labs will determine next steps)

**Comment by anvmn** [comment]
@adamhstewart 

Will need to figure out a way of implemnting this.
Meanwhile, please note that currently we do not have logic for Blood group and Random blood sugar results.

They are at `THESE ARE ALL ON HOLD  - DONT WORRY ABOUT THEM FOR NOW `section of logics file.

**Comment by anvmn** [comment]
@adamhstewart 

For syphilis, we have a follow up question when result is positive:

![Selection_876](https://user-images.githubusercontent.com/17882245/175922376-7d507d53-664e-411d-b18e-5f4d9b25c58c.png)

It's used to come up with correct type of Syphilis diagnosis.
It will remain as is, right?

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### Found issues and questions:

1. Antenatal encounter node is not created, waiting for a fix.

![1-code-500](https://user-images.githubusercontent.com/3536805/177771685-162b8b8a-b513-4702-8858-c64454960254.png)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Blood group - Negative rhesus is not indicated in Hospital referral.
2. Hypoglycemia is not indicated on Progress report or on Hospital referral.

Progress report|Hospital referral
-|-
![8-progress-report](https://user-images.githubusercontent.com/3536805/177791572-699e518d-7452-48fe-a0f4-308884a903ec.png)|![6-referral](https://user-images.githubusercontent.com/3536805/177791616-436e5bcf-a3af-4a9b-b2af-7f8277ca430c.png)

3. Is the 'Have you updated all results that have been returned for this patient?' necessary? Can't we just check if the list is empty? 

### Checked and approved:

1. Laboratory page lists all the pending tests.

1|2
-|-
![3-laboratory](https://user-images.githubusercontent.com/3536805/177791972-4fa36b60-6af4-4d87-b353-675051f60873.png)|![4-subsequent](https://user-images.githubusercontent.com/3536805/177792060-0de039d2-c434-4e68-9332-8cbfc5057bb5.png)

2. Syphilis, Hepatitis is indicated on the Hospital referral page.
3. Anemia is indicated on the Progress report.

**Comment by jeanette-pelizzon** [comment]
1. @anvmn negative rhesus = hospital referral so should appear in that list. Can we update? 
2. Hypoglycemia? @balagan73 please elaborate what you mean by this.
3. This question was requested by the clinical team so we should keep it. Also, they may have results that have not yet been returned by the lab and will still remain on the list. Getting lab results back may take more time than expected. This allows them to move on in the encounter.

**Comment by jeanette-pelizzon** [comment]
If a patient is referred to the hospital it should be reflected on the progress report. It's not clear from these screenshots if that is happening. @balagan73 do you know if that's happening. I am having trouble with my testing environment at the moment and can't click through to check.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> negative rhesus = hospital referral so should appear in that list. Can we update?

For now we don't have any logic for handling rhesus result. It's under `THESE ARE ALL ON HOLD  - DONT WORRY ABOUT THEM FOR NOW` section of logics file.
So, there's no problem there.

> Hypoglycemia? @balagan73 please elaborate what you mean by this.

@balagan73 please answer

**Comment by balagan73** [comment]
@jeanette-pelizzon By hypoglycemia I meant diabetes. I will check again this and the progress report.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and question:

1. Gestational Diabetes is not displayed in progress reports. I will update #268 with this finding.

2. These findings were achieved via case management, Prenatal encounter CT (for example for Akuzwe Pamela on 15/07) is not getting created on nutrition environment. @anvmn When you have time, can you look into it?

### Checked and approved:

1. Hospital referral is indicated on the progress report.
![9-referral](https://user-images.githubusercontent.com/3536805/179240666-77f1b97c-e818-44ac-a34e-aebbdde073fa.png)

**Comment by jeanette-pelizzon** [comment]
1. Diabetes hasn't been developed yet. Logic and issues were finalized last week. These are in progress so that doesn't need to hold back this issue from moving forward to acceptance. 

2. @anvmn reassigning to you for QA follow up on this issues.

**Comment by anvmn** [comment]
@balagan73 please test Diabetes diagnoses:

![Selection_925](https://user-images.githubusercontent.com/17882245/179581106-a11bb2a9-4ea3-4fb3-8c62-af7da2720592.png)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. When pending test results are entered under Laboratory -> History, and patient <= 20 weeks EGA + urine dip (glucose) >=2+   blood sugar >7mmol/L, they should be diagnosed with Gestational diabetes, and not referred to hospital. If I understand correctly, hospital referral is only necessary if Random blood sugar test cannot be performed. Or maybe logic were copy pasted from Gestational diagnoses and not changed? In that case this should be fine, except the hospital referral, if that is not required.

Lab reports|Referral|Progress Report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/180029473-99a354f6-1fff-47a4-ae7a-b3c7aad09eec.png)|![14-referral](https://user-images.githubusercontent.com/3536805/180029602-8e337534-3d52-4e39-b423-9bdd1b35c5f7.png)|![13-report](https://user-images.githubusercontent.com/3536805/180029653-60189a36-42aa-4478-b35e-9c9a58b62fc2.png)

**Comment by anvmn** [comment]
@balagan73 

Not sure from where you stating the requirements, but for tests completed from labs history, the requiremenst are [here](https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1188108879).
The ones for Random blood sugar are marked in red.
In short, if performed test causes any kind of Diabetes diagnosis, at current encounter, patient should be referred to hospital.

//cc @jeanette-pelizzon

**Comment by balagan73** [comment]
@anvmn I was checking the Logic google sheet. Then, according to the comment of @adamhstewart patient should be sent to hospital after non-normal results. And I suppose, the diagnosis should be Diabetes and not Gestational Diabetes, but the google sheet states otherwise. //cc @jeanette-pelizzon 
![image](https://user-images.githubusercontent.com/3536805/180135247-c66bf2e0-5410-421d-aca6-c5edf6aa6ba4.png)

**Comment by anvmn** [comment]
@balagan73 You're looking at logic for issue #331.
This issue is #258, and it's requirements are [here](https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1188108879).

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. After pausing encounter, and coming back in a future date, under history tab I have entered all results as positive. I referred patient to hospital, but report says otherwise.

Pending lab results|Hospital referral|Report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/180717728-a056bedd-b50e-46f6-a77f-222d827633bd.png)|![image](https://user-images.githubusercontent.com/3536805/180717797-d4ae043e-e1de-4abb-a703-08089c357cdd.png)|![image](https://user-images.githubusercontent.com/3536805/180717920-29f32654-4104-4ddf-9492-e4ab0dd5dbee.png)

**Comment by anvmn** [comment]
> After pausing encounter, and coming back in a future date, under history tab I have entered all results as positive. I referred patient to hospital, but report says otherwise.

@balagan73 you did refer to hospital, but on 25/07, not on 12/07. So that part is correct.
However, we do not have requirements for progress report, when we send to hospital based on diagnosis from previous encounter.
@jeanette-pelizzon can you define this please?

**Comment by anvmn** [comment]
@balagan73 

With latest release we got Blood group - negative rhesus implemented,
Please test:
![Selection_965](https://user-images.githubusercontent.com/17882245/180855149-0adcf0e4-3afc-44b1-b25e-0d63a231ae9e.png)

**Comment by jeanette-pelizzon** [comment]
> However, we do not have requirements for progress report, when we send to hospital based on diagnosis from previous encounter. @jeanette-pelizzon can you define this please?

So what you are asking is, if a patient has labs drawn in a previous visit and then gets the results at a later date, those are not appearing on the progress report? And that you do not have the wording?

**Comment by balagan73** [comment]
@anvmn This case was tested here, all is fine: https://github.com/TIP-Global-Health/eheza-app/issues/342

### QA Review

### Found issues:

1. I have checked again the cases of diabetes and hepatitits. When I go back, and Update lab results of Blood sugar and Hepatitis so that the patient has these conditions, and then I refer them to hospital treatment, it is not stated on the Progress report. 

Referral|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/180948881-f89a7c06-6ba2-4934-8311-a14a037aabc4.png)|![image](https://user-images.githubusercontent.com/3536805/180948916-ac27348f-6eb2-4654-a43e-5e50c6878f5d.png)

### Question:

1. I did the negative rhesus with this patient. I have changed the date on the Prenatal encounter node to 2022-July-09 (test date was specified as 01 July, if I am correct). Then came back, and continued testing, and now the progress report shows a date for this test in 2021. @anvmn Should we be concerned about it?

First test|Second test
-|-
![image](https://user-images.githubusercontent.com/3536805/180949484-3b274793-029d-4c9d-8440-c61f9f9fc168.png)|![image](https://user-images.githubusercontent.com/3536805/180950403-bfd35794-223c-401b-a2c5-33a15f7efac1.png)

**Comment by anvmn** [comment]
@balagan73 @jeanette-pelizzon 

> I have checked again the cases of diabetes and hepatitits. When I go back, and Update lab results of Blood sugar and Hepatitis so that the patient has these conditions, and then I refer them to hospital treatment, it is not stated on the Progress report. 

This is know issue. @jeanette-pelizzon will define text for progress report and open separate issue for this.

> I did the negative rhesus with this patient. I have changed the date on the Prenatal encounter node to 2022-July-09 (test date was specified as 01 July, if I am correct). Then came back, and continued testing, and now the progress report shows a date for this test in 2021. @anvmn Should we be concerned about it?

No, all works as designed.
You entered an encounter that was already open on 26-08-2021, and performed negative rhesus there.
Here's the content that was created:

![Selection_971](https://user-images.githubusercontent.com/17882245/180969347-8bce672c-8f4d-4d81-9492-a21fd32243db.png)
![Selection_972](https://user-images.githubusercontent.com/17882245/180969376-e1f21685-fb0d-43d3-b105-3b1bfbc0741f.png)

@balagan73  To avoid confusion, I suggest that you create new patients and not use existing ones.

**Comment by jeanette-pelizzon** [comment]
> This is know issue. @jeanette-pelizzon will define text for progress report and open separate issue for this.

This issue exists [here](https://github.com/TIP-Global-Health/eheza-app/issues/342) and seems like it was already implemented. #342 

Let me know if you meant something else.
