### ISSUE TITLE
ANC Subs Visit - Labs - HIV PCR [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#260]
## Issue 

If a patient is pregnant and positive for HIV, we need to do a different type of HIV test on them to track their viral load- how many copies of the HIV virus are present in a certain amount of blood. This is important because the patient's viral load needs to be below a certain threshold by the time they give birth so they do not pass the virus along to their baby. We track the viral load through an HIV PCR test. FYI, this test can take up to a month for the lab results to be returned. 

One | Two | Three
--|--|-- 
<img width="327" alt="Screen Shot 2022-04-28 at 6 00 22 PM" src="https://user-images.githubusercontent.com/77505464/165854979-f80d8995-b581-4bde-80d4-b168c0df3b9e.png"> | <img width="332" alt="Screen Shot 2022-04-28 at 6 00 29 PM" src="https://user-images.githubusercontent.com/77505464/165854981-11d7910c-f652-426d-80a3-8714d443baf8.png"> | <img width="333" alt="Screen Shot 2022-04-28 at 6 00 45 PM" src="https://user-images.githubusercontent.com/77505464/165854983-d19e46aa-b33b-4d24-b36c-b5864c5986ad.png">

## Design Files 

Designs can be found in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) 

## To Do: 
- Create HIV PCR subactivity 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This requires new CT on backed. The effort is 4h.
Please update estimation.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Questions:

1. Date format is different from design dd/mm/yyyy vs dd-mm-yyyy. Is that a problem?
2. On the HIV PCR test results page the order of fields is different from design, but it is logical, since the HIV PCR Test Result field only displays when No is selected as an answer for the Are there <20 copies/mm3 question. I suppose this is OK.
![5-test-results](https://user-images.githubusercontent.com/3536805/175043088-83d1b3f0-b4a5-47a1-8295-0d12c8e24b6b.png)


### Checked and approved:

1. The screen displays and updates as on the design.

1|2|3|Pause encounter
-|-|-|-
![1-were-you-able](https://user-images.githubusercontent.com/3536805/175043327-f13e7f65-d3ff-416e-aa50-04f4ee7ffeec.png)|![2-test-date](https://user-images.githubusercontent.com/3536805/175043331-fefffafc-fa31-429a-bb92-035de8886832.png)|![3-test-date](https://user-images.githubusercontent.com/3536805/175043337-8f09cd7a-8cb8-4117-976a-fe95d1782db3.png)|![4-pause-encounter](https://user-images.githubusercontent.com/3536805/175043435-aa182c57-063d-4d41-95bb-76e852822c23.png)

**Comment by adamhstewart** [comment]
@balagan73 thanks - proper date is DD/MM/YYYY
