### ISSUE TITLE
ANC Subs Visit - Next Steps - Continued Illness [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#263]
## Issue 

Since this is a subsequent visit, a patient could have been diagnosed with an illness in their first visit (or a previous visit), been prescribed medication, and then still come up positive in a lab or hit the markers for the same illness in the subsequent visit. In this scenario, the next step will be to refer them to the hospital.  

(First Visit) Diagnoses with Illness ---> (Next Visit) Diagnosed with same illness = refer to hospital for further evaluation.

**EXCEPTIONS** to this rule are: 
- HIV (See #264 for more information)
- Hypertension (See #256 for more information)
- Diabetes (waiting on information from Valens)
- Anemia (See #265 for more information)
- Syphilis (See #266 for more information)

## Notes: 
- if a patient has been diagnoses 2x a sent to hospital, comes back and is diagnosed again we keep sending hospital. 

## To Do: 
- Create logic for next steps for second diagnosis of same illness

**Comment by anvmn** [comment]
@jeanette-pelizzon 

About `Since this is a subsequent visit, a patient could have been diagnosed with an illness in their first visit, been prescribed medication, and then still come up positive in a lab or hit the markers for the same illness in the subsequent visit`:

1. We need a list of all possible illnesses that meet this criteria. Note that there are illnesses that get diagnosed only on subsequent visit, and patient is prescribed medication. Should they be included as well?

2. The condition is that patients was diagnosed and got medications at previous visit? What do we do in case patient was diagnosed at first visit, got medication, then was diagnosed again on second visit, and was sent to hospital, and then was diagnosed again on third visit? Not sure this can happen though (need an answer to 1 before we can anlayse this).

**Comment by jeanette-pelizzon** [comment]
1. It is everything except those listed in the exceptions in the main issue 
2. If they are sent to the hospital and then come back and still have the issue I would assume we send them back to the hospital as it means the health center isn't equipped to handle the issue at that level. Tagging @leowea here in case we don't get to this in our meeting.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Another question - do we apply this logic only for illnesses that can be diagnosed at first nurse encouter, or, both first and subsequent encounters.

**Comment by jeanette-pelizzon** [comment]
@anvmn both first and subsequent.

**Comment by anvmn** [comment]
### Analysis:

Diagnoses that are treated with medication on initial nurse encounter:

- Hypertension
- Malaria
- Syphilis
- HIV
- Anemia 

Diagnoses that are treated with medication on subsequent nurse encounter:

- Lower Urinary Tract Infection
- Candidiasis
- Possible Gonorrhea
- Possible Trichomonas or Bacterial Vaginosis
- Heartburn

Exceptions listed above are:

- Hypertension
- Syphilis
- HIV
- Anemia 

Heartburn also does not require special handling, because it's initial requirements already have it included:

![Selection_758](https://user-images.githubusercontent.com/17882245/169690363-2749daa4-a239-4914-9cf1-2c3c316bf353.png)

That leaves us with:

- Malaria
- Lower Urinary Tract Infection
- Candidiasis
- Possible Gonorrhea
- Possible Trichomonas or Bacterial Vaginosis

@jeanette-pelizzon some of these diagnoses also trigger Health education.
Do we need health educarion here, in addition to referral to hospital?

**Comment by jeanette-pelizzon** [comment]
@anvmn no we do not need health education if we are referring them to the hospital

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When symptoms don't change, next steps includes referral to hospital.

Candidiasis:
![6-candidiasis-continued](https://user-images.githubusercontent.com/3536805/175555199-af16015d-9abe-4fd4-bdbd-64aaf53d15bb.png)
![7-hospital](https://user-images.githubusercontent.com/3536805/175555210-e25d81c6-cfad-4f88-8874-882c8134efd4.png)
