### ISSUE TITLE
ANC Progress Report - Logic [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#268]
## Issue

The app diagnosis needs to populate on the progress report in the appropriate section. The different diagnoses, the wording that should appear on the progress report, and the section that it should appear on can be found on [Logic Master](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=2144570215) on the ANC Progress Report tab. The wording follows a template of Diagnosis + Complications (if any) + Action Taken + Date.

From #257:
Wording in case of Outside care:
diagnosis + diagnosed by outside care + medication given (if any) + added to patient record on XX/XX/XXX
Example: Malaria diagnosed by outside care and treated with Coartem added to patient record on 10/07/2021
If other was selected I think we can just say in medical diagnosis
"Received a diagnosis from a different health care facility - please follow up with patient"

E-Heza will have to populate the medication prescribed, the complications (for Hep B and Syhilis), and the date the action was taken.

Here is an example of the progress report with sample diagnoses filled in:

<img width="302" alt="Screen Shot 2022-05-04 at 12 55 35 PM" src="https://user-images.githubusercontent.com/77505464/166737454-8835c8ae-50f7-48fa-bd3e-3b20a8e7ab76.png">

## Design Files
- you can find the design in Figma [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021)
## To Do: 
- Logic for the diagnoses to popular 
- Style per design

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
### QA Review (NOT FINISHED)

Note to self: Check **Malaria with anemia** without other complications, whether there is a duplicate diagnoses or not.

### Found issues and questions:

1. When patient has **Malaria with Severe Anemia**, and I refer them to the hospital, the progress report states otherwise.

Also, the wording of the treatment is grammatically incorrect. "Give" should be dropped.

Bug|Wording
-|-
![3-i-did-refer](https://user-images.githubusercontent.com/3536805/178022512-2be249ad-8632-4d0c-9a91-8a36e77af7ea.png)|![18-malaria-wording](https://user-images.githubusercontent.com/3536805/180150383-a97eda3a-5803-40da-adaa-ebccf24c1ff1.png)

2. In the case of **Candidiasis** treatment the dosage is indicated, but it is not indicated in the case of Gonorrhea.
![1-gonorrhea](https://user-images.githubusercontent.com/3536805/178765854-6fcb6ad4-b295-470e-b790-afef7322d1ec.png)

3. If **HIV and Malaria is diagnosed under Outside care**, wrong HIV medication displays.

Medication|Progress report
-|-
![3-outside-care-medication](https://user-images.githubusercontent.com/3536805/178924960-7c595cef-bc97-4850-9e3f-cabc8eb0996b.png)|![4-hiv-medication-wrong](https://user-images.githubusercontent.com/3536805/178924976-c6797ee4-f910-464a-bcc2-af60552066dd.png)

4. Patient with <= 20 weeks EGA + urine dip (glucose) >=2+ and blood sugar >=11 not indicated as **Gestational Diabetes** on the progress report.

Random blood glucose|Urine dipstick (short)
-|-
![10-random-blood-glucose](https://user-images.githubusercontent.com/3536805/179241010-8507cf2e-f64b-4ce1-b616-c31d82e4143d.png)|![12-urine-dipstick](https://user-images.githubusercontent.com/3536805/179241182-84c9bf67-c8ed-4c55-bf79-d640d63cdbd2.png)

Progress report:
![6-report](https://user-images.githubusercontent.com/3536805/179241686-9955a75b-045d-407f-a20f-9bf0ecc968cf.png)

5. **Diabetes** When <= 20 weeks EGA + urine dip (glucose) >=2+ and encounter was paused before Random blood glucose test.
Encounter could be ended without any next steps. Nothing displays on progress report.

6. Vomiting is mistyped as vomitting on the report:

![image](https://user-images.githubusercontent.com/3536805/180733288-c26dab2f-1fda-4c8d-a21d-b7cf61a0e546.png)

7. For Varicose veins and persistent varicose veins there is a missing dash (-) on the progress report page.

Varicose veins|persistent varicose veins
-|-
![25-varicose-veins](https://user-images.githubusercontent.com/3536805/180739141-96792a69-10e9-42b5-ab6d-54ad7cb37b78.png)|![26-persistent-varicose-veins](https://user-images.githubusercontent.com/3536805/180739854-85e8fbca-0bd3-407b-8a67-013d4c1c3c8e.png)

### Checked and approved:

1. **Gonorrhea, Candidiasis** diagnoses display under Medical diagnosis section.

2. **Outside care diagnoses** display properly under Medical and Obstretical diagnosis sections. (UI looks good, it is only messed up in the screenshot)
![5-other-medications-ok](https://user-images.githubusercontent.com/3536805/178927679-aa2b9cd4-83fe-4bdd-a23b-c9a0f453ffef.png)

3. **Sever Vomiting** 
 - Danger signs: sever vomiting: Patient is referred to hospital under obstetrical diagnosis on the progress report:
 
![image](https://user-images.githubusercontent.com/3536805/180001845-de3a3f3b-2033-4f44-a7f2-e1d482d56076.png)

4.  **Gestational diabetes** -referred to hospital is indicated on the report.
Patient >20 weeks EGA + fasting blood glucose of >7 mmol/L
 and  > 20 weeks EGA + urine dip (glucose) >=2+ 
also >20 weeks EGA + random blood glucose of >= 11.1 mmol/L

![8-gestational-diabetes](https://user-images.githubusercontent.com/3536805/180005311-2986ba4f-f75d-4ac1-a739-39c08a4c4259.png)

 5. **Diabetes** 
 Properly displayed on report for all 3 logic:
![12-diabetes](https://user-images.githubusercontent.com/3536805/180017190-96156933-f075-422b-a916-99401c49e6b2.png)

<= 20 weeks EGA + urine dip (glucose) >=2+  and Random blood glucose test is not run, hospital referral is indicated on report.
![13-referral-no-rbc-run](https://user-images.githubusercontent.com/3536805/180022065-cb709fd9-d9f3-418d-a0ab-91d9fe0476f2.png)

6. **Gestational Hypertension**

If blood pressure is >=140 to <=159 (systolic) and >=90 to <=99 (diastolic) (independent #s)
![image](https://user-images.githubusercontent.com/3536805/180049614-922d1852-763e-49f8-825f-541d281be47f.png)

7. If HIV RDT results are positive, and patient is administered medication, on the Progress report no treatment is recorded.

RDT|Medication|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/186618178-9be8ccfc-abc4-4ef9-836c-20ce22d78ac4.png)|![image](https://user-images.githubusercontent.com/3536805/186618248-7e790b52-ed94-481a-8731-e5381f7d1528.png)|![image](https://user-images.githubusercontent.com/3536805/186618363-f325b112-e83d-4df1-b5b5-74f71ad28324.png)

**Comment by adamhstewart** [comment]
@anvmn please check above issues.

**Comment by anvmn** [comment]
@adamhstewart 

> 1. When patient has Malaria with Severe Anemia, and I refer them to the hospital, the progress report states otherwise.

Fixed at #475.

> 2.I n the case of Candidiasis treatment the dosage is indicated, but it is not indicated in the case of Gonorrhea.

For Candidiasis, we have 2 options for same medication:

![Selection_1105](https://user-images.githubusercontent.com/17882245/190968140-5e896ce8-8a48-4700-983c-659ee91be820.png)

This is why we state which one is given - 200mg at screenshot.

> 3. If HIV and Malaria is diagnosed under Outside care, wrong HIV medication displays.

Fixed at #475.

> 4. Patient with <= 20 weeks EGA + urine dip (glucose) >=2+ and blood sugar >=11 not indicated as Gestational Diabetes on the progress report.

Blood sugar ranges were changed - 126/200. Please retest.

> 5. Diabetes When <= 20 weeks EGA + urine dip (glucose) >=2+ and encounter was paused before Random blood glucose test. Encounter could be ended without any next steps. Nothing displays on progress report.

To determine Diabetes diagnosis, Random blood glucose test must be run.
Recent developments eliminated the option of ending encunter unless all mandatory activities are completed, so 
there should not be an option to skip Random blood glucose.
Please retest.

> 6. Vomiting is mistyped as vomitting on the report:

Fixed at #475.


> 7. For Varicose veins and persistent varicose veins there is a missing dash (-) on the progress report page.

Fixed at #475.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Patient has malaria with severe anemia, is referred to the hospital, but report doesn't indicate referral. Actually this is how it is prescribed in the Logic master document, so I guess not mentioning hospital referral here is OK.

Referral|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/192469473-510c3b8a-ae17-49ef-9f80-f56d132e73fa.png)|![image](https://user-images.githubusercontent.com/3536805/192469491-d1abc0c6-41ab-4489-92c9-6d68aba346b2.png)

2. When HIV is diagnosed in Outside care, and None of these is selected as treatment, 'treated with None of these' displays on the progress report.

Outside care|HIV medication|Progress report 
-|-|-
![image](https://user-images.githubusercontent.com/3536805/192473601-400a8a35-f117-494e-93e5-e910d19a6cbd.png)|![image](https://user-images.githubusercontent.com/3536805/192473346-6ce11228-bdf2-44d7-8eef-407f06d5dd44.png)|![image](https://user-images.githubusercontent.com/3536805/192473268-5e4ef878-65af-43ed-89eb-ea40f4adec00.png)

3. In mobile view when Malaria is diagnosed under Outside care, no treatment administered displays correctly on the report, but the comma is broken into a new line.
![image](https://user-images.githubusercontent.com/3536805/192474574-cebfc266-0165-4cf5-b51d-3ae47d3b42ca.png)

### Checked and approved:

1. Typos are fixed (vomitting and the missing dash).
![image](https://user-images.githubusercontent.com/3536805/192464678-1b03b9ab-4330-4e81-a830-4005a8a44728.png)
![image](https://user-images.githubusercontent.com/3536805/192475805-940ebe33-43fd-4a81-b121-5e970b424eec.png)

2. With Diabetes when <= 20 weeks EGA + urine dip (glucose) >=2+ the Random Blood glucose test was not skipped, next steps displayed correctly. Diabetes is displayed on the progress report.

![image](https://user-images.githubusercontent.com/3536805/192470264-99ee3cd4-471b-4389-9af1-b2fbb4f8ebdc.png)

3. Gestational diabetes (after meal 200 mg/dl) is correctly diagnosed.

![image](https://user-images.githubusercontent.com/3536805/192478476-abb4ce82-d9a6-4054-9c76-dd8a0cb56522.png)
