### ISSUE TITLE
ANC Subs Visit - Maternal Mental Health [11h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#290]
## Issue 
The Maternal Mental Health activity consists of a series of questions - a survey - that the nurse will ask the patient. Each answer is given a score. The activity needs to tally up the score to create a diagnosis at the end. There are ten screens with one question each and a list of answers. This was an intentional design and clinical decision to make it easier for the user to navigate and to reduce user error. I have the answers with checkboxes but we can change that to whatever is easiest to do the tally. 

Video overview [here.](https://www.loom.com/share/1560e4c298254690a2b46714d4b5add9)

## Design: 
Can be found in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) 

Screen One | Screen Two | Screen Three | Screen Four | Screen Five 
--|--|--|--|--
![EPDS 1](https://user-images.githubusercontent.com/77505464/172662181-2fb8209b-aad5-4d2d-bbb4-27eade02a8bd.jpg) | ![EPDS 2](https://user-images.githubusercontent.com/77505464/172662183-787b2bee-5a62-4bc1-9c4a-db84aa470ecb.jpg) | ![EPDS 3](https://user-images.githubusercontent.com/77505464/172662185-fca1008f-af02-4982-a624-4bb140dffcb2.jpg) | ![EPDS 4](https://user-images.githubusercontent.com/77505464/172662187-0392d8c3-9b81-4184-8419-10e1cb47d39c.jpg) | ![EPDS 5](https://user-images.githubusercontent.com/77505464/172662188-b890946a-4616-4bec-a83a-f2c95569a28d.jpg)

Screen Six | Screen Seven | Screen Eight | Screen Nine | Screen Ten | Screen Eleven
--|--|--|--|--|--
![EPDS 6](https://user-images.githubusercontent.com/77505464/172662331-b1646bfe-6487-4eb4-ba61-8ccaf62f3ea9.jpg) | ![EPDS 7](https://user-images.githubusercontent.com/77505464/172662332-aa447449-8e76-46d9-9153-a2e87f76f2f6.jpg) | ![EPDS 8](https://user-images.githubusercontent.com/77505464/172662334-f9904039-824d-4afa-a712-916a875ebf6b.jpg) | ![EPDS 9](https://user-images.githubusercontent.com/77505464/172662336-609ec48f-f4de-42f3-8bd4-857eb7f44e4d.jpg) | ![EPDS 10](https://user-images.githubusercontent.com/77505464/172662337-19d94cf4-d951-4751-be4a-dc0aa8174712.jpg) | ![EPDS 11](https://user-images.githubusercontent.com/77505464/172662339-3ceaf7c5-efb2-427f-85a0-fe7fd3246a83.jpg)

## Related Issues: 
- #289 
- #291

## To Do: 
- Style Screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 
There's no option of going back in screens to edit answers. Is this intentional?

**Comment by jeanette-pelizzon** [comment]
@anvmn 

(1) Updated with a back button in case a patient changes their answer after the nurse moves on. 
(2) added in an 11th screen to verify whether the health center has a mental health specialist as we spoke about yesterday.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> added in an 11th screen to verify whether the health center has a mental health specialist as we spoke about yesterday

Please provide a design how this for should look when there's mental health specialist at HC:

![Selection_804](https://user-images.githubusercontent.com/17882245/172684146-3e851a5d-3ee3-4533-a8a8-95aa89cab534.png)

**Comment by jeanette-pelizzon** [comment]
@anvm yes updated the relevant issue (#291)

**Comment by jeanette-pelizzon** [comment]
@anvmn updated relevant issues (#291)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/


### QA Review

### Found issues and questions:

1. There is no back button on the very first screen. Is this a problem?
2. The label of the Back button is Back instead of Go back, and its background is not red. Is this a problem?
3. The background of the Save button is darker than on the design. Is this a problem?

### Checked and approved:

1. Questions display as on the design.

Question1|Question2|Question3|Question4|Question5
-|-|-|-|-
![4-question1](https://user-images.githubusercontent.com/3536805/174787830-76cec929-03df-4d5e-a037-d307cba62e8f.png)|![5-question2](https://user-images.githubusercontent.com/3536805/174787848-b3dc4b9a-adc0-457f-91c1-010bf2bbaaaa.png)|![6-question3](https://user-images.githubusercontent.com/3536805/174787852-81bbe95d-088d-4bdd-a87e-b9fd23210ab5.png)|![7-question4](https://user-images.githubusercontent.com/3536805/174787856-5000c6ab-c922-4d07-8390-a326015880d3.png)|![8-question5](https://user-images.githubusercontent.com/3536805/174787862-b6207335-67ba-4b5e-a922-980d69f44b38.png)


Question6|Question7|Question8|Question9|Question10|Question11
-|-|-|-|-|-
![9-question6](https://user-images.githubusercontent.com/3536805/174788632-5e6f3ef4-215e-4c82-ab86-67af9e0813ff.png)|![10-question7](https://user-images.githubusercontent.com/3536805/174788657-bb77e870-06c4-4b5e-b71c-4528ffeb6fc7.png)|![11-question8](https://user-images.githubusercontent.com/3536805/174788659-12096c40-d2b4-4563-baab-0b538e8127cb.png)|![12-question9](https://user-images.githubusercontent.com/3536805/174788664-e8993f1e-8b45-45fe-9f67-69ec611e27ab.png)|![13-question10](https://user-images.githubusercontent.com/3536805/174788667-0699b294-13c9-47e0-bf0c-466b0f932273.png)|![14-question11](https://user-images.githubusercontent.com/3536805/174788670-fb93e332-5210-40cb-9d43-dc4235fd91fd.png)

 2. Referral form displays under Next steps.
 
 Specialist available|Specialist not available
 -|-
![18-referral](https://user-images.githubusercontent.com/3536805/174795054-d1f483ce-bef2-4020-9d6a-23376c5b865d.png)|![19-referral-hospital](https://user-images.githubusercontent.com/3536805/174795071-f6d5be24-bf5e-4a26-874a-6d0433fb70e5.png)

**Comment by adamhstewart** [comment]
@jeanette-pelizzon can you confirm that @balagan73 's questions are not problematic in terms of the design intent?

**Comment by anvmn** [comment]
> There is no back button on the very first screen. Is this a problem?

No, becuase there's nowhere to go back.

> The label of the Back button is Back instead of Go back, and its background is not red. Is this a problem?

We try to maintain common UI and functionality, and there're other places at APP where we have this, so we show it here in common matter. If this needs changing, we better make this change throughout whole APP.
@jeanette-pelizzon  to decide. 

> The background of the Save button is darker than on the design. Is this a problem?

As far as I undertand, this issue does not exist on tablet, so, not relevant.

**Comment by jeanette-pelizzon** [comment]
@balagan73 @anvm I think it is fine for now. I think we can address a number of UI issues at a later date - including this.
