### ISSUE TITLE
ANC Subsequent - Provide textual context for referral to hospital [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#305]
## Issue

In cases where there is high risk the message does not provide context (on the page) for why the referral is happening:

![image](https://user-images.githubusercontent.com/688507/175829752-9b565708-2af6-4f10-95ce-ed566ba32d3d.png)

## Task
- Add a sentence before the current introduction sentence that repeats the patients diagnosis: "The patient has been diagnosed with: [condition], [condition]. This patient is a high risk case...."

**Comment by anvmn** [comment]
@adamhstewart 

I'll need detailed definitions for text that need to be displayed.
There are at least 30 cases where we send patient to hospital. and it's not only due to certain diagnosis.
For example, patient can be sent to hospital due to adverse event to medication.
Another possibility is hypertension treatment logic, where we increase doses untill we decide to send to HC.
Also, at we have some new cases at https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1166608871.

While this may not be common, we may have many reasons for hospitalization, so do we just separate with `,`?
Asking because I see different requirements for the popup at https://github.com/TIP-Global-Health/eheza-app/issues/306.

//cc @jeanette-pelizzon

**Comment by adamhstewart** [comment]
@anvmn We would use the same list here - in this case it would be a comma series. We are less concerned about visual clarity as it's not a popup, and in most cases they will have just seen it.

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1177606947 Here I have already found some cases that should have been mentioned on the hospital referral page. Now I have tested only for them, and the hospital referral page doesn't display.

Blood sugar|Long dip
-|-
![1-blood-sugar](https://user-images.githubusercontent.com/3536805/177943362-5385c32d-0b3b-4491-93b0-2381757059af.png)|![3-glucose](https://user-images.githubusercontent.com/3536805/177943370-ed6dd5d8-90be-4b0a-ac42-2814ca08ebcc.png)

Logic:
![2-logic](https://user-images.githubusercontent.com/3536805/177943412-588b2394-6596-4f46-9dd4-98c7c2250438.png)

2. There are duplications on the popup... Ah, ok, it is going to be a bullet list according to https://github.com/TIP-Global-Health/eheza-app/issues/306
![4-duplications](https://user-images.githubusercontent.com/3536805/177943848-4daf2b45-f2b7-485d-9871-18d8a2621210.png)


### Checked and approved:

1. Those conditions that trigger hospital referral, properly display on the hospital referral form.
![5-referral](https://user-images.githubusercontent.com/3536805/177943273-45163bd3-e878-4e79-8100-d2f70c44e26f.png)

**Comment by jeanette-pelizzon** [comment]
1. Gestational Diabetes has not been implemented on E-Heza yet. We are still working through the logic with the clinical team. The issue for gestational diabetes will hopefully be created early next week once I finalize all the logic and design with the clinical team.  Unless there is a different issue here @balagan73 I will move to Acceptance. Please let me know 

2. Awesome.

**Comment by jeanette-pelizzon** [comment]
Early Acceptance Testing note: users have requested that we signify what diagnoses is high-risk. So we should not only list them at the top but also include them in the sentence below. 

Here is an example: 
<img width="345" alt="Screen Shot 2022-07-12 at 5 18 11 PM" src="https://user-images.githubusercontent.com/77505464/178605171-8a677056-7f9a-4845-a41d-ddde80999380.png">

// @Diama1

**Comment by anvmn** [comment]
@jeanette-pelizzon 

When it comes to referring to hospital, there are emergency and non ugent diagnoses.
Since emergency diagnoses are triggered right away, either all diagnoses on referral form are emergency, or all are non urgent. For example, at your screenshot, both are non urgent.

So far, the idea was that if patient is referred to hospital, it's a high risk case.
For emergency diagnoses we also had red popup.

If you think it's necessary, please define what 'emergency referral form' should say, and what should 'non urgent  referral form' say.

**Comment by jeanette-pelizzon** [comment]
Update: we do not need to update the second line of text. Having the diagnoses in the first line is enough.
