### ISSUE TITLE
ANC Update - Symptom Review [10h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#325]
## Issue

We added the Symptom Review activity while we were working on the Subsequent ANC encounters so originally we just had this activity appearing in subsequent encounters. As was pointed out in QA of other issues, it was strange that we only had it in subsequent encounters. After talking to the clinical team, they would like the Symptom Review activity - and all logic associated with it - to appear in the first encounter as well. This was users can diagnose those diseases/issues early on in a pregnancy and prevent further issues later on. 

## To Do 
- add Symptom Review Activity to first encounter in ANC 
- add in Symptom review logic to first encounter in ANC

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. As this is displayed at the first encounter, maybe it is worth rephrasing the text, because the patient not necessarily has any symptoms. Or maybe we can just drop the first sentence.

![2-symptom-review-page](https://user-images.githubusercontent.com/3536805/179971434-603b0ab2-6070-4121-8718-4881cf809fa7.png)

### Checked and approved:

1. Symptom review displays at first encounter:


![1-symptom-review](https://user-images.githubusercontent.com/3536805/179971431-e725fb14-3939-4f75-87dd-4a8d0f81e17a.png)

**Comment by jeanette-pelizzon** [comment]
That first line should not appear on this screen. That first line only appears on the conditional screens based on the symptoms they selected. 

This is the design: 

<img width="316" alt="Screen Shot 2022-07-21 at 7 09 41 AM" src="https://user-images.githubusercontent.com/77505464/180234529-5c87512f-db6d-465c-9584-2df164d24380.png">

@Diama1 can you fix?

**Comment by Diama1** [comment]
> @Diama1 can you fix?

@jeanette-pelizzon sure

**Comment by Diama1** [comment]
> That first line should not appear on this screen. That first line only appears on the conditional screens based on the symptoms they selected.
> 
> This is the design:
> 
> <img alt="Screen Shot 2022-07-21 at 7 09 41 AM" width="316" src="https://user-images.githubusercontent.com/77505464/180234529-5c87512f-db6d-465c-9584-2df164d24380.png">
> 
> @Diama1 can you fix?

@jeanette-pelizzon Are we dropping the first text for both encounter or just for the first encounter?

**Comment by jeanette-pelizzon** [comment]
@Diama1 for all encounters. That text doesn't make sense there at all.
