### ISSUE TITLE
ANC - Diabetes - Already Diagnosed [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#338]
## Issue 

Currently, if a patient has been diagnosed with diabetes in a previous ANC visit during this pregnancy and they continue to have high glucose numbers, we continue to refer them to the hospital. 

This doesn't need to happen. After speaking with Wendy, if a patient has been diagnosed with diabetes we should continue to run the random blood sugar test at each visit and record those values in the progress report. There will be no next steps because the patient is already in a program. 

All E-Heza needs to do is prompt the nurse to run the lab and then record the numbers in the patient's chart. 

## To Do: 
- Update the logic

**Comment by anvmn** [comment]
@balagan73 

We had these requirments as part of #331 and #332, but I don't see QA report  addressed it.
Please verify one Nutrotion env.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. When at first encounter I do not enter all data for the patient, just go for labs, do a test, and then pause the encounter, then after finishing the test (random blood sugar test), and coming back for subsequent visits, it is not possible to enter patient data, eg. pregnancy data, photo. I think this is the precondition of validation not working on Obstetrical exam, because we have no EGA data.

Available activities (plus next steps under To Do)

![image](https://user-images.githubusercontent.com/3536805/180216870-b7af0883-14fc-4ab0-ae17-7b2c0cb6e90a.png)

**Comment by balagan73** [comment]
I am stuck with this, cannot end encounter after entering lab results with Case management. I have tried repairing my device, it did not help. After repairing the device, not all patient have images in the directory. @anvmn Can you help me with this?

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Now I could end the encounter when doing Case management.
![image](https://user-images.githubusercontent.com/3536805/180711678-9ea9410e-38ba-43d8-a061-ab30e5432320.png)


2. Patient is referred to hospital at first encounter, when blood glucose level is high according to logic.
Then at subsequent encounter no more hospital referral is happening.

More high blood glucose lab results|One referral
-|-
![image](https://user-images.githubusercontent.com/3536805/180711616-eeb8f24f-24a4-4d95-9e1f-935c407f2fb6.png)|![image](https://user-images.githubusercontent.com/3536805/180711649-bebe5558-475d-4f28-a418-95574e7fd4fa.png)
