### ISSUE TITLE
ANC Subs - Outside Care - Logic Update [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#356]
## Issue 

In #355 we added the yes/no question "Do you have follow-up care planned with a specialist?" Now we need to update the logic associated with this question. 

**If yes**, cancel next steps for diagnosis that were selected on this screen.

_More info_: we finish the subactivity screens but any next steps regarding continued care for that diagnosis will be cancelled. We don't need to worry about them. We just want to document that they were given medication and what kind in their progress report and let the specialist deal with any next steps.

**If no,** then we follow the normal logic for everything.

## To Do: 

- Update Logic accordingly

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

> If yes, cancel next steps for diagnosis that were selected on this screen.

There are no next steps for any of selected diagnoses. 
We collected this info only for progress report. See https://github.com/TIP-Global-Health/eheza-app/issues/257#issue-1217863014.

Moreover, if we needed next steps, that would completly break our current architecture, 
because there are diagnoses that can be determined only on 'labs results' phase of encounter.
For example, we do not support Syplhilis treatment on initial phase.
Outside care on the other hand is at initial phase, which means Syphis treatment will have to be supported at both phases.

Also, next steps for some diagnoses determined not only by diagnosis itself, but also by additional questions we ask. HIV for example. So, even if we really wanted to, we could not determine HIV treatment.

Other issues we'd need to deal with if we needed this supported:
- What steps should there be if patient was given medication for diagnosis. For example, Syphilis diagnoses and medication is given (and selected on second screen of outside care activity). 
- What should happen to labs that we offer at the encounter. For example, if patient was diagnosed with Syphilis, should we run Syphilis test at current encounter?
- If patient was diagnosed with something that requires referral to hospital, do we need to refer? Maybe the diagnose was made at the hospital, so why referring again?

**Comment by jeanette-pelizzon** [comment]
@adamhstewart is in talks with Wendy about keeping/cancelling the whole outside care activity. I'll let him take this one over.

**Comment by jeanette-pelizzon** [comment]
Per our conversation on 8/1, we are putting this issue on hold. 

// @anvmn @adamhstewart
