### ISSUE TITLE
NCD - Medical History - Social History [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#402]
## Issue 

Social history is important for the medical team to know as these factors can greatly affect a patient's health. I have made notes on the screenshots as to what questions are conditional. Hopefully, this helps clarify with fewer screenshots. There is not logic associated with these answers at this time but that may change in the future. 

<img width="290" alt="Screen Shot 2022-08-11 at 9 15 30 AM" src="https://user-images.githubusercontent.com/77505464/184180924-20f0c581-99c0-4eb2-8a69-d638228f7236.png">

## To Do 
- Style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Results

### Found issues and questions:

1. Page is made according to the design, but when I fill out the form, I am uncertain what the units of measurements are.
In the case of alcohol how many bottles? Liters? In the case of cigarettes I suppose it is cigarettes and not packs, otherwise it would be indicated like that. I am not a professional, but as a layman when we speak about how much people smoke, it is generally referred to in packs. So just to avoid confusion maybe we could still write how many cigarettes per week?
![image](https://user-images.githubusercontent.com/3536805/193521183-174ef230-4a47-4553-8e5a-039a6b47371d.png)

### Checked and approved:

1. Except from the above question the page corresponds to the design.

**Comment by jeanette-pelizzon** [comment]
I think this is okay as it was the wording provided by the clinical team. We have the indicator of time (week) so I would assume that means how many individual drinks per week and how many individual cigarettes. (if I am remembering correctly you can buy just individual cigarettes there) 

I will follow up with them though and ask. Thanks for pointing out.
