### ISSUE TITLE
NCD - Logic - Hypertension Stage Two with Complications [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#407]
## Issue 
When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue.

Hypertension is one of the major issues tackled by the NCD encounter. There are several stages of Hypertension. For the purposes of these issues, I have broken them into one stage type per issue.

**[The logic for NCD's can be found here.]**(https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)

**Stage Two Hypertension with renal complications OR diabetes** will result in medication distribution and a referral to the hospital. 

The goal of giving a patient this medication is to get their numbers to systolic of <140 and diastolic of <90. If a patient has a systolic <100 we can bump them down a stage level. 

Renal Complications | Diabetes | Referral Screen
--|--|--
<img width="265" alt="Screen Shot 2022-08-11 at 2 40 50 PM" src="https://user-images.githubusercontent.com/77505464/184247231-47571a66-5c70-4f0f-9a94-9ab4ecfdd6f5.png"> | <img width="266" alt="Screen Shot 2022-08-11 at 2 40 12 PM" src="https://user-images.githubusercontent.com/77505464/184247182-7eaecbe9-e4dc-4f71-b8e3-7f722b34a78c.png"> | <img width="241" alt="Screen Shot 2022-08-11 at 9 51 37 AM" src="https://user-images.githubusercontent.com/77505464/184190994-d7f65b83-74c1-4c0c-a83d-bceb39741618.png">

## To Do 
- Implement Logic 
- Style Screens per Design

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. When urine dip-stick has +1 protein or Creatinine is above 1.4, the patient is referred to hospital, but no diagnosis and medication distribution occurs.

BP|Protein|Next steps
-|-|-
![image](https://user-images.githubusercontent.com/3536805/193593947-b6cf688d-c6c5-44c2-b385-e94113dc4377.png)|![image](https://user-images.githubusercontent.com/3536805/193594065-70e3c6f7-5eea-467d-8e17-37837a4b63a7.png)|![image](https://user-images.githubusercontent.com/3536805/193594110-5f47827f-96f7-440e-a7df-dc9578cdf690.png)

2. I have just taken a screenshot of the Stage 2 hypertension diagnoses, then I went back to Laboratory to make sure I have selected Creatinine tests (Creatinine tests were indeed selected), and when I came back to the Completed tab, the diagnosis disappeared. This is correct, because we have to wait for test results, but temporarily displaying diagnosis is confusing.
Screenshot of the disappearing diagnosis:
![image](https://user-images.githubusercontent.com/3536805/193595910-65eebc50-a8ea-434b-b4b5-ec7f83fc8baa.png)

**Comment by jeanette-pelizzon** [comment]
1. diagnosis should be happening. can you please investigate @anvmn 
2. Also very weird instance @anvmn
