### ISSUE TITLE
[META] NCD - Progress Report

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#448]
## Issue 
As it is a new encounter type, we also need to create a progress report for NCD patients. I put together a quick [video here](https://www.loom.com/share/e7d067216a014d9699fda52cfde6d24e) to walkthrough the various sections and what needs to be in them. 

**Progress Report** 
![NCD Progress Report](https://user-images.githubusercontent.com/77505464/190278610-ceaa7062-8d76-407e-a813-27b2bf00e800.jpg)

**Lab Results** | **Liver Function** | **Creatinine** 
--|--|--
![Lab Result Pop Out](https://user-images.githubusercontent.com/77505464/187319286-d5a02e59-71c7-4626-8ef5-6cbd761b1487.jpg) | ![Liver Function](https://user-images.githubusercontent.com/77505464/187319295-87b86fa7-9554-44f8-a9d0-ee40ffa2a66c.jpg) | <img width="431" alt="Screen Shot 2022-08-30 at 11 33 00 AM" src="https://user-images.githubusercontent.com/77505464/187515966-d2343973-9e94-41f4-921d-232edaaf44e3.png">

Note: in the video, I mentioned not having nitrogen ranges. Ignore that. The screenshots for the design are correct. I did not realize that one of the tests included nitrogen and it wasn't it's own test. 

## Related Issues:
- #466 
- #467 
- #468 
- #469 
- #470 
- #471

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Please break down this META issue into detailed issues for each pane.
Since we have mutiple identical encounters, Risk factors and Medical diagnosis panes need to 
reflect it, by adding dates.
Also, the charts will have to define the number of ecounters we want to present.
Do we make it 7 for BP and 13 for Glucose, as charts show now?
