### ISSUE TITLE
ANC Progress Report - Medical/Obstetric Diagnosis Formatting [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#478]
## Issues
<img width="1242" alt="Screen Shot 2022-09-20 at 1 48 34 PM" src="https://user-images.githubusercontent.com/688507/191340638-4dd26a51-63b6-4305-908b-f7410c84f5bd.png">
Patient = Dukuze Soline - Rukura Health Center (Nutrition environment)

1. Formatting should be consistent with the smaller font and the dash list separator (also review spacing so it looks like one list)
2. Diagnoses should have a date they were recorded
3. Diagnosis should not appear twice, if they were diagnosed twice there should be two dates in order of earliest to latest.
4. (not indicated) Assuming that "underweight" were diagnosed at different times, if not the more severe case should be shown. Otherwise there should be a diagnosis date for clarity.

## Tasks
- Fix the format changes indicated above

**Comment by anvmn** [comment]
@adamhstewart 

For the context, what we have on the bottom of Medical and Obstetrical panes are not diagnoses.
These are alerts, that we developed for initial ANC, which was only for CHW.
Never got an answer on what to do with them when nurse views the report, so they remained there.
This was mentioned at https://github.com/TIP-Global-Health/eheza-app/issues/353#issuecomment-1250215829 already, and now I think maybe we should be hiding them for nurses?
Some of these alerts are duplicated of proper diagnoses. For example, `Pregnancy induced hypertension`, as @balagan73 found at point 1 of https://github.com/TIP-Global-Health/eheza-app/issues/340#issuecomment-1253308729 and 'High risk of Preeclampsia' @balagan73 found at https://github.com/TIP-Global-Health/eheza-app/issues/353#issuecomment-1207722371.

> Formatting should be consistent with the smaller font and the dash list separator  (also review spacing so it looks like one list)

Actually, at CSS, there's not dash separator on list items. We have that dash, because it's a `<p>` whith text prefixed with dash.

![Selection_1125](https://user-images.githubusercontent.com/17882245/191516168-eb77db29-26d8-468b-9b48-68296b673a78.png)

So, seems to me that fix should be to implement this as real list `ul` with `li` items.
The font will be larger, similar to font at other types of progress reports.

> Diagnoses should have a date they were recorded

These are alerts, and they are meant for current encounter.
Some will show only if certain result happened twice, so adding a date to this is complex.

> Diagnosis should not appear twice, if they were diagnosed twice there should be two dates in order of earliest to latest.

This is a bug, which is fixed at #480.

**Comment by adamhstewart** [comment]
> This was mentioned at https://github.com/TIP-Global-Health/eheza-app/issues/353#issuecomment-1250215829 already, and now I think maybe we should be hiding them for nurses?
Some of these alerts are duplicated of proper diagnoses.

I see, yes they should be hidden then.

> So, seems to me that fix should be to implement this as real list ul with li items.

Sure - as long as there is consistency.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA
