### ISSUE TITLE
ANC @ Health Center - Labs Logic [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#51]
## Issue

When a patient goes to her ANC visit labs are done at every visit. However, the labs vary depending on the EGA. 

Lab | First Visit | Every Subsequent Visit | 34 Weeks | 38 Weeks
--|--|--|--|--
HIV RDT|Yes | | |Yes
Syphilis|Yes | | |Yes
Hepatitis B|Yes ||Yes|
Malaria RDT|Yes | Yes |Yes|Yes
Hemoglobin|Yes | Yes |Yes|Yes
Blood Group + RH|Yes ||||
Random Blood Sugar|Yes|||
Urine Dipstick|Yes | Yes |Yes|Yes

### Note  

- If a lab test is not completed, it will be pushed to the next visit. 
  - Not completed, if answer is `No` for `Were you able to perform this test?`
- If it is a test completed at every visit (ex: malaria), and it is not able to be completed it will not be pushed as it is already appearing in every visit. 
- Labs not done will continue to appear until they are completed up until birth. 

## To Do

- Implement logic for displaying Labs sub-activities
- Implement logic for deferring Labs sub-activities for subsequent encounters

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Questions/Found Issues:
1. HIV RDT and Syphilis tests were completed at the 38 weeks visit. Why they appear in sub-sequent visit (38 weeks and 1 day)?

Lab | 38 Weeks visit | Subsequent Visit |
-- | -- |-- |
HIV RDT | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145802692-6c4d3c76-4cb5-40e9-833e-9ec612412491.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145802800-c5f4d72f-b772-47cd-b826-9f19aee87095.png">
Syphilis | ![Test2_-_Google_Drive](https://user-images.githubusercontent.com/35059802/145802656-dcd454f2-a762-43c6-ba8d-a8b4a365f622.png)|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145802861-4985e2f9-597e-4bd7-b876-27ebda117432.png">

2. Hepatitis B test should appear at the first and 34 Weeks visits only if it was completed at the first visit. But this test appears at all next visits after the 34 Weeks visit (where the test was completed). Example:

- All tests are completed:

 First Visit | Subsequent Visit 1 | 34 Weeks visit | Subsequent Visit 2 | 38 Weeks visit | Subsequent Visit 3 |
-- | -- |-- | -- |-- |--|
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806195-a1665c1d-86ef-4f8f-a76f-a863ba35c931.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806218-91a1708b-b513-4766-aa65-451dd1989e4a.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806260-86251aaa-b7cb-4d32-876c-cb4e6811ccd0.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806357-332c5077-7a76-48b8-994b-f72e427000d9.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806381-c7f9d0d2-c0fa-4e82-a4e0-9536c7e80b0d.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806429-0e357640-e5f7-4c6e-8049-6b571bd9e7c5.png">

3. All tests that should be pushed to the next visit, if they were not completed in the current visit, are not pushed (HIV RDT, Syphilis, Hepatitis B, Blood Group + RH, Random Blood Sugar)

Example:

- First Visit:
 
HIV RDT | Syphilis | Hepatitis B | Blood Group + RH | Random Blood Sugar | 
---|---|---|---|---
<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145849002-fbd7abf6-6250-46cf-9af0-5787c99f518d.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145849059-71f06a00-e65b-40c9-a43c-e44783a47be1.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145849240-3a3df56c-e147-4de8-9256-7b0bccbacc34.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145849319-ca757b23-dd51-4b39-adb7-e8395359861a.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145849430-76493ee2-b887-4b00-8cc5-8ab0e63baf26.png">

- Next visits:

| Subsequent Visit 1 | 34 Weeks visit ( Hepatitis B appears not because it was pushed to the next visit, but because it should appear at this visit anyway) |
---|---
<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850065-60f65cd5-67ed-499b-afbb-1868bebdc3e6.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850129-885def43-7a08-4f97-b87d-2f94ef9d3ab4.png">


### Checked and Approved:
1. All 8 Lab sub-activities appear at the first visit, regardless of what stage of pregnancy the visit was. Examples:

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145720422-4fb47f9f-0af8-4573-bad3-4eacb3e07f48.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145720442-a1400c79-fc17-41c7-b6e4-c827163771dc.png">
---|---

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145720477-e027e5af-8be6-41b9-b9a6-f63dc15b2f0e.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145720496-e4ed954b-7b6a-47e8-84e5-502b46b553d5.png">
---|---

2. Malaria RDT, Hemoglobin, Urine Dipstick tests appear at each visit, whether they were completed or not during the previous visit. Examples:

- All tests are completed:

Lab | First Visit | Subsequent Visit 1 | 34 Weeks visit | Subsequent Visit 2 | 38 Weeks visit | Subsequent Visit 3 |
-- | -- |-- | -- |-- |--|--
Malaria RDT | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799181-e21b143c-4a51-4251-aa29-23ad1bf0b8c4.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799446-3cb1a730-5a9a-4817-881f-0453cf68730a.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799611-9382d58c-cdd4-4d0f-8772-152ccf8996ee.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799806-84a9e143-71a1-4203-ba79-30fc503f6316.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145800024-a1656239-21cc-4a52-b80f-3b6724793f6a.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145803052-e8494bd3-f66d-4a11-8cf5-cee42873521d.png">
Hemoglobin | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799282-fea19b2f-5d91-4a7b-a235-005028bc43df.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799526-58944c8e-05a6-4a44-b962-b45278b2b0d1.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799704-7da0840a-7523-4bc2-bb13-43f5ecdc5fba.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799930-c9ca5591-898b-4dcf-b089-8c5de3bb9e0e.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145800105-6ad6a4bf-df5d-4db0-b349-530722153691.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145803142-ab80d117-de9c-45c7-a8d3-bc872301edf3.png">
Urine Dipstick | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799335-1cea920f-7172-49e7-a089-88e847628800.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799492-6dde4811-56d1-4ded-8646-1a8180201483.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799667-bd0a8f02-c7d6-48df-b5f2-2813499dbd5b.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145799865-6057538f-eda6-4a63-959d-8950cd866f33.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145800059-71c43ecb-230a-425a-8a62-64eaa0b4ed22.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145803222-ac23ae3d-29d5-4ab7-8bdc-489bf9b332bc.png">


- All tests are not completed:

Lab | First Visit | Subsequent Visit 1 | 34 Weeks visit | 
-- | -- |-- | -- |
Malaria RDT | <img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850380-780a4bb7-3ce6-4707-a9fe-39df88831c8e.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850606-55b331f4-d129-4cbd-b0ab-1afbaf3e7fb7.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850826-66458b77-83c9-42dd-9031-98acb1b5cea7.png">
Hemoglobin | <img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850521-a2872b40-5caa-43b3-8ae4-12f7897e4f4f.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850756-83c5b134-0bf0-40de-b2df-e96f985fb172.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145851035-422bf598-cc4f-46ba-b104-549c2a015c77.png">
Urine Dipstick | <img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850464-f3e36511-1ac4-4332-b3fc-453af8b57cf0.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850676-bf16d52d-c881-48f8-ac30-0014271b44a3.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145850988-ebfca6a8-c452-4d49-999d-9cccea52caa0.png">


2. HIV RDT and Syphilis tests should appear at the first and 38 Weeks visits only if they were completed at the first visit. Examples:

Lab | First Visit | Subsequent Visit 1 | 34 Weeks visit | Subsequent Visit 2 | 38 Weeks visit
-- | -- |-- | -- |-- |--
HIV RDT | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801299-99429516-f169-449f-b7a8-356b1ce977cb.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801488-26929895-70c5-4df0-8544-aa585377e827.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801595-7522d3a9-6060-413b-b4a4-16ffcbd1e06c.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801690-6639af41-5b9d-43de-895b-eba68ac8887a.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801802-2fdebd60-8a54-4b2c-a1f4-c7cdc6a0f850.png">
Syphilis | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801382-bf2fdf0c-0d1b-42bf-9589-cbaee8ffcd09.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801502-23ec27fe-2618-4aca-ac4b-99c32622284b.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801620-e5bece91-416b-483c-9be9-bdd2a04204ae.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801720-7c133b74-8774-4021-8b49-e6db74c56274.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145801859-4f2e2af4-9640-4e52-917b-0bd5636c25e7.png">

3. Blood Group + RH and Random Blood Sugar tests should appear at the first visit only if they were completed at this visit. Examples:

Lab | First Visit | Subsequent Visit 1 | 34 Weeks visit | Subsequent Visit 2 | 38 Weeks visit | Subsequent Visit 3 |
-- | -- |-- | -- |-- |--|--
Blood Group + RH | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145803983-a944def9-0837-497d-9a18-2cd613ef5dcc.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804170-537f77cc-be6a-4770-8ba0-cac3d6b1428e.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804257-cf70084f-d93f-4b4f-98ab-bd8e4b6516ee.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804337-fddf393a-f2ff-461c-a139-d35360e31734.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804430-905ddbac-93cf-41b3-abda-621d3d74e2da.png"><img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804519-a35088cd-2e65-4a03-b5f0-2ddcc14f6555.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804598-c15c6477-89bf-4b82-b981-66e797b55781.png"><img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804943-c4e25dc8-54f2-4cfc-a39f-15a1ebebce77.png">
Random Blood Sugar | <img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804038-ad5b969f-7f4f-43c4-870a-ccd9174689e9.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804200-4a0940fc-9c9c-4a7c-9f71-f6a93641d36d.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804294-afbc421f-80a1-4ff9-84ec-d74aab7684cc.png">|<img width="362" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804362-a77e3fa8-72e5-450a-b25f-c3445060473f.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804452-9bf8bec8-c79a-4c16-aa04-7fa1d9c5a1dc.png"><img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804540-a33fd5e7-0911-4e3c-bdff-0256fa670ea1.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804614-b00579cc-83de-4bc1-acc6-55b6629e40a4.png"><img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145804650-38b04609-9804-4170-bf26-b37b6313754a.png">

4. Hepatitis B test should appear at the first and 34 Weeks visits only if it was completed at the first visit. 

Lab | First Visit | Subsequent Visit 1 | 34 Weeks visit | 
-- | -- |-- |--
Hepatitis B | <img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806195-a1665c1d-86ef-4f8f-a76f-a863ba35c931.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806218-91a1708b-b513-4766-aa65-451dd1989e4a.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145806260-86251aaa-b7cb-4d32-876c-cb4e6811ccd0.png">

**Comment by isapisa** [comment]
@anvmn can you please check all the 3 issues found by Ludmila?

**Comment by anvmn** [comment]
@LudmilaGoichman
Please retest all 3 points on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Checked and Approved:
1. If HIV RDT and Syphilis tests were completed at the 38 weeks visit, they don't appear in sub-sequent visit:

Lab | 38 Weeks visit | Subsequent Visit |
-- | -- |-- |
HIV RDT | <img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147941681-76b499f7-c024-405e-b5ef-66e3fc814732.png">|<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147941792-83d07e38-575c-4963-897f-1865513a078a.png">
Syphilis | <img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147941742-5aa8d065-0d43-4003-9376-16cd6d879a86.png">|<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147941792-83d07e38-575c-4963-897f-1865513a078a.png">


2. Hepatitis B test doesn't appear at all next visits after the 34 Weeks visit if the test was completed at the 34 weeks visit. Example:


| 34 Weeks visit | Subsequent Visit 2 | 38 Weeks visit | Subsequent Visit 3 |
-- | -- |-- | -- |
<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147942294-30b816a8-5d99-42e9-945f-1f61dbf8268f.png">|<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147942211-5b9f5672-5fa3-4190-b040-e3a2ab20dbff.png">|<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147942152-989750a6-66c6-4882-b687-9a0934e40f83.png">|<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/147942051-f7846792-38fc-4a03-baac-3d163e496264.png">

3. All tests that should be pushed to the next visit, if they were not completed in the current visit, are pushed (HIV RDT, Syphilis, Hepatitis B, Blood Group + RH, Random Blood Sugar)

Example1:

- First Visit:
 
HIV RDT | Syphilis | Hepatitis B | Blood Group + RH | Random Blood Sugar | 
---|---|---|---|---
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147942450-2f169ec5-4f3d-415a-a082-13f2da1bdc84.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147942484-d682da8c-4aa8-4f95-97ae-b8d5b3065676.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147942514-0d12a35e-3d64-4f9f-ac21-225d22aa254b.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147942564-9335f20d-f9f4-4d0c-91cf-df55d36e0142.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147942618-e45e1b9d-3fa4-41f2-8050-d41179973d4f.png">

- Next visits:

| Subsequent Visit 1 (all tests weren't performed)| 34 Weeks visit (all tests, except Hepatitis B, weren't performed) | Subsequent Visit 2 (all tests, except Hepatitis B that doesn't appear, weren't performed) | 38 Weeks visit (only Blood Group and Random Blood Sugar tests weren't performed) | Subsequent Visit 3 |
-- | -- | -- | -- |--
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943150-8c845708-0bec-43c2-8556-a00062e40827.png"><img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943205-fc6f8af2-9123-4fbc-9e14-e0aa9188e7fc.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943277-aca0d317-4b10-4491-8586-64edee0ddc22.png"><img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943385-a01e7785-0e86-4971-a0aa-b6179f6581a2.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943510-b93accd5-6cc0-4376-ba70-fcf062ff83c6.png"><img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943545-0b323295-d001-4a1c-b72e-4ebbcf64e7f4.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943674-52449677-f411-47cc-94c7-b1ff5f76ec5d.png"><img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147943746-5373b84c-2ea0-4a0c-a41e-f1fba01c0e92.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147944080-0b834381-f358-47b4-9510-94ace14a63ea.png">

Example 2( for Hepatitis B from 34 weeks visit and for HIV RDT + Syphilis from 38 weeks visit):

all test were not performed in all visits:

Test | First Visit | 34 Weeks visit | Subsequent Visit 2 | 38 Weeks visit | Subsequent Visit 3 |
-- | -- | -- | -- |--|--|
Hepatitis B | <img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957521-6806ffa0-cdfa-4f69-a74f-8348e876f055.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957557-f16da2fb-90e6-48f3-8136-2a6bcdda5bd4.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957611-3bdf0373-2420-44a6-865d-f2fdb0233dc4.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957628-63fb75ae-3c91-49ea-8405-c1931cf7f571.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147958041-207a6b47-e7cd-4b98-b906-bea747842ca0.png">
HIV RDT | | | | <img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957820-0c10e1f4-8f1c-48ec-aded-595568d8ee12.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957931-9ad9fcdb-1416-4854-9c08-fe0342e0dbe6.png">
Syphilis | | | | <img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957788-88eef224-9654-4aa6-998e-8cfe575ecd0f.png"> |<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/147957863-7a9465dd-8e24-42d0-bfeb-dc70026136b6.png">
