### ISSUE TITLE
NCDA Scorecard - Data Pulling - ANC + Newborn [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#517]
**Regular Prenatal and Postpartum Checkups**

_What module is the data being pulled from:_  Questionnaire

_Green Checkmark on scorecard:_ if answered yes on the questionnaire

_Red X on scorecard_: if answered no on the questionnaire

_Dash on scorecard:_ After pregnancy is complete, these will all turn to dash marks.

**Iron During Pregnancy**

_What module is the data being pulled from:_  Questionnaire

_Green Checkmark on scorecard:_ if answered yes on the questionnaire

_Red X on scorecard_: if answered no on the questionnaire

_Dash on scorecard:_ After pregnancy is complete, these will all turn to dash marks.

**Given insecticide-treated bednet during pregnancy**

_Green Checkmark on scorecard:_ if answered yes on the questionnaire

_Red X on scorecard_: if answered no on the questionnaire

_Dash on scorecard:_ After pregnancy is complete, these will all turn to dash marks.

_Note: this appears in the infrastructure environment and wash section of the scorecard but including in this issue as it relates to pregnancy_

<img width="802" alt="Screen Shot 2022-10-24 at 10 26 01 AM" src="https://user-images.githubusercontent.com/77505464/197849423-be704799-4492-482c-a680-5d30d5a1875b.png">

**Related Issues/Docs:**
- Meta Issue: #515
- [ Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab.
- [Figma](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by anvmn** [comment]
@adamhstewart  @jeanette-pelizzon 

Since this data needs to be pulled from ANC module, we need to connect between the child, and a pregnancy child mother was tracking on Eheza.
For this follwing conditions must be met:

1. Child participates at group encounter with mother (to establish child-mother relationship).
2. Mother was tracking the pregnancy at Eheza.
3. At ANC, postpartum encounter was performed, and child was created at it's Newborn activity.

I see a problem here, because condition 2 will be met pretty rare, because most of the patients are being imported. Condition 3 is even more rare.

An effort of impementing above logic is not trivial. I estimate it wil take 8h to implement this issue with current requirements, and not sure it's worth it, given the fact that we will have very little data.
It may be a better idea to add these 2 questions to Questionnaire, so we can have the info for all patients.

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

There's another question that is taken from ANC at [Infrastructure + Environment + Wash](https://github.com/TIP-Global-Health/eheza-app/issues/521):
![Selection_1252](https://user-images.githubusercontent.com/17882245/200184201-f844d100-7558-4ee5-9242-e551594727e2.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn updated main issue to address the changes we made to the questionnaire.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. V characters display instead of checkmarks.
![image](https://user-images.githubusercontent.com/3536805/207015923-72208a93-1a94-40c1-80f4-99099198fa1b.png)

2. On the scorecard only slots during pregnancy are marked. I suppose this is correct for 'Iron during pregnancy', but is it for 'Postpartum checkups' too?
![image](https://user-images.githubusercontent.com/3536805/207017617-da0b97c1-9c78-47d3-9880-2e0aad7ace11.png)

3. The behavior of 'After pregnancy is complete, these will all turn to dash marks' is different in the case of _'Insecticide treated bed nets'_ .  Is this correct? See image below.

### Checked and approved:

1. Insecticide treated bed nets display with an X if answered No to the question.
![image](https://user-images.githubusercontent.com/3536805/207017109-2eb66e6c-02f4-4985-ade6-ed6f40524217.png)

**Comment by jeanette-pelizzon** [comment]
1. They should be checkmarks 
2.  Yes we are only tracking the pregnancy data for pregnancy months 1-9 
3. No, they should get a check mark if they were given the questionnaire and answered yes to that questions in months 1-9 of pregnancy. They should get a red mark if they answered no. A dash if the questionnaire was not completed that month. This needs to be fixed. 

@adamhstewart @anvmn

**Comment by anvmn** [comment]
>  1. They should be checkmarks

There's no place to fit icons in a row with 35 cells.
All other markers we got is charcters, so I figured we could use green V.
@jeanette-pelizzon tell me if this is critical.

> 3. No, they should get a check mark if they were given the questionnaire ...

Discuissing insecticide-treated bednet during pregnancy here.
However, this is non issue, because per master document, ANC + Newborn pane got only 2 entries, and insecticide-treated bednet during pregnancy is not one of it:

![Selection_1552](https://user-images.githubusercontent.com/17882245/215712945-f711dab3-4c75-436c-a135-07518cc07df5.png)

The one @balagan73 was pointing to is at Infrastructure + Environment + Wash pane and implemented per requirements at #521.
