### ISSUE TITLE
NCD -  Subsequent Visit - Labs Frequency  [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#535]
## Update 

As we create Subsequent Visits for NCD, we need to update which labs appear and at what time. All labs will continue to appear at the initial visit, and unless indicated below, they will not occur again.  

- Random Blood Sugar - Every Visit
- Creatinine - Initial Visit + Yearly 
- Urine Dip Stick - Initial Visit + Yearly 
- HIV - Initial Visit 
- Pregnancy Test - Initial Visit 
- Lipid Panel - Initial Visit + Yearly 
- Liver Function - Initial Visit + Yearly 
- HBA1c - Initial Visit + Every 6 Months

**Comment by anvmn** [comment]
@jeanette-pelizzon 

What about Liver Functions and HBA1C?

**Comment by jeanette-pelizzon** [comment]
@anvmn Both are run at the initial visit and then after that - HBA1c is every 6 months and liver is run yearly. I updated the main issue.

**Comment by jeanette-pelizzon** [comment]
I am pretty sure liver is run every time

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env.

### Found Issues/Questions:
1. A pregnancy test should not appear for men and for girls under the age of 13 (the issue has already been mentioned)

<img width="355" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788992-00ba5dc9-01f4-4a42-af65-fae19fb68b03.png">

2. The main entry of the test shows that the results are abnormal, although the subtests themselves have not yet been executed. Why isn't it labeled "pending results" like the other tests (without subtests) and subtests?

<img width="368" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210790476-05b5e9bd-dac2-4c24-819f-83a38a0ef276.png">|<img width="368" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210790641-948bae34-df83-4f46-8998-84852486b543.png">
---|---

3. Random Blood Sugar test. I entered a wrong value in the first test (value 5 can only be in mmol/L units). Therefore, the value didn't appear in the graph, and this looks like the first test wasn't performed. Is it okay, or should the wrong value be set to "0" in the graph?

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792961-085f7a06-833d-42a8-8887-d0dd21aa1567.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792668-315fc158-1339-4a33-be89-1453fa3ff336.png">
---|---

### Checked and Approved:
1. All the tests (8) that should appear in the initial encounter appear:

Random Blood Sugar - Every Visit
Creatinine - Initial Visit + Yearly
Urine Dip Stick - Initial Visit + Yearly
HIV - Initial Visit
Pregnancy Test - Initial Visit
Lipid Panel - Initial Visit + Yearly
Liver Function - Initial Visit + Yearly
HBA1c - Initial Visit + Every 6 Months

<img width="355" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788899-9c8879c6-2e63-4d73-bc05-e3dd1e5c38ed.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210789448-0eda9bb9-7b73-4c23-9bff-984d6943adbd.png">
---|---

Tests that were not performed at the initial encounter:

HIV - Initial Visit
Pregnancy Test - Initial Visit

<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210789231-b03bf9f3-47aa-48fc-b11f-4f710c2123c4.png">|<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210789329-0cc44a5f-27c7-4669-ad49-c5fc6c46ab15.png">
---|---

2. Tests one month after the initial encounter:

Random Blood Sugar - Every Visit
HIV - Initial Visit // appears because wasn't performed in the initial encounter 
Pregnancy Test - Initial Visit // appears because wasn't performed in the initial encounter 

<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210791337-ad081295-a1de-40a0-ac3c-6e3ef8002c71.png">

3. Tests six months after the initial encounter:

Random Blood Sugar - Every Visit
HBA1c - Initial Visit + Every 6 Months

<img width="357" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210791654-162d3464-08e1-492c-ba12-3e48a81fe2c5.png">

4. Tests (6) year after the initial encounter:

Random Blood Sugar - Every Visit
Creatinine - Initial Visit + Yearly
Urine Dip Stick - Initial Visit + Yearly
Lipid Panel - Initial Visit + Yearly
Liver Function - Initial Visit + Yearly
HBA1c - Initial Visit + Every 6 Months

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792332-0fccec6a-d23e-4b70-87a1-e79ed0e92b6a.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792394-38885f00-030d-42a8-a76d-1afc6654df0a.png">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 2. The main entry of the test shows that the results are abnormal, although the subtests themselves have not yet been executed. Why isn't it labeled "pending results" like the other tests (without subtests) and subtests?

When there are 2 levels, the requirements were to show either Normal, or Abnormal.
Exact definition was - if all sub entries  are normal, then show Normal. Abnormal otherwise.

3. Random Blood Sugar test. I entered a wrong value in the first test (value 5 can only be in mmol/L units). Therefore, the value didn't appear in the graph, and this looks like the first test wasn't performed. Is it okay, or should the wrong value be set to "0" in the graph?

Lowest value we allow in this chart is 40. Any result bellow that is filtered out.
In your example, if the result is 5, setting it to 40 would be wrong.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- nutrition env

### Question:
1. A pregnancy test appears at subsequent encounters for girls 13 years old who were 12 years old at the first encounter. Was it such a requirement? I'm just not sure, if this test is run on the initial encounter and doesn't appear on all subsequent encounters, then why, if the test isn't relevant on the initial encounter, run it on a subsequent encounter (sometimes a year later)?
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192847-9bad9fb0-e4bf-416d-ba34-b76fd1592d9c.png">


### Checked and Approved:
1. A pregnancy test doesn't appear for men at initial and subsequent encounters

First encounter | subsequent encounter 1 | subsequent encounter 2 |
---|---|---
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192364-0cedffca-3414-4541-b3c2-10e02bc2fda4.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192376-d08612d8-cf02-4f27-8b27-a065fc0592f6.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192662-eb885b38-94a0-4897-a2a3-43ec47b2da75.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192668-f15aefcd-bf47-487c-94dc-a7bbbdeb6f12.png"><img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192981-53f6bae3-1a89-4c87-9bb9-5d5ec6b10c8e.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192726-93a1b976-33a2-47ed-958c-51467909a5ec.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192734-f729869a-9ba2-4d23-a1c6-aadddc896407.png"><img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211193063-f40253fc-90d0-40b6-a947-2d2b959e0b13.png">


2. A pregnancy test doesn't appear for girls under the age of 13 years at initial and subsequent encounters

First encounter at age 12 years | subsequent encounter at age 12 years 3 month |
---|---
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192420-4d0dfa40-3cb4-4645-a94a-b2a2c3a47da8.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192439-b5fdd4d0-9886-41f9-95a2-3ac785dc34cc.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192824-c480488f-81b1-40a1-a65c-f52eae89d343.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192918-26dee3c3-4c8e-471f-86cc-1d2754577d6a.png"><img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211193044-1c565f52-7b2b-4516-ae26-d8b0d947e81b.png">


3. A pregnancy test appears at subsequent encounters for girls 13 years old who were 12 years old at the first encounter 

First encounter at age 12 years | subsequent encounter at age 13 years  |
---|---
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192420-4d0dfa40-3cb4-4645-a94a-b2a2c3a47da8.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192439-b5fdd4d0-9886-41f9-95a2-3ac785dc34cc.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211192775-377d9412-74c0-4c02-a063-f6f308d2f1f4.png"><img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211193026-b0478641-ead1-49bc-b252-2ad3942ba1ad.png">

**Comment by anvmn** [comment]
@LudmilaGoichman 

This is an edge case, but per current requirements, test should be run once, and it does.
Passing to client acceptance.
