### ISSUE TITLE
NCDA + Newborn Exam - Birthweight [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#543]
## Issue 
We are adding the question "What was the child's birthweight" to both the NCDA questionnaire and the newborn exam. The user will input the birthweight in grams. If the weight is below 2500 grams the child is underweight. There should be the RED callout next to it. 

In NCDA, this means that the scorecard will update accordingly.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> There should be the RED callout next to it.

Can you provide a design for this please?

**Comment by jeanette-pelizzon** [comment]
> Can you provide a design for this please?

see #544 for questionnaire design. 
See #542 for newborn exam design.

**Comment by anvmn** [comment]
@jeanette-pelizzon I don't see the RED callout anywhere

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> I don't see the RED callout anywhere

Ok, found it:
![Selection_1290](https://user-images.githubusercontent.com/17882245/202290404-3889d5f1-8a44-4bd6-b928-e751c0d0f8dd.png)

That's similar to what we got for MUAC input.

**Comment by LudmilaGoichman** [comment]
@anvmn Which env to check? on nutrition?

**Comment by anvmn** [comment]
@LudmilaGoichman yes

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env.

### Questions:
1. I think it should be "child's" instead of "childs":

<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209933379-d3eb566d-f306-4def-ae92-c1db5195dba2.png">

2. Should there be some kind of restriction on the values of this field?
   a.  for numbers after the decimal point? 
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209934053-b87c04fd-fced-445b-9183-a0a44f6aee73.png">

   b. for max and min values?
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209934283-680830c0-87a7-4014-ad7d-157576e75f30.png">

3. I think it correct that the question doesn't appear in an acute illness encounter and a home CHW visit (individual nutrition encounter), but I want to be sure
from https://github.com/TIP-Global-Health/eheza-app/issues/515:

> The scorecard will be updated everytime a child is seen during a Standard Pediatric Visit, FBF (Nutrition), or an acute illness visit. 

4. The birthweight question appears in Individual child nutrition encounter for CHW, but doesn't appear in Home visit under Nutrition encounter for CHW. This is correct, right?
<img width="424" alt="E-Heza_System" src="https://user-images.githubusercontent.com/35059802/209979904-b4190e03-a9c1-4d8b-bacf-23ab5f5a4a5e.png">

6. The answer appears in the child's scorecard as "yes" or "no" after "Born Underweight". Should the weight be given in grams in addition?
<img width="351" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209980375-204978e4-47a2-429a-9168-e2243bf43cab.png">

### Checked and Approved:
1. The birthweight question appears only for children under 2 years of age
2. The birthweight question appears only once at the first encounter of the relevant type
3. The birthweight question appears either in the Birth History activity (in Newborn exam) or in the ECD Scorecard activity in all other encounter of the relevant type
4. The answer to the birthweight question should be entered in grams
<img width="257" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209977983-00a8573b-5c0e-4e01-a6a8-fe09b02265ae.png">

5. The birthweight question appears in the following encounters:
   a. nurse: 

| Pediatric encounter | FBF group nutrition encounter| Individual nutrition encounter |
---|---|---
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209936205-ab7f9800-c9c1-427a-b66d-403c32f7685d.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209936398-48c630f6-06b3-49f9-b836-b3d55cd97c3c.png">| <img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209937136-1cececd1-ac87-478f-8c5a-ee88f7d265b6.png">

   b. CHW:

Newborn exam | Individual child nutrition encounter |
---|---
<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209937405-8e7f187b-1dc8-4b24-9d0d-c68c02d5cb4c.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209937480-05a949fa-ad0a-4096-9dfa-e87ded99daa8.png">

8. If the weight is below 2500 grams the child is underweight and the RED callout is displayed next to the answer.
<img width="333" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209978337-c01119ea-c600-4d2b-8768-8895ecece614.png">

9. The child's scorecard is updated according to the answer:

underweight | normal weight |
---|---
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209979202-7fbc0577-5504-4097-813c-7c396eb60bf4.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/209979281-e00ba7c7-0130-4c3c-9fef-a31d8c6ab2b1.png">

**Comment by anvmn** [comment]
@LudmilaGoichman 

Point 1 is fixed at #581.
Point 2 - no min, max or any other restriction, as at all inputs we got.
Pints 3, 4 - no NCDA at AI / Home Visit encounters.
Point 6 - no need to add the value.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon

- nutrition env

### Checked and Approved:
1. "childs" has been changed to "child's"

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211206175-4367ae39-d2fc-4a2d-9690-eb039fa02c33.png">
