### ISSUE TITLE
NCD - Labs- HBA1C [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#546]
## Issue 

HBA1C is run every 6 months to check certain blood sugar levels in a patient. In Rwanda, this test is only run at the hospital, however, we need the results in E-Heza so that the health center can have a more complete picture of an NCD patient's health. 

(1) The lab populates every 6 months in E-Heza. It will stay there until results are put in. This lab only appears in the first part of an encounter. 

(2) The lab works differently than others as it will only appear in the first part of the encounter and results will be put in there directly. 

(3) If the answer to the first question is yes -> patient will be referred to the hospital for testing. The lab should continue to reappear until the results are input. 

<img width="291" alt="Screen Shot 2022-11-14 at 4 02 06 PM" src="https://user-images.githubusercontent.com/77505464/201793499-cec3b017-1446-4c69-bd7e-5efeb783552a.png">

(4) If the answer to the first question is no -> then the user will be prompted to input what date the test was run and then they should input the result. 

<img width="302" alt="Screen Shot 2022-11-16 at 8 45 54 AM" src="https://user-images.githubusercontent.com/77505464/202241820-4c0d3083-73b4-48ed-a6d4-63187306019e.png">

(5) These results should appear in the lab section of the progress report.  Normal ranges are anything BELOW 6%.

**Comment by jeanette-pelizzon** [comment]
Updated Today -> main issue with normal ranges and updated design.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

It seems to me that question 'Is the patient due for testing'  makes nurse job hard and the process more time consuming. This is a question we should know answer to already (speically, when you say 'The lab populates every 6 months in E-Heza').

This is how I'd make the flow:

If we have at least one date of testing + result, we know if patient needs to test again or not.
 - if not (6 months did not pass), we don't show the lab at all
 - otherwise, we ask for date + result of most recent test:
    - record date + result
    - if that test was more than 6 months ago,  refer to the hospital for testing

If we don't have first date + result, we need to ask if patient has made the test and got a result.
 - positive answer  - ask for date of that test
    - ask for result and record date + result
    - if that test was more than 6 months ago,  refer to the hospital for testing

 - negative answer - refer to the hospital for testing

Does that make sence?

**Comment by jeanette-pelizzon** [comment]
@anvmn yes, I like your flow. I think we had this question because at first it wasn't clear to the team when testing happened but now we have answers so this makes sense! Thank you!

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env.

### Found Issues/Questions:
1. NCD. The HBA1C activity (in the Laboratory) cannot be saved if the answer to the first question is "yes" and the selected date is yesterday

> Fixed at https://github.com/TIP-Global-Health/eheza-app/pull/581.

2. This test doesn't exist in Antenatal Care encounter, but the screens shown in the description are from Antenatal Care. Should a test be added to this encounter?
3. Should "the" be before "hospital" like in the examples?

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210605127-220af7f8-ae00-4dfa-a79b-7163bc89d172.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210605618-ac810af1-34b4-419e-90db-7ba21da85eee.png">
---|---

4. Closest test record date is yesterday's date (not today).Is it because tests are only done in hospitals and it can't be done today before visiting a nurse?

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210611387-7d835b9f-5eb4-42e2-94e2-31f42d276c65.png">

### Checked and Approved:
1. The flow is correct. Examples:

- First encounters:

> If we don't have first date + result, we need to ask if patient has made the test and got a result.
> positive answer - ask for date of that test
> ask for result and record date + result

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210604282-92bed56f-786f-4e05-8461-9fd5eb175f92.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210604407-ceeebc8f-96b0-43f8-9232-a5b6fd4e9808.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210604488-a0952d94-8b9f-434d-8cb2-c6d01d1a7315.png">
---|---|---

> if that test was more than 6 months ago, refer to the hospital for testing

more than 6 months ago | less than 6 months ago|
---|---
<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210606495-4bd7fc0c-f49f-4523-bb6a-e7cc5aa4ea74.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210606567-c4e82d66-0b5a-4b52-97d7-098c0dbbcbd5.png">

> negative answer - refer to the hospital for testing

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210604857-d1e0b2c5-e0fc-490a-9960-96a63f18769e.png">

- Subsequent encounters:
> If we have at least one date of testing + result, we know if patient needs to test again or not.
> if not (6 months did not pass), we don't show the lab at all

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210608223-c86e098d-15a5-43f5-b605-26015d7d1b68.png">

> otherwise, we ask for date + result of most recent test:
> record date + result

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210607519-ac45d812-0fcb-4b42-a2b0-7975d4aab956.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210607607-a483bd7c-8195-4658-bc87-04f0045cb2ef.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210607720-ac7802b2-c934-4967-88ed-d6450e9f5691.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210607991-c94d982f-02b3-4d56-8c34-f6663b5beeb9.png">
---|---|---|---

> if that test was more than 6 months ago, refer to the hospital for testing

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210608473-716145f5-4b12-492c-b1c8-0ab87369d397.png">

2. Abnormal values (>= 6%) are marked in red in the lab results, while normal values are black.

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210610054-ac3740cf-c4a6-4b78-bb9c-004d8d6c4dbe.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210609620-0dab3627-1065-4247-934f-9ae2dd532870.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210609374-ac62ef04-f8c7-461b-b701-cf5e2af07ad6.png">|<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210609505-45859caf-c155-4c35-9bc6-222b08f3e20c.png">
---|---|---|---

3. Values are displayed on the graph

<img width="361" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210609863-e2ea984a-dfc2-42f9-801e-9efbe2c709a3.png">

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 2. This test doesn't exist in Antenatal Care encounter, but the screens shown in the description are from Antenatal Care. Should a test be added to this encounter?

The design is not accurate here. The test appears only at NCD encounter.

> 3. Should "the" be before "hospital" like in the examples?

No, "the" is not needed here.

> 4. Closest test record date is yesterday's date (not today).Is it because tests are only done in hospitals and it can't be done today before visiting a nurse?

Well, patient will need to perform test at hospital, get a result and get to health center on same day.
This is very much not likely to happen. So, no option to set today's date.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon

- Nutrition env.

### Checked and Approved:

1. NCD. The HBA1C activity (in the Laboratory) can be saved if the answer to the first question is "yes" and the selected date is yesterday

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211198670-d560598c-488a-487f-9b21-219a6a83564a.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211198687-36ceed4a-e2a3-4401-8a26-2c788810831c.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211198764-a404bfa0-d6b4-42bd-8880-9c2100dfa74a.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211198786-ef8f9e63-9d66-44c6-b328-5cdba4eff0bc.png">
---|---|---|---

**Comment by anvmn** [comment]
@LudmilaGoichman is this a problem, or it's checked and approved?

**Comment by LudmilaGoichman** [comment]
@anvmn Approved. Sorry, copy-paste mistake
