### ISSUE TITLE
[FEATURE] Resilience Messaging (RM)

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#586]
## Feature Issue 
Resilience Messaging is a program that we are implementing that has been shown to help healthcare workers learn to better manage the daily stress and fatigue of their roles. Messages and activities were created by an outside organization and then adapted by TIP to meet the Rwandan context. 

We have decided to implement them in a messaging center format to begin with. This lays the groundwork for a future of messaging within the app. 
 
## Figma 
- [Figma can be found here](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=2%3A3&t=1bcjKvjchg0yqYLK-0)

## Supporting Docs/Files
- [Master Spreadsheet ](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit?usp=sharing) -> Tab = Dev Master
- [Video Overview](https://www.loom.com/share/39f362bb5d094ab792288c5aa268105c)
- [Entry Flow Video](https://www.loom.com/share/4fc94ef2966245f0beeb38886ea2b834)

## Related Issues 

- #591 
- #592 
- #593 
- #594 
- #595
- #596
- #597 
- #598 
- #599 
- #600 
- #601 
- #602 
- #603 
- #604 
- #605  
- #606 
- #621 
- #629

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

Looked through the issues, and made some comments.
Don't yet have access to master spreadsheet, so I can't get into messages details, but here are general comments and questions:

1.  Who participates in that 'Program' issues describe? Al nurses and/or CHWs? Only nurses / CHWs? Some nurses and/or CHWs (in this case, how do we indicate which ones)?
2. What is considered to be the program 'start date'?
3. Seems like we need to be managing inbox of messages, which means that all that content need to be stored on backend, and be synced. I don't have yet access to master spreadsheet, but with all those read / unread / favorite requirements, we'll have to store separate entity for each message.
Since nurse can work on any device, this means we need to be transfering all messages of all nurses to all devices.
4. What do we do with monthly / 3 months surveys? Is it only for storing on backend, or, we need it for some decision logic on the device?
5. Currently, estimations are off - can not be used for planning (calculation of completion date, etc...).

**Comment by jeanette-pelizzon** [comment]
1. CHW's + Nurses will be participating. We need to figure out a way to give just certain Health Care Workers (HCWs) to have access at a time. We discussed a boolean field in our call on 1/16. 

2. Agree that start date will be the first time they enter into the wellbeing app. 

3. We can go with what we just discussed on 1/16 - whatever you think will work best. 

4. We just need to store survey data so that the Resilience Team @ TIP can see and do whatever they need to with the data.

5. I just took guesses on hours it would take since this is a new content type for me. Can you comment on the issues that need the estimations changed with what you think it will take? Thanks! @adamhstewart plz note this estimation is off and shouldn't be counted on.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> CHW's + Nurses will be participating. We need to figure out a way to give just certain Health Care Workers (HCWs) to have access at a time. We discussed a boolean field in our call on 1/16.

In this case, seems to me that Wellbeing on homescreen should be displayed only for HCW who participate in program. What do you think?

![Selection_1492](https://user-images.githubusercontent.com/17882245/212768218-e24e8eb4-9608-4c91-bdf0-8fbdd3dabca5.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn yes, I think that makes sense.
