### ISSUE TITLE
RM - Message Content [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#593]
## Issue 

Each individual message has customized content. Messages are arranged in a pre-defined order according to the program. You can see the content for each individual message via [this spreadsheet ](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit#gid=419344799)under the "Development Master" tab. 

## To Do: 
- Create individual messages

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Leaving popups aside, with 38 messages we got right now, this issue is very much underestimated.
It should be at least 12h.

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

### QA review. First Part - Introduction.

- nutrition env
- tablet

### Questions/Found Issues:

1.  The order of messages is wrong:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220383573-3a486d40-0fe6-4fa2-9205-651c9100959b.png">|<img width="255" alt="image" src="https://user-images.githubusercontent.com/35059802/220960762-d8caf457-49f2-4b3d-81e2-23d480aee7e7.png">
---|---

2. The titles of these messages must have a dot at the end:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220390006-60e62967-9827-4bbd-9714-7cc88bef0ce9.png">

In the Excel file at the end of the title of this message there is no dot, but I think it should be added:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/35059802/220964337-844b3aa5-d7f8-42b5-83fe-3968ae5299f8.png">


3. In the next message:
      a. the list should be numbered instead of bulleted
      b. there should be a dot at the end of the last sentence
<img width="334" alt="image" src="https://user-images.githubusercontent.com/35059802/220391426-8c290931-c059-4cdf-86b1-2c475dec3435.png">

4. In the next message:
      a. the ":" is missing before the bulleted list
      b. all entries in the list must end with a dot or all without a dot
      c. fourth entry in the list. I think it contains a typo. I think it should be "learn" not "learns"

<img width="341" alt="image" src="https://user-images.githubusercontent.com/35059802/220393965-5604afe4-b646-4fa7-a91a-16fce541dfe0.png">

5. A dot missing in the end of this message:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/35059802/220395038-c5a4ebd5-1364-42af-a5f5-c19714de1d1d.png">

6. The last sentence should be bold

<img width="351" alt="image" src="https://user-images.githubusercontent.com/35059802/220963092-f7398bfe-e2a5-4c01-a2cb-b247006c0829.png">

7. The title of this image has been fixed in the Excel file:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/35059802/220965209-e27a66e9-225a-451d-988c-b32b177fcc4a.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/35059802/220965310-1a4b0d12-aa61-4806-9ef7-b426d7ee2d11.png">

### Checked and Approved:
1.  The first 4 messages appear on the first day, and the additional 4 messages the next day. (for Nurse and CHW)

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220384119-73207d31-5dda-46f0-9185-cb8855423808.png"> |<img width="255" alt="image" src="https://user-images.githubusercontent.com/35059802/220961404-e2f8beac-6a21-4a8c-813c-0b060616702e.png">
---|---

2. The message text is correct except for the issues mentioned above

**Comment by LudmilaGoichman** [comment]
@anvmn I updated the first part of the QA review ^^

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

### QA review. Second Part - Mindfulness.

- nutrition env
- tablet

### Questions/Found Issues:

1.  The titles of these messages must have a dot at the end (or all titles without dot):

<img width="349" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221545854-c851afdd-1a2a-4443-8146-623c70b55501.png">|<img width="357" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221546794-bc1f0fb6-b07e-4042-b034-166451d9e781.png">|<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221550352-a7f0c7ed-2a4d-4b37-bc81-b13fa3835862.png">|<img width="346" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221552267-422eef8c-3084-4487-aac2-221cfdf195d4.png">|<img width="351" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221806910-b2e80e24-32f4-430a-92d1-f79393d1f3f7.png">
---|---|---|---|---

2. The last paragraph should be bold in the next messages

<img width="357" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221547055-e26c9672-52f4-4e58-a40d-59b6e67c7379.png">|<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221550419-5e3a6531-4d49-4536-8550-93bad34ad8dd.png">|<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221551296-4caf5887-efcb-41d3-a45e-80d935534cc4.png">|<img width="346" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221552881-ad9b155a-4ba7-415e-b791-629d8e5d78f5.png">|<img width="351" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221807303-be7fb1cc-341e-4462-9ca0-46d8156c8701.png">
---|---|---|---|---

3. The list should be numbered instead of bulleted:

<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221551533-e55499c8-1df5-4fc7-9027-a40390d696cd.png">|<img width="351" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221807503-caf103cf-b1b3-4368-98a5-bfa9af5018fe.png">
---|--


5. The following sentence is missing above the list: `Do the following:`

<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221551842-3f9d127d-36fd-4747-b60e-cb04783c0f33.png">

### Checked and Approved:
1. All 6 messages appeared
2. The messages text is correct except for the issues mentioned above

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

### QA review. Third Part - Stress Management.

- nutrition env
- tablet

### Questions/Found Issues:

1.  The titles of these messages must have a dot at the end (or all titles without dot):

<img width="347" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221557932-bd6d1e84-83a0-4fbb-bf95-2d502ff7aca8.png">|<img width="370" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221813046-7eeb6756-fd84-49ef-aaa1-6ab7b74493f4.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221817825-2f3fb71b-b9db-485a-b566-43e2dbbf80a4.png">|<img width="603" alt="image" src="https://user-images.githubusercontent.com/35059802/221825971-129677ae-3263-4fd8-9e76-c8970bb05af5.png">
---|---|---|---

3. Missing question mark at the end of the title.

<img width="346" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221555306-48a9a70c-cfcd-44be-b95f-40bc0835a942.png">

4. The last paragraph should be bold in the next messages

<img width="346" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221556031-948ac690-6695-4315-a614-8d9d67267f40.png">|<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221557262-bcf60475-2a45-40d7-a345-45a8fe0265fc.png">|<img width="347" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221559275-ed29082b-ada9-4bd6-89be-e4db9e590897.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221817959-c7253bdb-58f1-4060-9350-774c7e1bf262.png">|<img width="603" alt="image" src="https://user-images.githubusercontent.com/35059802/221826142-7a1a7d77-85bf-4c03-be5a-cc1270144029.png">|<img width="608" alt="image" src="https://user-images.githubusercontent.com/35059802/221826913-60a8b8ab-2733-4b9b-9b40-d460413b6917.png">
---|---|---|---|---|---

5. The list should be numbered instead of bulleted:

<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221557173-872773dd-fb6e-47c0-beb0-cf1a62da122e.png">|<img width="370" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221813537-5c81030a-1909-4578-aa87-7e02929fa101.png">
---|---

6. All entries in the list must end with a dot or all without a dot

<img width="351" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221557563-f0b14e59-b965-479a-82ad-de0f3e0d7cec.png">|<img width="370" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221815029-21d69934-abd9-4086-9a28-a0ba6d760fd2.png">
---|---

### Checked and Approved:
1. All 7 messages appeared
2. The messages text is correct except for the issues mentioned above

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

### QA review. Fourth Part - Self Care.

- nutrition env
- tablet

### Questions/Found Issues:

1.  This category is written in the Excel file as `Self-care` Which version is correct?
<img width="349" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221561104-98232090-2a14-4636-97fe-b3449e485c26.png">

It's different in all places:

<img width="341" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221852102-05492c71-6a18-49f1-b8c7-e093a2f5c0b4.png">|<img width="342" alt="image" src="https://user-images.githubusercontent.com/35059802/221852972-e662b92d-4427-4b61-ac58-19b7ce13813b.png">
---|---


2. The titles of these messages must have a dot at the end (or all titles without dot):

<img width="349" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221561180-ee26e950-94fd-44a8-aa9a-efc89a3e3c33.png">|<img width="348" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221828415-bf3717cd-6481-4743-834b-26a8f02b8f8d.png">
---|---

4. The last paragraph should be bold in the next messages

<img width="349" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221562020-4ec788bc-d4f0-450a-b20e-21554448a778.png">|<img width="348" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221828620-954ff9b1-0687-46d5-921d-41c4b4e6caf5.png">|<img width="349" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221851850-ac1a64f0-206a-42ab-805e-42ff82d96b69.png">
---|---|---

5. The list should be numbered instead of bulleted:
<img width="349" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221561925-0e4344de-ecb9-4b34-ac98-149e591e66e2.png">


### Checked and Approved:
1. All 3 messages appeared
2. The messages text is correct except for the issues mentioned above

**Comment by LudmilaGoichman** [comment]
### NOT FINISHED! IT WILL BE UPDATED

### QA review. Fifth Part - End Of Month.

- nutrition env
- tablet

### Questions/Found Issues:

1.  This category is written in the Excel file as `End of the first month (No Category)`. Which version is correct?

<img width="344" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221575198-a90b4185-50ba-4dd7-9568-5b9cc78420a2.png">

2. I think there is a dot missing at the end of the first paragraph

<img width="344" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221576299-a9a3f064-16e5-429e-9052-24620709eb7c.png">


3. The list should be numbered instead of bulleted:

<img width="344" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221576410-468f465f-6c20-418a-8e2c-d6fb24687bb5.png">

4. All entries in the list must end with a dot or all without a dot

<img width="344" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221576590-defb86eb-52eb-417c-b111-a0f62d9ac7b9.png">


### Checked and Approved:
1. All 2 messages appeared
2. The messages text is correct except for the issues mentioned above

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart

### QA review. Seventh Part - Growth.

- nutrition env
- tablet

### Questions/Found Issues:

1.  The titles of these messages must have a dot at the end (or all titles without dot): 

<img width="347" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221581046-6160393f-4362-425e-b6a8-11d29c4b00bd.png">|<img width="420" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/222968721-9707dc7d-bee9-4dfc-ac10-eec3fb559559.png">|<img width="473" alt="Shottr" src="https://user-images.githubusercontent.com/35059802/222969054-fbbd315c-4dba-42cc-a7d4-4a1f81a2a4f5.png">
---|---|---

2. The last paragraph should be bold in the next messages


<img width="347" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221581134-21be5cfa-69f4-45fa-839f-073e0a74a723.png">|<img width="505" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/222968615-62d99311-754d-4e47-9b58-2a72ff5378a9.png">|<img width="420" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/222968742-4a81244b-cb81-493a-82de-8b937494d9bc.png">|<img width="473" alt="Shottr" src="https://user-images.githubusercontent.com/35059802/222969106-753ea812-36da-4743-a3c2-5f6180ac3e99.png">
---|---|---|---

3.  I think this message contains a typo. I think it should be "appreciate" not "appreciates"

<img width="347" alt="NEW_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/221582043-cb008b69-a01a-48e3-be9f-22b4c4b1a06e.png">


### Checked and Approved:
1. All 4 messages appeared
2. The messages text is correct except for the issues mentioned above
