### ISSUE TITLE
RM - Entry Flow [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#601]
## Issue 

Please watch [this overview video](https://www.loom.com/share/4fc94ef2966245f0beeb38886ea2b834) to understand how the pop-ups for unread messages appears in the flow of the app. 

The unread message pop-up will appear when a user logs in to the app OR when a user has finished an encounter and navigates back to the homescreen. 

This will only happen if they have unread messages. If the unread messages are at ZERO then NO pop-up will appear. 

## To Do: 
- Ensure pop-up works appropriately

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> OR when a user has finished an encounter and navigates back to the homescreen.

This definition is somwhat problematic, because:
1. There are group sessions, where concept of encounter does not really exist, as session is multiple encounters and also got 2 view modes.
2. As we go on and add new types of encounters, this development will need to be extender to support the new type, which is prompt to errors.

Maybe we can make the notification on Login, and then with periods of one hour?

**Comment by jeanette-pelizzon** [comment]
@anvmn I am okay with making it at hour long intervals - but it should never interrupt an encounter. The pop-up should only appear if they are on the "home screen" or whatever we want to call it. We don't want these messages to pop-up during an encounter because it will interrupt their workflow and cause more stress (which the opposite of the goal of the program).

**Comment by anvmn** [comment]
@jeanette-pelizzon 

That's fine, we develop popup so it's only shown on Main menu screen. Nowhere else.

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Questions/Found Issues:
1. I created a new nurse and CHW. When they logged into the app for the first time, the first message displayed was "drink water" and then "unread messages". Is it correct?

| | Nurse | CHW |
---|---|---
the first message | <img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220372010-bc10c4bd-d344-4598-9f42-c929529b4288.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220372352-d4fbc038-409b-4e4e-b7e8-ccd63a5e102c.png">
the second message | <img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220372195-9f6293b0-fd48-4f09-8077-472c2e941ebc.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220372505-bb85006a-eb27-494b-a3b1-f5223b1fc34e.png">

2. The "unread messages" pop-up was closed by clicking the "ignore" button, but the same pop-up appeared after 5/10 minutes (for nurse and CHW. should be 1 hour, right?). The third popup did not appear after 5/10 minutes - it was after 1h

3. The "unread messages" pop-up was closed by clicking the "ignore" button, but the same pop-up appeared after each refreshing the browser window. Is it okay?


### Checked and Approved:
1. the "unread messages" pop-up can be closed by clicking the "ignore" button
2. the Wellbeing module opens when clicking the "read" button in the "unread messages" pop up

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220382103-84edfa83-b508-47fc-8047-1c0669eedb03.png">

3. The third "unread messages" pop-up appeared after one hour _(approximately. I didn't notice exactly because I checked other issues)_

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220387704-2d57775b-453e-4868-ae33-7ed110cb96fa.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220387909-6419e815-6298-4cce-afad-37709478e345.png">
---|---
