### ISSUE TITLE
RM - Unread Messages [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#603]
## Issue 

In the unread messages section, only messages that have not been read will appear in this category. Watch the video overview to see how this looks and functions. 

- Messages appear in a red color until the have been read by a user. 
- User will tap on a message to expand it and see the full message. 
- User will tap again to collapse a message - this will make a message "read." The message will then move to it's appropriate catefgory
- If a user swipes left on a message, options to mark unread, mark as a favorite, or set a reminder will appear. (There will be issues got each of these scenarios created)

- [Video overview here.](https://www.loom.com/share/39f362bb5d094ab792288c5aa268105c)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> If a user swipes left on a message, options to mark unread, mark as a favorite, or set a reminder will appear. (There will be issues got each of these scenarios created)

This implies using gestures, which is something completly new to the APP.
I suggest we remain with existing method, which are buttons.
The reasons are that introduction of gestures at this stage is not intuitive, which may cause users not to use the features. Also, it's implementation is a considerable extra effort.

I propose moving the date to the left, and at right part of message header placing a button that will open a  popup with options.

![Selection_1525](https://user-images.githubusercontent.com/17882245/214798470-f51e5e63-5f4d-4a13-8a6a-d00d509fffdc.png)

The 'options' button icon can be something like:

![Selection_1524](https://user-images.githubusercontent.com/17882245/214798704-be5aa5b4-cb01-4eb5-84c6-48b1353c575b.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon here's a demo for the popup:

![Peek 2023-01-30 14-26](https://user-images.githubusercontent.com/17882245/215560614-9c762503-a9e2-46e5-9461-f59774d96dd0.gif)

**Comment by Diama1** [comment]
@jeanette-pelizzon do we have the option icon yet?

**Comment by adamhstewart** [comment]
@anvmn This approach is fine... @jeanette-pelizzon can we get an icon with three dots to indicate the menu?

**Comment by jeanette-pelizzon** [comment]
<img width="43" alt="Screen Shot 2023-02-11 at 11 42 57 AM" src="https://user-images.githubusercontent.com/77505464/218278085-3d474dae-4472-476b-a095-a6babeb3979f.png">
https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=1204%3A789&t=3EhEGzPAjrc0b5mv-0

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Questions/Found Issues:
1. The message disappears on the second tap on the message (the first tap expands), even if that tap happened while trying to scroll down, instead of collapsing the message and marking it as read. The same thing happens when you click on the "Read" menu item.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220618917-0050ebb5-c361-4fb5-92e4-2997a041c159.png">|<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220619017-264adc86-ec00-4331-b823-089b58dba321.png">
---|---

### Checked and Approved:
1. The unread messages are red
<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220618633-256c705e-4786-4ee3-8a91-7e9a5d722a9f.png">


2. Tapping on the unread message expands it

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220618559-00591b0a-3d03-4f26-b3ea-cad66f48739b.png">

3. The menu for each unread message is there

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220618757-59760725-9714-4267-af57-c4d87918f991.png">
