### ISSUE TITLE
RM - Remind Me Feature [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#606]
## Issue 

When a user swipes left, they will have the option to remind themselves later about a message. Then message will be marked as read until the set time, when they will reappear in the unread category. 

They have the option to "snooze" or "remind me later" of 1 hour, 6 hours, or 12 hours. 

<img width="312" alt="Screen Shot 2023-01-13 at 3 42 48 PM" src="https://user-images.githubusercontent.com/77505464/212438051-aefb2331-b142-4ef0-b458-69af3a89fc13.png">

[Figma](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=417%3A1275&t=1bcjKvjchg0yqYLK-0)

[Video Overview](https://www.loom.com/share/39f362bb5d094ab792288c5aa268105c)

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Questions/Found Issues:
1. there is no messages that marked as "read" so the message disappears after selecting time for reminding.
// _I think it's very inconvenient that the read messages disappear (especially on the second tap). I think for this the "delete" menu button can be added, and the read messages can be moved to the "read" additional tab._

2.In the Favorites tab, the user can set the same (or different) reminder time for the same message an unlimited number of times, since the message does not disappear from this tab. 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220899296-d4e65ca5-f6d9-4764-b8fe-4fbb5a842fe5.png">

3. Messages, for which a reminder time has been set in the Favorites tab, don't appear in the Unread tab after the reminder time has elapsed.

### Checked and Approved:
1. the message's menu in Unread and Favorite tabs includes the "Remind Me" menu item

Unread | Favorite
---|---
<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220891933-69623b05-ac9e-4531-b75e-f3ab753cd004.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220892141-37263f6e-fa0e-4300-8ffb-fdee78dd545d.png">

3. After clicking the "Remind Me" menu item, the pop up with time for reminding appears:

Unread | Favorite
---|---
<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220893227-24d30a06-2776-462a-bfd2-7128b6d70767.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220893334-22ec9b70-85b3-4219-8319-891389569a98.png">

5. If to click the "Cancel" button ^^, the pop up disappears
6.  If to click one of the "x hour(s)" button, the pop up disappears and the message from the Unread tab also disappears (if this message was in this tab). The message in the Favorite tab remains.

Examples:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220894600-6860bd0a-2a56-4145-9dda-480d040a9925.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220894697-154edac9-50e1-47d6-972b-09a708911dfb.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220894796-c5fd8ee2-7d44-4427-ab13-d430031301d2.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220895049-cd0a1536-6d92-442a-9a51-12ba38509655.png">
---|---|---|---

<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220896624-880ea4dd-151a-4502-979f-5478ae7ecb2e.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220896823-21b68227-f28d-457f-812d-c61b9fb9ecae.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220896949-d867fa9d-2ebe-4215-a174-046638309700.png">|<img width="371" alt="image" src="https://user-images.githubusercontent.com/35059802/220897091-ab0bd8a4-0693-4e68-be0b-dd2c10892034.png">
---|---|---|---

7. Messages for which a reminder time has been set in the Unread tab, appear in the Unread tab after the reminder time has elapsed.
