### ISSUE TITLE
ANC - Obstetric Exam - Fundal Height [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#626]
## Issue 

Based on feedback from HCW's, we need to make some changes to the obstetrical exam - fundal heigh section. 

- Hide Fundal height input (this will become conditional based on next point)
- Add in the question "fundal palpable?" -> Y/N
- If yes, then the height input should appear and work as previously designed 
- If no, the height input will stay hidden and a Pop-Up will appear (see design)

If Yes: 

<img width="282" alt="Screen Shot 2023-01-24 at 2 28 18 PM" src="https://user-images.githubusercontent.com/77505464/214436527-ebc39a78-6ddd-487c-baf9-d6ce7ef10b54.png">

If No: 
<img width="277" alt="Screen Shot 2023-01-24 at 2 35 00 PM" src="https://user-images.githubusercontent.com/77505464/214436469-21a855e9-1ba3-4104-9e68-09ebe649674c.png">

## Figma 
- [Figma is here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=1630%3A39512&t=nmJuG2XH9xswpuoA-0)

## To Do: 
- Update conditional logic 
- Add question 
- create pop up 
- style screen per design

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 

- nutrition env

### Question:
1. The popup shows the word "recommended" instead of the word "recommend" as in the design. Is this a bug?

<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219095951-54547148-dd15-4500-924f-c703e7c771fc.png">


### Checked and Approved:
1. conditional logic has been updated and a new question has been added:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219097600-d1fd814e-139c-4580-9c24-311ce193f160.png">

2. If the answer is "yes":

first encounter | subsequent encounter - previous measurement is shown |
---|---
<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219094852-41169c8a-3b9c-4321-afb8-816aeac3b4ea.png">|<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219097962-6c853382-39c7-446d-83e7-e0f7b66e424d.png">


3. If the answer is "no":

<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219095447-bf01b5c8-0a55-480e-ae0d-2ed8bb1e9de5.png">|<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219097222-7f04786e-f690-4bd8-996c-cd7701f18187.png">
---|---
