### ISSUE TITLE
ANC - Logic - Mastitis 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#628]
## Issue 

We are updating the logic for mastitis. 

- Getting rid of the early mastitis or engorgement diagnosis - that logic will now diagnose as mastitis 
<img width="1366" alt="Screen Shot 2023-01-24 at 5 10 43 PM" src="https://user-images.githubusercontent.com/77505464/214457451-be6b235c-9967-4eaf-ab37-782eabb77dd6.png">

- update the medication distribution screen 

<img width="229" alt="Screen Shot 2023-01-24 at 12 42 52 PM" src="https://user-images.githubusercontent.com/77505464/214457377-daa010d1-a026-48c2-9dad-379e4a8935f8.png">

## To Do: 
- update screen per design 
[- update logic per logic document
](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

**Comment by anvmn** [comment]
@jeanette-pelizzon 
 
1.  wrong screenshot

2. > update the medication distribution screen

   As I unertand, we now diagnose Mastitis for criteria of Early mastitis or engorgement . Currently, at both diagnoses, we have same Health education and Medication distribution, with diffrent set of medication. So what changes is that we'll dispaly medication set of Mastitis.
Is this the only change needed?

**Comment by adamhstewart** [comment]
@anvmn a slight redirection here: We will keep the diagnoses as they appeared before (early mastitis and engorgement), rather we will combine all the medication options for all three diagnoses (early mastitis, mastitis, and engorgement) so that every medication option is available for every diagnosis.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

@adamhstewart Since "We will keep the diagnoses as they were before", could you please revert the changes in the Excel sheet? According to @anvmn it should look like this:

![image](https://user-images.githubusercontent.com/35059802/220101677-6c00ee07-7fe8-463b-a008-3e3acb66f69d.png)

- nutrition env
- tablet


### Checked and Approved:
1. The the medication distribution screen has been updated: the same medication are offered for early mastitis or engorgement and mastitis diagnoses. Examples:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220099864-35140bf6-975b-4d81-9bfa-aa5f1fce62b9.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220099924-878b94db-23d0-4369-8e2f-8220c6570edd.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220100556-272fb83b-026f-434b-8090-74f0a421a6aa.png">
---|---|---

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220100942-37c3199a-7a55-442f-965d-d4d0b6019430.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220100671-263c0443-346e-4a6f-994e-460176293c96.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220100834-0ebc804d-8e3b-40b7-a130-792d998b8fe4.png">
---|---|---

**Comment by adamhstewart** [comment]
@jeanette-pelizzon can you confirm the above comment and add to the master doc.

**Comment by jeanette-pelizzon** [comment]
reverted the excel doc back. Should be good to go now.
