### ISSUE TITLE
ANC - Malaria Prevention - Logic Update [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#630]
## Issue 

Based on feedback from HCW's we need to make the Malaria Prevention activity optional in the first half of the visit and, if not completed, re-appear when they go to input test results later. This is because they said that sometimes they give the mosquito nets out during the second half of the visit and we need to account for that. 

They can move on to next steps without completing this activity. It will then reappear in the 2nd half and at that time it will be required to answer.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- nutrition env
- tablet

### Questions/Found Issues:
I have a question about the end of the encounter when the Malaria Prevention activity appears along with the Lab results activity. If the Lab results activity is completed first (the mosquito net has not been delivered yet), then the Progress report will be opened with the disabled "end encounter" button. Therefore, the nurse should return to the activities view for completing the Malaria Prevention activity

<img width="368" alt="image" src="https://user-images.githubusercontent.com/35059802/219962708-99b5b596-4225-44be-8846-93cbf8cbafe1.png">

But when the nurse completes the Malaria Prevention activity, she needs to open the Progress report again, because there is only a "leave encounter" button in the activities view and the "end encounter" button only appears in the report

<img width="368" alt="image" src="https://user-images.githubusercontent.com/35059802/219963129-26fe111e-ef8e-49cb-b93a-5d2f59f9e240.png">|<img width="368" alt="image" src="https://user-images.githubusercontent.com/35059802/219963159-67579dc5-b6ff-4b78-8014-4adc4dac3937.png">
---|---


### Checked and Approved:
1. If the Malaria Prevention activity was not completed  in the first half of the visit then it appears with the Lab results activity. And encounter cannot be ended if the Malaria Prevention activity will not be completed:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/35059802/219962212-10d0e680-1fae-4add-9bf5-75e1951d7b98.png">|<img width="368" alt="image" src="https://user-images.githubusercontent.com/35059802/219962336-9997560f-c68a-49f7-9cf8-8845997ea39b.png">|<img width="368" alt="image" src="https://user-images.githubusercontent.com/35059802/219962366-dc2b82f6-cb68-4fe0-89f9-d1d74f8acf9c.png">
---|---|---

2.  If the Malaria Prevention activity was completed  in the first half of the visit then it doesn't appear with the Lab results activity.

**Comment by adamhstewart** [comment]
Added the userflow comment to backlog for analysis.
