### ISSUE TITLE
ANC - Progress Report - Malaria Blood Smear [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#632]
## Issue
We had to introduce a blood smear option for malaria testing. This test will not always be run but when it does get used it needs to appear in the lab results section of the progress report. It will only show up on the progress report if it has been run. 

- Name of Test: Malaria Blood Smear
- Normal Result = Negative 
- Result Options = Negative, +, ++, +++ 

## To Do: 
- Add this test to the progress report 
- Let jeanette know if you need a design for this but it should be pretty straightforward.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- nutrition env
- tablet

### Questions/Found Issues:
1. The test name should be `Malaria Blood Smear`

> Name of Test: Malaria Blood Smear

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959096-f9c8fece-4ff7-4b9a-9f83-4196f17d3099.png"> |<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219960008-282ca8b5-99f4-4c05-9f6e-ffbfc106b699.png">
---|---

2. When the Malaria Blood Smear test result is `negative`, the result doesn't appear in the report (in all encounters)

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959298-d46df29b-a337-4c71-ab9f-2744665dbdcd.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959351-dd95734e-783b-45ec-a157-f631b29dffeb.png">
---|---

3. when the test wasn't be performed, the record appears in the report

>  It will only show up on the progress report if it has been run.

first encounter:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219960224-1c2bce1d-d409-41ee-9bb6-9cf84209333e.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959547-06bd61a6-f462-4d55-9935-ce41501dd252.png">
---|---

subsequent encounter:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219960095-e9df286d-3a47-41ed-8157-4e17a07902fe.png">| <img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219960124-7c7d682c-ca7b-4e33-9f9b-ce65d4bcf1d4.png">

4. Why does the test (RDT?) result appear in the node? Is it because of the blood smear test result "++" or because I checked different cases including the RDT test result and it was not removed (the last saved test was a blood smear)?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/35059802/219960597-cdff5154-0b91-4081-aa44-df763f565ee2.png">

### Checked and Approved:
the Blood Smear test result appear in the lab results section of the progress report in the following cases:

the first encounter:

|+ | ++ | +++ |
---|---|---
<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219958905-3069fcf1-d7eb-416f-93c0-9705c1508f21.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219958935-3f77625b-1623-49e0-9e89-1bc623d1cbcc.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219958880-c019f4dc-4868-4c97-aef1-09fd3bc2d58d.png">

the subsequent encounter:

|+ | ++ | +++ |
---|---|---
<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959752-f1c458a6-d10a-4231-82a4-cdf07c44d443.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959813-c87b7e20-c75b-42ae-91bd-2d2d369865fb.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959883-0ef0a809-75ae-4773-b532-ac5545f7b3d8.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959790-117f79a7-19a0-4520-991e-688c3344b0df.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959860-f930edd4-a796-4fa4-9e5f-fe0d00dd201e.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219959912-81c7adfb-ce6d-4004-a92d-3668611ff661.png">

**Comment by adamhstewart** [comment]
@anvmn please review these questions

**Comment by anvmn** [comment]
@adamhstewart 

Points 1, 2 and 3 are fixed.

> when the test wasn't be performed, the record appears in the report 

> 4. Why does the test (RDT?) result appear in the node? Is it because of the blood smear test result "++" or because I checked different cases including the RDT test result and it was not removed (the last saved test was a blood smear)?

Because you different cases including the RDT test result and it was not removed.
What counts there is the test note that says than test was not performed.
