### ISSUE TITLE
ANC - Health Center - Case Management [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#65]
## Issue 

Due to the fact that the laboratory needs to process the lab samples before results are given to the patient, E-Heza needs a way for the nurse at the Health Center to enter lab results for a patient outside of their initial encounter. To do so, the nurse will go into case management and click on a "Lab Results" tab. This will display the name of the patient, the status of the results, the type of labs they are waiting for (right now all we have is ANC but this may change in the future), and the arrow to begin inputting the results. 

When a nurse clicks on the arrow, all the lab tests that have not yet had lab results input (either from today or previous) will appear.  Lab results are typically returned the same day. The patient waits while the lab processes and goes back in to see the nurse and receive the results. There may be outlier cases where results are given the next day which is why all lab tests waiting for results should appear. 

![image](https://user-images.githubusercontent.com/34378755/145395060-2cce0ee9-de03-40e8-889c-8f8be43898fa.png)

Each test has different result inputs and those are in the issues for each specific lab. Separate issues for those screens have been created.

### Logic and labels

After 14 days, a test that has not had results recorded will automatically close.

Labels on the case management screen: 

- 0 - 7 days from the time of the encounter - pending tab in yellow 
- 7 - 14 days from the time of the encounter - closing soon tab in red 
- @ day 15 close the encounter - it will be marked on the progress report as a missing result

### Design
They can also be found in Figma [here](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5965%3A43454).

## To Do 
- Add `Lab Results` section to case management (nurse)
- Implement logic for informing open lab results activities from ANC encounter
- Implement logic for labels
- Logic for flow to open lab result activities
- Implement logic for closing results and informing progress report

### Clarifications

No ~~There is no pop-up to confirm beginning the lab inputs. I know we have it elsewhere. For consistency do we want one here? I don't think it's needed.~~

**Comment by anvmn** [comment]
@isapisa 

> Implement logic for pending vs complete labels

What logic would that be? I need a list of possible labels and conditions for each one.

**Comment by isapisa** [comment]
@jeanette-pelizzon 

I had suggested `Pending` and `Complete` in the issue above, but since this is the case management, I assume we don't actually need `Complete` (if nothing is to be entered, then it wouldn't show for nurses).

Are there any other possible labels?

Also, what do you think about this definition?

`Pending = Any results not entered from an ANC encounter > Labs activity`

**Comment by jeanette-pelizzon** [comment]
The only label for this would be "Pending."  If it is complete, it won't appear in case management. They will stay as pending until completed or baby is born - whatever happens first. (hopefully the labs happen first though!) 

Definition is more or less correct - It would be any test that has been run but has not yet had results input into E-Heza.

**Comment by isapisa** [comment]
@jeanette-pelizzon 

`Pending = Any test that has been run at Labs activity but results not entered. Stay as pending until completed or baby is born`

**Comment by anvmn** [comment]
@isapisa

I don't think this definition can work.
Take a case where for whatever reason one of lab results is not entered.
This will keep the entry at case management.
On next visit of that person, there will be another entry, which will cause confusion.
At issue description it's said that results will be submitted on same day, or the day after.
I suggest we set some kind of limit. For example, we show the entry for 5 days. Then, it's considers resolved.

**Comment by isapisa** [comment]
@anvmn 

alternatively, we should keep showing the lab results that are pending for all those that are not recurring in the next encounter.

For example, referencing the [labs logic](https://github.com/Gizra/ihangane/issues/2820), `Syphilis` test is taken at the first encounter and then again at 38 weeks.
If the results are not entered after the first encounter, we should keep showing it until the next time a nurse takes the test.

It would be more complex, but might make sense to do it this way. There could many reasons that a nurse will not enter the lab results within, for example, 5 days.

What do you think?

@jeanette-pelizzon did you discuss this with Wendy by any chance?

**Comment by anvmn** [comment]
@isapisa 

> There could many reasons that a nurse will not enter the lab results within, for example, 5 days.

My guess is that whatever is not entered withing first few days is lost, and will not be filled, ever.
I think it's for @adamhstewart and Wendy to decide.

**Comment by isapisa** [comment]
@jeanette-pelizzon @adamhstewart one to take up at your next clarification meeting please ^^

**Comment by jeanette-pelizzon** [comment]
Talked this through with Wendy and Adam today in our meeting. Past results will remain until they are input, the child is born, or they saw why they were not input. 

Results will group together. For example, Hemoglobin is run every visit. If it is ordered and the results are never input through case management, the results will remain in case management. The next hemoglobin test that is run will appear on the same input screen as the previous one. The previous test will be labeled so the nurse will see that it was a previous test. 

![21](https://user-images.githubusercontent.com/77505464/144915451-221de7be-71f7-4663-9ec7-227b51eeea92.jpg)

If the test results were received, then this screen appears: 

![22](https://user-images.githubusercontent.com/77505464/144915522-21419c48-212e-48f4-90c3-b8303e7cbb3d.jpg)

If the test results were never received, then this screen appears: 

![23](https://user-images.githubusercontent.com/77505464/144915568-e4476b7b-ef7b-45fa-98a7-50536ed97522.jpg)

Tagging @leowea for approval on the designs.

Let me know if you have any questions or concerns.

**Comment by leowea** [comment]
@jeanette-pelizzon @isapisa These are looking great! If it were in the US, 'prior draw' would make perfect sense. I'm not sure that this is typical language in Rwanda. Could it say 'prior test'? Otherwise it looks great!

**Comment by jeanette-pelizzon** [comment]
Per the conversation today, we are going to hold off on making this change. 

We will keep the flow for case management the same as it is currently. After 14 days, a test that has not had results recorded will automatically close.

Labels on the case management screen are changing: 

- 0 - 7 days from the time of the encounter - pending tab in yellow 
- 7 - 14 days from the time of the encounter - closing soon tab in red 
- @ day 15 close the encounter - it will be marked on the progress report as a missing result

<img width="540" alt="Screen Shot 2021-12-08 at 4 02 06 PM" src="https://user-images.githubusercontent.com/77505464/145292626-5507e2a5-4f22-454a-bb83-7f9d560171aa.png">

**Comment by leowea** [comment]
@jeanette-pelizzon looks great.

**Comment by isapisa** [comment]
@anvmn updated the main issue

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env
- tablet

### Question:
1. >@ day 15 close the encounter - it will be marked on the progress report as a missing result

Should the test appear again on the subsequent encounter in this case ? Test for Syphilis-RPR with missing result doesn't appear in subsequent encounter.

<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148439197-7f43c883-f4ff-45e1-a3ad-cf9cf5c1adc9.png">|<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148439283-2f495023-a4fc-4ea8-919b-6fb9cbe8aa5b.png">
---|---

### Checked and Approved:
1. Lab Results section has been added to case management (nurse):
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148431766-8b74a4be-d896-47b6-9025-a56c7c9afd36.png">

2. logic for informing open lab results activities from ANC encounter has been implemented:

| report from the first encounter | lab results activities |
---|---
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148432137-376c6b55-4fb8-470a-a72f-889b8d08db0a.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148432316-f4bbfc8b-c6a2-4e2f-b007-e378d6354647.png">

3. logic for labels has been implemented:

- 0 - 7 days from the time of the encounter - pending tab in yellow:

| today encounter | yellow label |
---|---
![Prenatal_Encounter_-_Individual_Participant_-_Akuzwe_Bellancile_-_2022-01-06_-_2022-01-06___E-Heza_System](https://user-images.githubusercontent.com/35059802/148433093-2e29cce4-e9e1-4aed-8027-205db6b73af4.png)|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148433186-a1b1a0cf-ea44-4f5c-8ef3-16fe9a2102c0.png">


| encounter before 7 days | calendar | yellow label |
---|---|---
![Prenatal_Encounter_-_Individual_Participant_-_Akuzwe_Berthe_-_2022-01-06_-_2021-12-30___E-Heza_System](https://user-images.githubusercontent.com/35059802/148433594-54151c9a-c9b0-43bb-99c1-737127a6a97c.png)|![Gizra_ltd__-_Calendar_-_Week_of_January_2__2022](https://user-images.githubusercontent.com/35059802/148433750-70c73a21-3eaf-4fb7-b88d-ce632d567039.png)|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148433856-30cf90b0-c70d-4db4-ac79-b822ab9d02ac.png">


- 8 - 14 days from the time of the encounter - closing soon tab in red

| encounter before 8 days | calendar | red label |
---|---|---
![Prenatal_Encounter_-_Individual_Participant_-_Akuzwe_Benitha_-_2021-12-29_-_2021-12-29___E-Heza_System](https://user-images.githubusercontent.com/35059802/148434177-f8dc0dd4-1482-411c-8b1c-b77a3c60fcec.png)|![Gizra_ltd__-_Calendar_-_Week_of_January_2__2022](https://user-images.githubusercontent.com/35059802/148434284-ec719561-363e-4816-995e-b771be74fe5a.png)|<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148436406-a5cf0307-3555-4f52-8a41-abbb380b001c.png">

| encounter before 14 days | calendar | red label |
---|---|---
![Prenatal_Encounter_-_Individual_Participant_-_Cyiza_Bellancile_-_2022-01-06_-_2021-12-22___E-Heza_System](https://user-images.githubusercontent.com/35059802/148437101-464904e4-50fb-407a-baac-856579a6a23d.png)| ![Gizra_ltd__-_Calendar_-_Week_of_January_2__2022](https://user-images.githubusercontent.com/35059802/148436821-c3837cc4-9922-49b1-94f1-f43cfa00ea64.png)|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148437234-cf1dc17c-a663-40f1-a30b-3644c73e7376.png">

- @ day 15 close the encounter - it will be marked on the progress report as a missing result

| encounter before 15 days | calendar | case management in the day of encounter | case management after 15 days | the report |
---|---|---|---|---
![Prenatal_Encounter_-_Individual_Participant_-_Cyiza_Benitha_-_2022-01-06_-_2021-12-21___E-Heza_System](https://user-images.githubusercontent.com/35059802/148437484-52365550-d015-4a77-a84b-810e0b12dc65.png)|![Gizra_ltd__-_Calendar_-_Week_of_January_2__2022](https://user-images.githubusercontent.com/35059802/148437892-887ccc23-f06f-4bf1-8d73-e6581847291b.png)|<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148437976-8d535061-cf58-4e61-ae3a-a71cc6c5dc38.png">|<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148438007-bca42fc2-a703-4e78-a6c5-007e3710398a.png">|<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148438787-0828c563-5f4d-4ec0-98db-98d66f8a3775.png">


4. Logic for flow to open lab result activities has been implemented

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148432636-2ed346d5-6c61-4016-910a-74709280862b.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148432679-3b1cd5d7-8095-4145-a64c-0f331c68a2e4.png">
---|---

5. logic for closing results and informing progress report has been implemented

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148440631-85c020af-740d-46c2-8e8a-2e908aa80bbd.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148440669-ef954ec1-25a8-4e08-aa91-e65fdce2c288.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148440691-4e4fb8d0-1cff-4c8a-bc77-f776f5ee9c48.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148440719-144d9de7-a3e5-4a40-b8e5-be47feec80a1.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148440783-2adb101c-3390-40fc-a18e-91990c8e7fbc.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148440844-e01c7490-efc1-411b-9e57-b3cd0457d17e.png">
---|---|---|---|---|---

6. >There may be outlier cases where results are given the next day which is why all lab tests waiting for results should appear.

| test from today | test from yesterday|
---|---
<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148438428-bfd36676-de52-47d5-af2f-b5ad9af57187.png">|<img width="367" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148438476-36f19d1d-21a3-4391-bd62-880aa5db3643.png">

**Comment by jeanette-pelizzon** [comment]
1) On day 15 after a test is run, if no result is put in e-heza, it will automatically say it's a missing result. If it is a test that is run again in the pregnancy, then it should reappear the next time it is required. If it is a test that is not required multiple times (Blood Group + Rhesus, Blood Sugar) then it should populate on the next visit after the 15 day period has happened. 

This is what the screens should look like: 

Run Previously? | Pop Up | Results Entry
--|--|--
![Random Blood Sugar](https://user-images.githubusercontent.com/77505464/148845106-7da663c8-9a7b-4004-8c8c-71cc0ebbc98d.jpg) | ![Random Blood Sugar-1](https://user-images.githubusercontent.com/77505464/148845118-f1248946-e4a1-4cc3-a2b0-9a0c4cebb736.jpg) | ![RBS 4](https://user-images.githubusercontent.com/77505464/148845134-f9fa0c91-6c67-47e5-a80d-8015914a7790.jpg)


// @adamhstewart

**Comment by jeanette-pelizzon** [comment]
We aren't holding Acceptance Testing for this issue, but it does need to be resolved. @anvmn do you have any questions? 

// @isapisa  @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Well, this is slightly different from what we have discussed.
The case is that there was a test performed, but it's results were not filled within 15 days.
This can happen for different reasons. For example, test may be faulty, or it was lost at the lab.
In these cases, we don't have a result to fill, so requrements ^^ are not implementable.

What should happen is a suggestion to run the test again - completing all the cycle.
Entering test date, and then filling the results from case management screen, which is pretty much a standard behavior, so I don't see a need for a popup.

**Comment by jeanette-pelizzon** [comment]
Let's discuss Monday in our meeting. 

This is what should happen at the next visit if the test was previously run and the results were not input because the next time they will be back at the health center is for their next visit.

**Comment by jeanette-pelizzon** [comment]
Discussed in our meeting 1/24:

(1) If result is not logged, the test will auto close at day 15. 

(2) The result should be logged in the progress report as missing 

(3) The test should reappear at the next visit, if it isn't already meant to happen at that visit.

**Comment by anvmn** [comment]
@LudmilaGoichman deployed to Nutrition environment.
Please test https://github.com/TIP-Global-Health/eheza-app/issues/65#issuecomment-1020303899

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon 

- Nutrition env
- Tablet

### Checked and Approved:
1.  If result is not logged, the test auto closes at day 15

the first day | day 15 |
---|---
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152319570-b16d670b-cee3-41d5-88a8-31fe29f08b2c.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152319873-40354ff6-bb3c-48cb-8f11-7425c45403b8.png">

2. The result is logged in the progress report as missing

the first day | day 15 |
---|---
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152319365-f211b256-3dc6-4a9e-95b5-63a3386e9965.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152319469-e5534519-c017-4a35-97f2-62b4e61793f4.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152320062-0468c26e-4b68-43c2-8972-ade025fcd1ec.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152320236-8746b5ef-8cb7-478e-8324-20bd136e2a42.png">


3. The test reappears at the next visit, if it isn't already meant to happen at that visit.

tests that shouldn't have appeared if the result hadn't been missed | the appearance of tests that shouldn't have appeared if the result hadn't been missed |
---|---
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152321369-5b677349-8689-493c-aaf1-8e2fc12fb370.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152321268-48883f1d-d4be-4733-a076-c55a8203b94a.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152321611-f87560e6-fc9a-42a7-8f0b-5517728c210a.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152321725-1a7e676d-1aaa-4da8-936b-c8a7e23f7247.png">

4. The test with missing results that reappeared again on the next visit and was performed and logged, doesn't appear on the next visit (this check appears only if it's supposed to occur on this visit anyway).

missing results from the first encounter | pending results at the second encounter | logged results at the third encounter | available test activities at the third encounter |
---|---|---|---
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152333044-52b26e82-1042-4a8c-8dab-df1ac714e0f1.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152333136-dd266732-8747-4f08-9be6-8ab3f2595dc7.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152333293-2de8d378-5188-4a21-b21b-7489db22fd70.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152333350-ea82ec05-387e-4dd6-a752-a831862a5a0e.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152333556-bcde4387-d00a-4ec9-a52e-54be86a0e213.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152333685-5f70694e-4a0b-4433-8af1-e502bb74474c.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152334000-871a992f-3297-4c7b-aa86-92991f5ce08a.png">


5. Full flow when all tests were missed:

//Urine Short Dipstick test was performed at the first and third visits, and Urine Long Dipstick test at the second and fourth visits


encounter | at the beginning of the visit | examples of Lab History with missing results at the beginning of the visit | available test activities | at the end of the visit | examples of Lab History with missing results at the end of the visit |
---|---|---|---|---|---
| the first encounter |  |  |  |<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152322125-a195259b-9aff-4fe4-ba2d-102a386c7a35.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152322192-4caef15a-00cd-4c24-a9e9-639f3c03a937.png">|  | 
|34 weeks visit | <img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152322550-7d2f54fd-44f8-4159-893f-efc806a44053.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152322600-cfd3cba5-709e-44f2-bf42-bec1a5a88042.png">|  |<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152322718-f3dd29b6-adea-4bbb-ab20-03a614567a88.png"><img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152322827-61e6a81c-380a-4ee3-9fca-7961cc726826.png">|<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152323382-91b3b7b2-475e-4c5a-ae75-65edb098d230.png"><img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152323515-4c8bf3d0-3067-4e04-835b-18e519f8a642.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152323827-ceead542-1703-4845-a565-e471f46ea9e0.png"><img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152323867-bde9175c-30c4-4faf-90d1-236e44c85fa8.png">
|38 weeks visit | <img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152324154-5057e2da-5b06-4a51-93c3-ab1c89ee1e74.png"><img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152324253-29126e4e-7905-4e12-b7a6-54f0f6f82311.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152324714-3ba2d165-18a2-4f40-83e9-428cab8dda9d.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152324759-931faa6f-2826-4205-9749-9e77f2d56b9b.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152324865-3f1154e3-3d50-470d-9843-c5f84beecde7.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152324915-74f7c30f-faf1-4ed6-8ef0-3690814050f5.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325024-952a8450-b888-4e94-b0af-ec2c99fb90d2.png"><img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325133-ad01f53e-9b82-4d42-bf40-79c155f40f0d.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325354-844957ae-fa20-4c26-a53a-8ff4b45af2ef.png"><img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325456-79746fe3-3386-4b7f-9261-ab1f2f4d18af.png">
the encounter after 38 weeks visit | <img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325674-435a145b-b40b-4c0f-a4b9-9f090a92cb3d.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325785-1b10ff1f-25fd-46a2-9cc7-595a3d260b44.png">|<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325884-b0623b9d-0ae1-45e7-8533-77810ed0e80d.png"><img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152325964-3c944c97-d12b-4f71-b3bc-eca8654e3877.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152326041-bb9f8535-8878-4f70-bc15-b53df59d9ec9.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152326135-c577de16-cde4-4c82-ba1c-7c201437dd41.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152327850-752ea960-31a0-4f45-b6c6-17f04853168b.png"><img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152328007-0858d963-0723-4e23-8384-4aff07e1194b.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152327890-0535a851-4b72-4b9c-9a01-9aa49f9bceb9.png"><img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152327936-b3d3b5e9-e626-4b55-944d-bfcbd0a4aff5.png">
after performing/reporting all tests | <img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152328292-272348c4-55d8-4b5c-af45-75611d588394.png"><img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152328550-9e24c4cc-e114-4d54-8bdf-9938094276ad.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152328362-7662fd7f-68cf-486a-9b11-5c900af302b7.png"><img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152328460-1739da08-1d7d-446b-9307-fb83022379f0.png">
