### ISSUE TITLE
ANC @ Health Center - Labs - Random Blood Sugar [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#66]
## Issue 

The labs for Random Blood Sugar are run on the first ANC Antenatal visit and ~~in the future if glucose is +2 or more in urine dipstick (long dip)~~. There are three inputs. There are NO results input for this test in this flow. See note below.

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here: | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen. Date input is shown here:
--|--
<img width="465" alt="*No checkboxes" src="https://user-images.githubusercontent.com/77505464/140407640-c352efdb-7518-4287-8876-646dc04cc11e.png"> | <img width="499" alt="*Date Input" src="https://user-images.githubusercontent.com/77505464/140407680-7fac49bb-079e-4de1-83be-19337617db9a.png">

### Design
Please refer to [ANC Labs - Full Prototype](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) in Figma for design.

Screen One | Screen Two | Screen Three 
--|--|--
<img width="304" alt="Screen Shot 2021-11-04 at 3 32 10 PM" src="https://user-images.githubusercontent.com/77505464/140410744-fb38915c-db77-4249-99ac-e18581c6f113.png"> | <img width="303" alt="Screen Shot 2021-11-04 at 3 32 17 PM" src="https://user-images.githubusercontent.com/77505464/140410762-bc782140-f84e-4187-9afc-c630cd4a8512.png"> | <img width="307" alt="Screen Shot 2021-11-04 at 3 32 26 PM" src="https://user-images.githubusercontent.com/77505464/140410778-6dce9b4a-21f3-4b74-bcb8-e01ac8836504.png">

### Notes

- Random Blood Sugar results are sent to the lab and results are given later that same day. Results input is on a separate screen and flow. You can see the issue for the results screen[ here.](https://github.com/Gizra/ihangane/issues/2838) 
- Please note the top of the screen should read "Labs" or "Lab Results" which is appropriate for the screen. Noticed after I made all the issues that the title of the screens were off.

## To Do

- Create activity
- style per design
### Clarification

- Clarify requirement around: `in the future if glucose is +2 or more in urine dipstick (long dip)`

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> are run on the first ANC Antenatal visit and in the future if glucose is +2 or more in urine dipstick (long dip)

This does not sum up. Dipstick test is not an immediate one, so, we will not know Glucose level until it's results are entered. How would we decide if to run Random Blood Sugar or not?

//cc @isapisa

**Comment by jeanette-pelizzon** [comment]
Spoke to Wendy about this and we need more information about what is happening on the ground at the Health Center's to get a definitive answer. We will be checking with the team on Wednesday and will hopefully have more input and an answer then!

**Comment by isapisa** [comment]
@anvmn for now, please go ahead with the "usual" logic and disregard `if glucose is +2 or more in urine dipstick (long dip)`.

@jeanette-pelizzon once you have clarification on this criteria, can you open a separate issue to implement this?

**Comment by jeanette-pelizzon** [comment]
New issue for screen is Gizra/ihangane#2900

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> New issue for screen is Gizra/ihangane#2900

I believe this comment belongs to another issue, as it's about progress report.

We still need clarification here.

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- Nutrition Environment
- tablet

### Checked and Approved:
1. the activity has been created and styled per design:

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715724-e62f53ae-f04b-467b-8b2c-231f7bef8125.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715771-43b80c77-808e-4b00-9b73-0a935ac6ecae.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715796-9da15ada-4b6b-4a88-89f9-3c8f7e208fb9.png">
---|---|---|

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715815-8b2f7332-d9d1-4c0b-b01c-7f26cab5e09a.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715822-fa018dd0-d966-448c-bd92-1b5b45cd4498.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715830-beb61f9d-5243-46a6-8631-95e4b2232cd0.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715855-5dbf4ab7-f720-40ef-b82a-7b3181c1680f.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715865-15029857-11d5-47cf-878a-96727b80d917.png">
---|---|---|---|---


2. logic for date input and calendar has been created ^^

3. The title of the sub-activity is "Laboratory".
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145715753-10da4cf0-85f0-4436-a411-ea5b93d66cc2.png">

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition Environment
- tablet

### Question/Found Issue:

 >If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen. Date input is shown here:

the answer to the second question is "no", but `the results input will populate directly on this screen` cannot be performed, because the result field is missing:

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148102643-bead4c65-9bbb-4961-bc8a-5ed96350e31d.png">


### Checked and Approved:
the activity has been created and styled per design:

1. >Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here:


the answer is "no":

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148101830-153f5f0d-c7bc-4df0-850d-60ba3134b411.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148101882-764e7110-a337-47c2-b497-691cb0d976f3.png">
---|---

2.  >If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. 

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148102168-67fdd718-2a60-4dc1-91a7-ade2b8641f11.png">


3. >If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen. Date input is shown here:

the answer to the second question is "no":

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148102323-4e7fa5af-b968-41cc-80d8-c2329b34a0cf.png">

**Comment by adamhstewart** [comment]
@anvmn in reference to the first question. This looks correct as designed, but I'll ask you to take a look to be sure.

**Comment by anvmn** [comment]
@adamhstewart 

Yes, design is correct. Result is filled from Case management screen.

**Comment by anvmn** [comment]
Moving to client acceptance
