### ISSUE TITLE
ANC @ Health Center - Labs - Random Blood Sugar Results [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#67]
## Issue

**Overview**
During an ANC encounter, a patient sees a nurse who collects the appropriate samples for each test and then sends them to the lab (unless it is a rapid test). The samples are then processed by the lab and results are returned later that day. The patient will return to see the nurse after several hours and receive the results of the labs. Nurses will navigate from their Case Management screen to each patient awaiting lab results. The sub-activities will be all the tests that have been run but they do not yet have results for. The nurse will select the test she has results for and input them. She will do this for all tests she has results for. When she hits save that result will appear in the Progress Report for that patient.

**Random Blood Sugar Specific**
Lab results are input as a numerical value (example: 105) 

<img width="310" alt="Screen Shot 2021-11-04 at 4 10 57 PM" src="https://user-images.githubusercontent.com/77505464/140412633-f8ddc1e7-cf73-4ad5-a127-a7f971c76b96.png">

Screen One | Screen Two 
--|-- 
<img width="289" alt="Screen Shot 2021-11-04 at 4 11 44 PM" src="https://user-images.githubusercontent.com/77505464/140412733-7435e620-cb8e-41a9-8b54-f58339de9c5b.png"> | <img width="286" alt="Screen Shot 2021-11-04 at 4 11 49 PM" src="https://user-images.githubusercontent.com/77505464/140412745-1385d104-5799-403b-929b-a64f3a3430de.png">

### Note 
You can see the Labs input screen issue for Random Blood Sugar [here.](https://github.com/Gizra/ihangane/issues/2837)

## To Do

- Create activity
- Style per design

**Comment by adamhstewart** [comment]
@LudmilaGoichman seems to me I put this issue in the wrong column. if you already tested it just move over.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition Environment
- tablet

### Questions/Found Issues:
1. According to the design it should be `Results`:

<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104523-686dd5ba-5843-4ba3-99b1-c5fb0696e4b1.png">

and this is relevant for the following tests:

- Blood Group + Rhesus Results
- Hemoglobin
- Urine Dipstick
 Example:

![140399234-2baf951a-4233-4ea1-b01e-e064b84a537e_png__364×696_](https://user-images.githubusercontent.com/35059802/148107316-f50c5ce4-a3a4-4a1a-af8b-c58e0ed32228.png)| ![148073893-bca463ea-629a-4a4d-bffe-18b5942aa30e_png__726×1164_](https://user-images.githubusercontent.com/35059802/148107373-0823522c-2bae-47fb-a682-bc53025ca823.png)
---|---

2. >Lab results are input as a numerical value (example: 105)
Should only numbers without decimal digits be allowed?

<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104819-1a905f39-6594-4af8-b8a0-69c6d69576ee.png">

3. When I entered the result `999.888` ^^, synced and opened the Content tab in the backend, I got the following error:

<img width="1071" alt="nutrition-ihangane_pantheonsite_io_says_and_Content___E-Heza_System_png" src="https://user-images.githubusercontent.com/35059802/148105236-49788a47-f131-48d8-85d6-0db25e31dcd4.png">|<img width="1240" alt="nutrition-ihangane_pantheonsite_io_says_and_Content___E-Heza_System_png" src="https://user-images.githubusercontent.com/35059802/148105284-9f6add6b-bffb-4e7e-a679-6ed6ebfeb62c.png">|<img width="1107" alt="nutrition-ihangane_pantheonsite_io_says_and_Content___E-Heza_System_png" src="https://user-images.githubusercontent.com/35059802/148105362-e4b79752-83cb-4e45-83ca-161e65ed3a4b.png">|<img width="1002" alt="nutrition-ihangane_pantheonsite_io_says_and_Content___E-Heza_System_png" src="https://user-images.githubusercontent.com/35059802/148105392-0f3fc246-b9ff-4493-a2b5-2fd8a4685dcf.png">
---|---|---|---

and the result in the report was `Results Missing`:

<img width="544" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148105663-50c30daf-5ee6-45b7-a63b-e8fbaa06f310.png">

and the relevant node didn't contain the value at all:

<img width="888" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148105799-a14ea470-0b0b-4f35-881a-ce9cea21c345.png">

and the test didn't appear in the subsequent encounter and in the results activity after this subsequent encounter:

<img width="367" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148106469-069e3f2c-f45b-4fb9-ac23-c06be35e9be0.png">|<img width="367" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148106587-cee6d76b-bab1-4f4b-8bf5-8d60d200d9db.png">
---|---

4. When I tried to reproduce the error from the previous point, I entered the following results:

<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148108378-330b9ffe-8d73-40d2-96cc-1b5730e964c1.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148108408-e0fe86b1-bc93-4295-86a4-3ac7b59e6687.png">
---|---

and I got sync error on upload (the patient Cyiza Rose, Rwankuba HC):

<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148108700-43037060-6443-40c7-a1c4-933271191ebf.png">|![Sync_incident_-_Content_upload_-_27f7b6fa-c50b-5c9d-b36a-fda8d48ef6ed___E-Heza_System](https://user-images.githubusercontent.com/35059802/148108939-b407040b-f692-46ec-be4d-fa91c05ee619.png)
---|---

but the report contains both values:

<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148108838-b5ffbb62-a77a-4ba7-a71e-c48c159aeb81.png">

and now the env is stuck due to this error. @anvmn, could you please fix this?

### Checked and Approved
 sub-activity has been created

The Flow1 (with problems):

 first encounter | case management | new sub-activity | only numbers can be entered | the result field is mandatory | 
---|---|---|---|---|
<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104304-54cd0b9b-4b67-4d47-89c0-1ae2db8bdde6.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104337-66c5ee32-e74d-408d-8329-75ca878e40dd.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104406-c6428d6c-28b6-418d-9a0a-31fc0ef0eec5.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104583-fab8346f-de62-459a-b08a-6d26117ab9d6.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148104868-8d9f0ee5-e024-4d61-8ae9-6f73bc7ef6c0.png">

The Flow2

 first encounter | report before getting result | case management | the result | the report | 
---|---|---|---|---|
<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148107641-8dc1c7e8-05b5-4d71-9fc4-3df95c72bbb0.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148107838-b8f118a0-c494-4d33-a495-c49151db0ae3.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148107932-4576f637-aa51-4c51-b6ff-a071ee48ff42.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148108044-a01cd0c3-7553-4041-88ff-062668f59b83.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148108104-f2269992-de86-408d-b30d-607e8fec8776.png">

**Comment by adamhstewart** [comment]
@anvmn there is a small typo ("results") to change from point 1

The other findings seem sync related and maybe aren't issues at all, but can you investigate?

**Comment by anvmn** [comment]
@adamhstewart 

The problem is that we send Float value from client, while backend expect an Int.
I think that sugar count does not have decimal, and we need to fix client side. Can you confirm please?

**Comment by adamhstewart** [comment]
@anvmn checkec and confirmed mg/L should have no decimal. The backend wins.

**Comment by jeanette-pelizzon** [comment]
"Result" is okay to use as it is individual inputs

**Comment by anvmn** [comment]
@adamhstewart 

Issue is fixed at #99.
Since we use standard input (`type=number`), we will not limit the decimals (though if there're no decimals), nurses should not be trying to enter any.
However, we will make sure that final value that is uploaded to backend is an Int.

**Comment by anvmn** [comment]
@LudmilaGoichman deployed to Nutrition environment.
Please test https://github.com/TIP-Global-Health/eheza-app/issues/67#issuecomment-1008932683

**Comment by LudmilaGoichman** [comment]
@isapisa 

- Nutrition env.
- tablet

### Questions and Found Issues:
1. This issue has been fixed by @anvmn and rechecked ~~Activities for Labs Results in Case management don't appear (Case Management is empty)~~

Before fixing | After fixing |
---|---
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152166867-2835ccf1-3a12-4cf3-ae5b-4480efdd98b5.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152167012-4b4e4428-5aff-46fd-8186-2f23910ad63a.png">

2. Sugar count field is empty when the entered lab result is 0. Is it ok? (this doesn't affect the presentation of the result in report in app)

![Edit_Prenatal_Random_Blood_Sugar_Test_Prenatal_Random_Blood_Sugar_Test_-_Blood_sugar_test2_-_2022-02-02___E-Heza_System](https://user-images.githubusercontent.com/35059802/152164948-e3d20251-2b4b-4b2f-b07f-50bd09247a12.png)

3. If the nurse still entered a lab result with numbers with decimals, maybe that number should be rounded off? For example in this case it would be one, not zero:

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152167974-29d3d84b-2d2d-4171-b4cb-46cc3e0027f1.png">|![Edit_Prenatal_Random_Blood_Sugar_Test_Prenatal_Random_Blood_Sugar_Test_-_Blood_sugar_test2_-_2022-02-02___E-Heza_System](https://user-images.githubusercontent.com/35059802/152164948-e3d20251-2b4b-4b2f-b07f-50bd09247a12.png)
---|---

### Checked and Approved:
final value that is uploaded to backend is an Integer. Examples:

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152162884-e1eded53-dd51-4ad1-90d8-9b1abfc7c056.png">|![Edit_Prenatal_Random_Blood_Sugar_Test_Prenatal_Random_Blood_Sugar_Test_-_Blood_test_Blood_test_-_2022-02-02___E-Heza_System](https://user-images.githubusercontent.com/35059802/152160817-6e268924-ab5c-40a8-8ce7-fe1a2ddd40bf.png)|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152162975-afa74e5a-a8f9-4a88-a000-ee317006361a.png">
---|---|---

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152163038-7e6927ee-3ecc-4d20-a34d-28bf710d3ee6.png">|![Edit_Prenatal_Random_Blood_Sugar_Test_Prenatal_Random_Blood_Sugar_Test_-_Blood_sugar_test2_-_2022-02-02___E-Heza_System](https://user-images.githubusercontent.com/35059802/152165066-a0db8a6e-f529-4cb9-a8a3-b03ae6be0e96.png)|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152165275-ced95c77-1a62-4e9e-a15b-f878f08994e7.png">
---|---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

I do not think we should round anytrhing, because at real case scenario nurses will enter integer values for blood sugar.

Tested the 0, and I do see it on backend:
![Selection_463](https://user-images.githubusercontent.com/17882245/152169350-1ce6fc77-a3a2-4a3f-95a8-cff55940ed42.png)

Can you recheck this please?
