### ISSUE TITLE
NCDA - Desktop - Entry Flow

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#695]
## Issue 

We need to have an entry flow for people to view NCDA dashboards from a desktop. This interface would have them put in an email and a password. From the icons, they would be linked to the appropriate next screen. 

[FIGMA](https://www.figma.com/file/l0bvoD2VyyFc146VVIYWOQ/NCDA?node-id=511-3244&t=R8x8bNtIb1zPSbGl-0)

![Desktop - 1](https://user-images.githubusercontent.com/77505464/233880266-d53c062b-6c55-4a89-b910-e78e14b21620.jpg)

![Desktop - 2](https://user-images.githubusercontent.com/77505464/233880267-0c3f1271-469e-4b4d-a9e7-c5503e2b0088.jpg)

@adamhstewart: 
- Need to account for forgotten password - how will this work? Same as the pin?

**Comment by anvmn** [comment]
@adamhstewart 

Since this runs on backend, I don't see a need for separate login screen.
As discussed, we'll have a dedicated page, and whoever is logged in will be able to navgate to it.
Here we **need to decide** if we want to assign dedicated privileges, or allow access to all.

Also, it's not clear why we have both Dashboards and Stock Management.
We don't need a selection screen, as we only deal with Agregated NCDA here.

**Comment by anvmn** [comment]
Not relevant for selected implementation. Closing.
