### ISSUE TITLE
NCDA CHW Questionnaire - Universal Interventions [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#746]
## Issue

The universal intervention screen tracks/verifies immunization, and the receipt of FBF/nutritional supplements
<img width="296" alt="NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/258a6492-a2f2-4734-98e0-e5bd3cec7f7d">

## Tasks
- Render the frontend page as designed
- Implement the following logice
    - Display the next scheduled immunization date required
    - If appropriate display the number of monthly SPV visits the child has missed.
    - If the answer to "Is this correct" is "no", display the text: "provide the counseling to the mother to update the child's vaccination record with a Nurse through a Standard Pediatric Visit" 
    - If the answer to the question "Is she taking it?" is "no", display the text "Provide counseling to the mother on the consequences that may occur to the mother and the child."

**Comment by Diama1** [comment]
@anvmn @adamhstewart 
|  Question       |     Counseling    |
|  ---------------     |   -------------------- |
|  According to E-Heza you have missed X (months of Immunization)  appointment, Is this correct? | Provide counseling to the mother by explaining the importance of the immunization |
| Did you receive food supplementation? is the child taking it? |  Provides counseling on the importance of Ongera and FBF and advise them to go to the Health center to recieve them.|

**Comment by adamhstewart** [comment]
@anvmn Edits for all sections here: https://docs.google.com/document/d/12UHUCHKzpaeD-qvxZYASamZcXv1UpquMbcQwVyhymoQ/edit?usp=sharing

**Comment by anvmn** [comment]
@adamhstewart 

![Selection_2034](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/0db43d6b-d3a7-4763-8570-7f947b8b8be0)

1. Since next immunization appointment is calculated, we'll need to load all well-child data, and since this calculation is complex, it will take some time to complete. Also, this may cause lag when responding to changes on form (checking answers, click on buttons, etc...).
2. We don't have concept of missed immunization appointments. If child needs to receive vacinations, thery are given on demand basis. Next appointment date is only a suggestion for optimal date.
3. Should there be some kind of way to direct child to SPV encounter?

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
