### ISSUE TITLE
NCDA CHW Questionnaire - Targeted Interventions [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#748]
## Issue

<img width="296" alt="NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/d2150a3a-bb9b-40da-98a1-5591d0a4a3a3">

**Comment by adamhstewart** [comment]
Logic:

- "Please Check MUAC" Only show this question if the child does not already have acute malnutrition according to E-Heza 
- Each of the indented questions is conditional on a "yes" answer from the previous question
- Ignore the red instructional on the design page (design updated): https://www.figma.com/file/l0bvoD2VyyFc146VVIYWOQ/NCDA?type=design&node-id=601-3834&t=gmXivJ678PZ5Znh5-0

**Comment by Diama1** [comment]
@anvmn @adamhstewart 
|  Question       |     Counseling    |
|  ---------------     |   -------------------- |
|  **are they receiving it**?(Sub-question for Is the mother or the child beneficiary of cash transfer e.g. NSDS, VUP). | Provide counseling to the mother to go to the local government in charge and advocate for them. |
|Receipt of conditional food items including small livestock? |  Provide counseling to the beneficiaries to go to the local government in charge and advocate for them.|
| **Is the child being treated**?(Sub-question for Please check MUAC. Does the child have acute malnutrition?) | Provide the counseling about preventing acute malnutrition and send the child to the Health center. |
| **Does the child receive support?** (Sub-question for Does the child have disability?) | Provide counseling to the mother to take the child to the Health center so that they can get the support needed. |

**Comment by anvmn** [comment]
@adamhstewart 

> "Please Check MUAC" Only show this question if the child does not already have acute malnutrition according to E-Heza

1. Acute malnutrition can be diagnosed at multiple types of encounters, so we'll need to load all data.
2. We got 2 types of diagnoses - severe and moderate. Do both count?
3. Once child is diagnosed with Acute malnutrition, it is permanent, correct?

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
