### ISSUE TITLE
ANC Labs - bind new design for Calendar Widget [2h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#82]
After https://github.com/TIP-Global-Health/eheza-app/pull/14 is merged

**Comment by anvmn** [comment]
FYI @adamhstewart.

Maybe this issue needs to be cloned to public repo?

**Comment by anvmn** [comment]
@LudmilaGoichman please test on Nutrition env

**Comment by adamhstewart** [comment]
@anvmn Calendar looks great - there seems to be an issue with the default date (at least in the pregnancy dating where I started). It seems there is no default, and therefore a user can select 2021 Jan (indeed seems forced into it even if they do select 2022).

https://www.loom.com/share/b3dad534243a41c79533345c5ed5574f

In every case we should start the user with some default position in the calendar - in this case the date which is 1, 3, or 6 months from the current date based on the previous question.

**Comment by adamhstewart** [comment]
^^ amend comment above - not "every" case some cases we have no default so an empty field is OK.

But, still there's an issue for 2021 - Here (while registering a new patient, birth date field)  I select 2021 and only get 1-4 available (as if it were 2022)

![image](https://user-images.githubusercontent.com/688507/148094340-1c120cbe-084b-430f-8718-f55496867d81.png)

**Comment by adamhstewart** [comment]
## Final Review -  Issues found

1. There is a bug where if you select the year 2022, 2021 is populated in the box and the dates are limited to the past dates in January, as shown above

2. There is an additional feature requirement for the following instances of the calendar - we want a "default position" for the calendar widget (different than a default date, because we don;t want to prefill a date for entry)

- In ANC - pregnancy dating, the default position should be the first date of the time period suggested by the previous question.
- In ANC labs - the default position should be the current date (as it's likely that the lab was run in the few days previous)
- In SPV Immunization - the default position should be the next prescribed dose for the given vaccination.

Let's proceed on the first finding - on the second finding, I'm not certain it's even possible as described, so will push to scrum discussion.

**Comment by anvmn** [comment]
@adamhstewart 
Issue 1 fixed at #99

**Comment by adamhstewart** [comment]
@anvmn leaving a note here, but I'm going to re-address point 2 from QA above in #13 as it's broader than ANC Labs.
