### ISSUE TITLE
ANC Progress Report - Lab History [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#83]
## Issue 

Related: https://github.com/Gizra/ihangane/issues/2886

The lab section of the ANC progress report will allow a nurse or CHW to see historical lab data. It will be similar to the SVP progress report where we click out into more detail for Acute Illness history. 

Arrows next to each test will allow a nurse or CHW to see all past results for that specific test | Once an arrow is clicked, they will be taken to this screen. Any missing results will be labeled as such. 
--|--
<img width="468" alt="Screen Shot 2021-12-08 at 4 21 15 PM" src="https://user-images.githubusercontent.com/77505464/145286212-bb7ffd96-7739-4553-8cc6-2af9c33cb155.png"> | <img width="205" alt="Screen Shot 2021-12-08 at 4 22 15 PM" src="https://user-images.githubusercontent.com/77505464/145286304-3646da96-4cb5-4873-9bf7-52e1979bdbcc.png">

### To Do

- Create logic for displaying historic lab data on new screen
- Logic for missing result + label 
- Style per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> The lab section of the ANC progress report will be updated to allow it to record and show historical lab data.

Seems to me that it should show, but not record.
Recording is done from Case management.

**Comment by isapisa** [comment]
updated the issue as this is for Lab History only.

**Comment by anvmn** [comment]
@LudmilaGoichman please test on Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env
- tablet


### Checked and Approved
1. logic for displaying historic lab data on new screen has been created
2. Logic for missing result + label has been implemented
2. screen has been styled per design

Example: 

- If the test is run multiple times, all historical results are shown
- the screen with historic lab data can be opened by clicking arrow in the report
- If the result has not yet been submitted through the case management, a label with "Results pending" appears.
- If the result has not yet been submitted through case management and more than 14 days have passed since the ANC encounter, a label with "Results missing" appears.


<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148681627-7b2d4de0-420c-4b75-905f-c4f817f28ed1.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680604-5ae4049f-8429-445c-98d2-4ca616bc8ae5.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680578-45f1d56a-0544-4625-a3ab-f6985758cffd.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148681651-0ef6bb91-0737-45e2-902f-b6dee637c932.png">
---|---|---|---
