### ISSUE TITLE
ANC - Health Center - Lab Results on Progress Report [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#84]
## Issue 

To accommodate the changes made in the ANC flow at the Health Center level and to better integrate CHW's and Nurses, we have made some changes to the ANC progress report. 

Shows the date the lab was run and the result. If a result is not yet submitted through case management, a label with "pending" should appear. 

**If a test is run multiple times, we need to show all historical results.** (similar to how we did the acute illness history in the SPV progress report)

The lab results section of the progress report will be updated to look like this:
![image](https://user-images.githubusercontent.com/34378755/145394394-6588e55e-804b-4619-bc68-0dc768fa9cad.png)

## Design

**General**
The order was slightly rearranged. See full design on Figma [here] (https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) 

## To Do 

- Add Lab results section to progress report
- Style per design

### Clarifications

- **ON HOLD UNTIL WE ADDRESS ANC LOGIC** ~~The alert dots on the progress report~~
-  **YES** UPDATED DESIGNS COMING SOON ~~If a test is run multiple times, do we need to show all historical results or the most recent? Could we do an arrow to see historical results for a specific test? This was suggested by Theo for all results previously but we wanted results in the report.~~

**Comment by isapisa** [comment]
@jeanette-pelizzon the progress report shows the photos at the bottom whereas now it's still part of the patient progress. Should we change that as well?

**Comment by jeanette-pelizzon** [comment]
@isapisa yes, sorry the photos should be at the bottom. The order in that screenshot is correct in case I forgot any other changes.

**Comment by isapisa** [comment]
@jeanette-pelizzon Ok, made it a part of the issue. 
leaving you assign cause you mentioned other clarifications needed still.

**Comment by jeanette-pelizzon** [comment]
Update to the clarifications needed: 

- the dots will not be implemented right now
- historical lab data will be implemented similar to how we did the acute illness history in the SPV progress report. 

The lab results section of the progress report will be updated to look like this:
<img width="224" alt="Screen Shot 2021-12-06 at 3 38 18 PM" src="https://user-images.githubusercontent.com/77505464/144918925-253b81be-0fea-49fb-bfcb-3de66fa7105f.png">

When they hit the blue arrow, it will take them to a screen that shows the historical lab results for that specific lab: 
<img width="268" alt="Screen Shot 2021-12-06 at 3 41 34 PM" src="https://user-images.githubusercontent.com/77505464/144919319-043b059f-0447-463b-a359-61bbaeaeb960.png">

You'll see that if an old result was never input, it will have the red label that says that results pending. 

// @isapisa

**Comment by isapisa** [comment]
@jeanette-pelizzon can you please create a separate issue for the individual lab results screen?

**Comment by anvmn** [comment]
@LudmilaGoichman please test on Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env
- tablet

### Found Issues/Questions:
1. from https://github.com/TIP-Global-Health/eheza-app/issues/84#issuecomment-983751153:
>yes, sorry the photos should be at the bottom. 

But the photos are still displayed as part of the patient progress section. Example:
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680789-84be5abe-dd9a-472f-a0ab-9c391a2ba193.png">

2. I'm not sure if I understand correctly which date should appear:

> Shows the date the lab was run and the result. 

 the date when the measurements were taken for the test or when the test was processed in the laboratory (and the result was entered into the system). Currently it the first option the date when the measurements were taken for the test and I think it's correct

Example:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148681278-86a34227-0ea1-4558-853e-31a73f7d2489.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148681287-9d8dd850-02d3-4dab-ac90-f596bb4a34d8.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148681267-58c97bae-cd77-4466-8682-8cfffc1dfa23.png">
---|---|---

3. Is it okay that labels are "Results pending"/"Results missing" and not just "Pending"/"Missing"?

> a label with "pending" should appear.

### Checked and Approved
 Lab results section has been added to progress report and styled per design.

Example: subsequent encounter. The report:

- Shows the date the lab was run and the result.
- If the result has not yet been submitted through the case management, a label with "Results pending" appears.
- If the result has not yet been submitted through case management and more than 14 days have passed since the ANC encounter, a label with "Results missing" appears.
- If the test is run multiple times, all historical results are shown

| before test execution in current encounter | after text execution in current encounter| 
---|---
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680517-88443570-1dab-424f-93a4-8c4beb31b65c.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680525-2058885f-db25-4019-bd2d-c74a90023454.png">
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680604-5ae4049f-8429-445c-98d2-4ca616bc8ae5.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148680578-45f1d56a-0544-4625-a3ab-f6985758cffd.png">

**Comment by jeanette-pelizzon** [comment]
1) Photos can stay as they are 
2) The date that the lab was run so it is accurate as it is now. 
3) Labels can stay as they are. 

This is good to go for team acceptance. 

// @LudmilaGoichman @anvmn @adamhstewart
