### ISSUE TITLE
NCDA: Add Nutrition Measurements to "Targeted Interventions" Section [12h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#889]
## Issue

Under "Targeted interventions", we will add measurements for
- Length
- Weight
- MUAC

Conditionally if any of the above measurements are not within the normal range (as used in nutrition encounters), we will add the Nutritions signs question, also used in other nutrition encounters.

We will remove the existing MUAC question: "Please check MUAC. Does the child have acute malnutrition?"

An indication of acute malnutrition from the MUAC measurement (as used in nutrition encounters) should reveal the question: "Is the child being treated?" which is then mapped to the scorecard as before.

[Design](https://www.figma.com/file/l0bvoD2VyyFc146VVIYWOQ/NCDA?type=design&node-id=601-3834&mode=design&t=tmretWIUCF5A9kW7-0) (rough)

## Task
- Add the new questions and corresponding logic for previous measurements and Z-scores
- Add conditional logic for nutrition signs questions
- wire measurements to the backend

**Comment by anvmn** [comment]
@adamhstewart 

### Requirements analysis:

The requirements do not say so, but as I see it, Height, Weight and MUAC measurements are to be added only for Child Scorecard encounter.
Other 3 types of encounters that got NCDA activity, already take those measurements at separate activities, and I don't see why we'd want to have duplications.
Decision logic can be done based MUAC measurement, no matter where it was taken.

As for placement at Child Scorecard encounter, it will not be withing NCDA, but a separate (third) activity called Nutrition Assessment - similar to what we have at SPV encounter: 

![Selection_2322](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/d00b3546-4ee1-4185-ae24-d925e6f8b60f)


> An indication of acute malnutrition from the MUAC measurement (as used in nutrition encounters) should reveal the question: "Is the child being treated?" which is then mapped to the scorecard as before.

Currently, acute malnutrition inputs are shown only at Child Scorecard encounter, and only in case acute malnutrition was not diagnosed previously.
So, I suppose that the only change required here is that we need to be looking at measurement taken for MUAC, instead of '"Please check MUAC' question, and based on that, decide if to show the 'is being treated' question.

### Tasks (Child Scorecard enounter):

- Create 4 new content types, with all underlying infrastructure [**12h]**.
- Define new activity 'Nutrition Assessment' with 4 subactivities [**3h**]:
  -  Height
  - Weight
  - MUAC - conditional (shown from age of 6 month)
  - Nutrition - conditional (shown if one of previous 3 is off)
- For first 3, implement the previous measurements and Z-scores (note that measurements taken at Child Scorecard enounter will need to be taken into account when viewing then 'most recent' previous value) [**4h**].
- For Nutrition, integrate the assessment logic, so that acute malnutrition is recorded (similart to what we do at other types of encounters) [**2h**].
- Update logic for presentation of 'is being treated' logic [**1h**}.

### Estimation - 22h.

**Comment by anvmn** [comment]
@adamhstewart 

At https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1875508788, we have follwing argumentation for 'is being treated' question not being shown at HC:

![Selection_2327](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5b0dab3b-bcd6-479f-ba5d-ec37222ae866)

Now that we added MUAC for CHW, it does not stand anymore.
Should we show the question only for CHW still?

**Comment by anvmn** [comment]
Decision on ^^ - leave as is (show only for CHW).

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
